### ISSUE TITLE
Hospital and Practitioner Information as NDJSON

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#1069]
Create a `synthea.properties` setting to export the hospital and practitioner data as NDJSON.

### Discussed in https://github.com/synthetichealth/synthea/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **calidiaz0596** May 19, 2022</sup>
Hello, 

Excuse me if this is a dumb question, but is there a setting in the configuration file to have the hospital and practitioner information file export as a NDJSON file instead of JSON file? 

I tried manually adding "exporter.hospital.bulk_data = true" to the list to see if this would do anything, but no luck. 

I have also tried just taking the json files and convert them using an online converter but I keep getting the same error:  "Exception Occured: t.map is not a function"

Any help how I could export or convert these 2 files? 

![Screen Shot 2022-05-19 at 10 26 01 AM](https://user-images.githubusercontent.com/79172075/169335734-1fe249df-44a3-4855-b75b-9f65c07e9f3a.png)
![Screen Shot 2022-05-19 at 10 25 49 AM](https://user-images.githubusercontent.com/79172075/169335737-aa17d5a0-67e8-44f7-87b6-2e4365536909.png)

</div>

**Comment by IoTFier** [comment]
Hello @jawalonoski, I would appreciate the NDJSON capability for hospital and practitioner data.
Thank you.

**Comment by jawalonoski** [comment]
This should be fixed with #1096 merged.
