### ISSUE TITLE
Trouble entering a two-word state 

### ISSUE THREAD

**Issue by rhdolin** [synthetichealth/synthea#1084]
### What happened?

I'm trying to synthesize data for a population in New York, New York. There seems to be an issue with cities and states comprised of multiple words. I'm using the example from [here](https://github.com/synthetichealth/synthea/wiki/Demographics-for-Other-Areas), trying this: 

`.\run_synthea "New York"`

but getting a BUILD FAILED error.

### Environment

```markdown
I'm testing using windows, with java version "11.0.15.1" 2022-04-22 LTS
```

### Relevant log output

```shell
PS C:\Users\Bob\Documents\Code\synthea> .\run_synthea "New York"

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Bob\Documents\Code\synthea\build.gradle' line: 269

* What went wrong:
A problem occurred evaluating root project 'synthea'.
> startup failed:
  Script1.groovy: 1: Unexpected character: '\'' @ line 1, column 3.
     [ 'New
       ^

  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by jawalonoski** [comment]
Using Windows Command Prompt, you should be able to temporarily work around this issue:

```
gradlew.bat run -Params="['New York']"
```

**Comment by dehall** [comment]
I also notice that you appear to be running `run_synthea` instead of `run_synthea.bat`. I guess Powershell must support the necessary commands within the script, but I wonder if it handles spaces/quotes differently than shells in Linux/Mac do. Can you try running with the .bat version instead?

**Comment by rosscaleca** [comment]
I have been running into this issue on macOS. The following ended up working for me - moving the location to the front of the statement.

`./run_synthea ./run_synthea "New York" "New York" -p 1000 -a 40-90 --exporter.fhir.export false --exporter.csv.export true`

**Comment by fabkury** [comment]
The only thing that worked for me was to build the command line as described by @jawalonoski.

It is a mayhem of quoting and command line minutiae. Notice you have to build an object and pass it inside the brackets in -Params="[]". Example:

.\gradlew.bat run -Params="['New York', '-p', '1000', '--exporter.baseDirectory', '.\New York\', '-s', '42']"

Don't quote the arguments inside the [ ] beyond the single quotes ' '. Remember the double hyphen -- for the Synthea arguments inside the [ ] but single hyphen - for the -Params=.
