### ISSUE TITLE
FHIR Resource Type Filter

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#1104]
### Requested Feature

Modify the FHIR exporters to only export specific resources, similar to how the CSV exporter can include/exclude specific files:

https://github.com/synthetichealth/synthea/blob/c266ab656670fb7b7506b892245060944e4d9576/src/main/resources/synthea.properties#L36-L43

**Comment by willdalh** [comment]
Any update on this? 

I have found that I can hack a solution for this by commenting out certain parts in `org.mitre.synthea.export.FhirR4.java`. In my case the lines for `Claim` and `ExplanationOfBenefit`.

https://github.com/synthetichealth/synthea/blob/5d90e086985aecf69e8a1140d9793ad8f104fe73/src/main/java/org/mitre/synthea/export/FhirR4.java#L267-L337

Would you recommend any other way? Ideally the resources I want to omit should not be generated at all, but I guess there are some dependencies between these.

**Comment by jawalonoski** [comment]
I don't believe anyone is actively working on this yet. If you are motivated enough to issue a Pull Request, we'd happily consider it.

The hack you are using is fine for a quick local change, but you are correct that there are dependencies... or at least, references between the resources. Ideally each time a reference is created, it would instead be conditionally created based on what resources are being included/exported. This would need some pretty good test cases though to validate the results (broken references would be invalid).

**Comment by dehall** [comment]
Implemented in #1178
