### ISSUE TITLE
FIPS code for State / County?

### ISSUE THREAD

**Issue by ProfAaronBaird** [synthetichealth/synthea#1124]
### Requested Feature

I need to merge CSV data output from Synthea with county-level data sources, such as AHRF and County Health Rankings. It is great that the county name is included in patients.csv file under the COUNTY column/field, but it would be great if the FIPS code for the State/County could also be included. This would make the merge process much easier!

**Comment by jawalonoski** [comment]
This is probably not that difficult for us to add, since we already have this data within Synthea for the RIF exporter.

See https://github.com/synthetichealth/synthea/blob/master/src/main/resources/geography/fipscodes.csv

**Comment by ProfAaronBaird** [comment]
Sounds great and thank you. 

I was thinking of just doing this via zip to FIPS by just joining to the patient zip code that is output, but then saw that many of the patient records do not have a zip code. Then, I was thinking of just using county name, but all of the county names include "County" in the name, which is easy enough to strip off, but was thinking that FIPS would be easier.

I also just looked through the FIPS csv file that you provided the link to. That looks great. I did notice, though, when I searched for my own county here in Atlanta (Dekalb) that it was separated into two words "DE KALB" instead of one. So, minor issue, but there may be mistakes here and there in that file.

**Comment by jawalonoski** [comment]
Do you need FIPS state _and_ FIPS county, or is county itself sufficient?

It looks like the state code is the prefix to the county code anyway.

**Comment by ProfAaronBaird** [comment]
Thanks for checking. It is easier on my end if the state and county FIPS are concatenated into one 5 digit code (with a leading 0 if only 4 digits), as most county-level data that I am joining to uses this format, including the Area Health Resource Files (AHRF), County Health Rankings (CHR), etc., but I can also always add the state code if you end up with just the county code.
________________________________

**Comment by jawalonoski** [comment]
This should be addressed with PR #1165
