### ISSUE TITLE
BFD: Benes per Contract

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#1135]
### Requested Feature

`*** Migrated from Confluence ***`

Beneficiaries per contract. Realistically there should be about a 1% change across months. Also, the changes by year should be about 10-20% across years.

**Comment by hadleynet** [comment]
This was fixed by commit https://github.com/synthetichealth/synthea/pull/770/commits/4bf06a7efdcc81140be01415b7cf5097e83d64ea
