### ISSUE TITLE
BFD: Recent data

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#1138]
### Requested Feature

`*** Migrated from Confluence ***`

Newer data like claims (especially drug claims) within the last year, because sometimes they only show data within the last year in their apps

### Notes

May be addressed with a recent Synthea update allowing us to generate future claims for existing beneficiaries and then reveal them in the data as the future dates are reached.

**Comment by hadleynet** [comment]
See PR #1008

**Comment by jawalonoski** [comment]
Current under test, documented with BFD-2450 (last remaining task of epic BFD-2100)

**Comment by jawalonoski** [comment]
This is now deployed and updating.
