### ISSUE TITLE
BFD: Math adding up

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#1140]
### Requested Feature

`*** Migrated from Confluence ***`

Issues with 'math not adding up' from claims data

### Notes

Not using the new data, so this may be irrelevant to the Synthea team. Tracking here for examples/use cases in the wild

**Comment by hadleynet** [comment]
I think this was fixed by PR #1056.

**Comment by hadleynet** [comment]
Note that there are some related unit tests, see BB2RIFExporterTest#validateClaimTotals and validatePDETotals.

**Comment by jawalonoski** [comment]
Related to #1173

**Comment by hadleynet** [comment]
Related to #1278
