### ISSUE TITLE
BFD: Revenue Center Total Charge Line Item

### ISSUE THREAD

**Issue by hadleynet** [synthetichealth/synthea#1173]
### Requested Feature

Claims should include a "total charge" revenue center claim line that is the sum of the other line items.

**Comment by DevPJ9** [comment]
Hello, @hadleynet I would like to contribute. Can you please provide more info on requirements?

**Comment by hadleynet** [comment]
@DevPJ9 I'm actually working on a PR for this issue at the moment. Are you particularly interested in contributing to the BFD RIF export feature or in contributing to Synthea more generally?

**Comment by DevPJ9** [comment]
No problem @hadleynet, I just want to contribute to improve my knowledge and skills, so I am fine with any issue. Thanks for your reply :)
