### ISSUE TITLE
Injuries Timing Issue

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#118]
When a patient gets a Knee_Injury, the following sequence of states can be observed:

Knee_Injury [Simple]
ED_Visit_For_Knee_Injury [Encounter]
Torn_ACL [ConditionOnset]
Wait_For_Knee_Surgery [Delay]
Knee_Surgery_Encounter [Encounter]
Knee_Surgery_Procedure [Procedure]
Knee_Injury_Prescribe_Pain_Medication [Simple]
Knee_Injury_Prescribe_Non_Opioid [MedicationOrder]
Knee_Injury_CarePlan [CarePlanStart]

The problem I see is that the Knee_Injury_CarePlan state is referencing the ED_Visit_For_Knee_Injury state. Because the Wait_For_Knee_Surgery delay advances the clock by one week, the referenced ED visit violates the CarePlanStart requirement: "The CarePlanStart state must come after a target_encounter Encounter state in the module, but must have the same start time as that Encounter; otherwise it will not be recorded in the patient's record."

In my implementation, the problem manifests itself because the subsequent End_Injury_CarePlan state cannot find the CarePlan and throws an exception.

Here's the full state trace:

Knee_Injury [Simple]
ED_Visit_For_Knee_Injury [Encounter]
Torn_ACL [ConditionOnset]
Wait_For_Knee_Surgery [Delay]
Knee_Surgery_Encounter [Encounter]
Knee_Surgery_Procedure [Procedure]
Knee_Injury_Prescribe_Pain_Medication [Simple]
Knee_Injury_Prescribe_Non_Opioid [MedicationOrder]
Knee_Injury_CarePlan [CarePlanStart]
Knee_Injury_Recovery_Period [Delay]
End_Knee_Injury [ConditionEnd]
Conclude_Injury [Simple]
End_Injury_CarePlan [CarePlanEnd]

I tried, instead, to make the Knee_Injury_CarePlan reference the Knee_Surgery_Encounter. This worked for the Torn_ACL but results in another error in the Torn_Meniscus case where there is no Delay.

Knee_Injury [Simple]
ED_Visit_For_Knee_Injury [Encounter]
Torn_Meniscus [ConditionOnset]
Knee_Injury_CarePlan [CarePlanStart]
Knee_Injury_Recovery_Period [Delay]
End_Knee_Injury [ConditionEnd]
Conclude_Injury [Simple]
End_Injury_CarePlan [CarePlanEnd]

So its tricky I guess...

**Comment by jeffeastman** [comment]
Hmm, no, there IS a delay, but there's no Knee_Surgery_Encounter on the last trace. Still tricky...

**Comment by cjduffett** [comment]
Hi Jeff, great find! I'll take care of that first thing tomorrow. Looking at the module it looks like the timing of care plans may be an issue for several injuries. In each case there is a care plan that sometimes follow a Delay state. Since knee injuries are a more common injury (than burns or spinal injuries, for example) that's where it manifested itself first.
