### ISSUE TITLE
Data Dictionary

### ISSUE THREAD

**Issue by kennethleungty** [synthetichealth/synthea#1187]
### Requested Feature

Is there a data dictionary for the columns generated in Synthea?

For example, I am looking at encounters.csv, and I am not sure about the exact meanings behind the columns of: BASE_ENCOUNTER_COST, TOTAL_CLAIM_COST, REASONCODE.

**Comment by jawalonoski** [comment]
Let us know if any of the fields are not defined sufficiently.
