### ISSUE TITLE
A couple of proposed unit corrections

### ISSUE THREAD

**Issue by abrindam** [synthetichealth/synthea#1198]
### Sepsis Module
The `Lactate_Level` observation is coded as LOINC 59032-3 which is supposed to be Mass/Volume, but the unit being used is `mmol/L` which is Moles/Volume. The unit should be changed to `mg/dL`, or even better, the LOINC code 32693-4 should be used instead, which correctly corresponds to Moles/Volume.

https://github.com/synthetichealth/synthea/blob/7c14fea75daad705c311f9fa9916e65b550a0202/src/main/resources/modules/sepsis.json#L138

### Gallstones Module
In the `Complete_Blood_Count` section, the first item under `observations` has unit `K/uL` which per UCUM is "degrees Kelvin per microliter" when the intended unit is actually "thousands per microliter". The correct way to express this is `10*3/uL` (see the next item in the list, which is already doing this correctly).

https://github.com/synthetichealth/synthea/blob/a5228488e4627a26ee7dc3beea544de34b5cef25/src/main/resources/modules/gallstones.json#L1026

### Environment

```markdown
- OS: macOS 12.3 (21E230)
- Java: openjdk version "18.0.1" 2022-04-19
```

**Comment by jawalonoski** [comment]
## Sepsis Module
The "Common US Lab Results Rank" for `32693-4 Lactate [Moles/volume] in Blood` is 313, while the rating for `59032-3 Lactate [Mass/volume] in Blood` is 2444, so it is probably best to switch to the more commonly used LOINC code (i.e., `32693-4`).

Fortunately, that already coincides with the current units of measure (i.e., `mmol/L`) and the reference ranges used (e.g., `1 - 4`) according to the [Module Companion Guide](http://hdx.mitre.org/downloads/module_guides/Module_Companion_Guide_Sepsis_508.pdf) and the original source, [Andersen et al.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3975915/)

**Comment by jawalonoski** [comment]
## Gallstones Module

You are correct. Fix pending.

**Comment by abrindam** [comment]
Looks great! Agree with using `32693-4` based on rank.

**Comment by jawalonoski** [comment]
Fixed. with #1217.
