### ISSUE TITLE
How to assign one of multiple codes in ConditionOnset

### ISSUE THREAD

**Issue by r0sies** [synthetichealth/synthea#1201]
### What happened?

I have specified 8 different SNOMED codes related to hip fractures in a ConditionOnset state and assigned it to attribute "hip fractures". I was expecting Synthea to randomly? assign one of the 8 SNOMED codes to a patients however, it seems to only assign the first code listed. Is there a way for a patient to be assigned any one of the 8 hip fracture SNOMED codes, or should I define a separate ConditionOnset state for each of the 8 codes with a distributed transition across the 8 codes?
What does defining multiple codes in the ConditionOnset state do? Thanks for your help.

### Environment

```markdown
- OS: Windows 11
- Java: 17.0.5
```

### Relevant log output

```shell
"Fall": {
      "type": "ConditionOnset",
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": 17194005,
          "display": "Late effect of fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 263226008,
          "display": "Subcapital fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 5913000,
          "display": "Fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 359820003,
          "display": "Closed fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 409666003,
          "display": "Pathological fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 1705000,
          "display": "Closed fracture of base of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 704063001,
          "display": "Stress fracture of neck of femur"
        },
        {
          "system": "SNOMED-CT",
          "code": 431031001,
          "display": "Osteoporotic fracture of neck of femur"
        }
      ],
      "distributed_transition": [
        {
          "transition": "Emergency_Encounter",
          "distribution": 0.1
        },
        {
          "transition": "Terminal",
          "distribution": 0.9
        }
      ],
      "assign_to_attribute": "hip fractures",
      "target_encounter": "Emergency_Encounter"
    },
```

**Comment by jawalonoski** [comment]
> I was expecting Synthea to randomly? assign one of the 8 SNOMED codes to a patients however, it seems to only assign the first code listed. 

At ConditionOnset, technically **ALL** of the codes are added to the diagnosis. However, what is written out to the record depends on the exporter. Currently, most of the exporters use only the first code (e.g., both the FHIR and CSV exporters). Other exporters, such as the BFD RIF exporter, will use as many as it can.

> Is there a way for a patient to be assigned any one of the 8 hip fracture SNOMED codes, or should I define a separate ConditionOnset state for each of the 8 codes with a distributed transition across the 8 codes?

For now, you'd have to define 8 separate ConditionOnset states.

> What does defining multiple codes in the ConditionOnset state do? 

It assigns all the codes to the diagnosis. Most of the internal logic in Synthea only considers the first code (it considers this the "primary code". It is up to each exporter to determine what to do with the all of the extras. Most of the exporters only consider the first code.

**Comment by r0sies** [comment]
Thanks for clarifying Jason. I'll close this ticket.
