### ISSUE TITLE
Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05

### ISSUE THREAD

**Issue by vohuythao** [synthetichealth/synthea#1210]
### What happened?

Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05

Hello,

When I run the Single Patient API test with Inferno ONC Certification (g)(10) Standardized API Test Kit,
FHIR R4 ( Azure API for FHIR) with FHIR Proxy
US Core 3.1.1

I met this problem

![image](https://user-images.githubusercontent.com/14121587/204100676-25d127e7-9bee-47c1-9d78-314db003cdb1.png)

Go to more details

"fullUrl": "https://sfp-proxy23604.azurewebsites.net/fhir/Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05", "resource": { "resourceType": "OperationOutcome", "id": "3072650f-7d47-4426-ae20-e7ff1264c31d", "issue": [ { "severity": "warning", "code": "forbidden", "diagnostics": "Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05" } ] },

Then I search in FHIR data for Provenance ID and saw it also has reference to this Patient ID

![image](https://user-images.githubusercontent.com/14121587/204100719-d8ab3e04-42e1-4552-9e1d-51959d0f032d.png)

I think all the correct data is there in FHIR, just don't know why Inferno throw error.
Maybe the simulation data from Synthea is not correct

If you guys can suggest any hint, any keyword or any direction to troubleshoot, I am appreciate your help.
Or if you have batch bundle data that can pass all Inferno G10 test kit, could you please provide

I am appreciate your help. 
Thanks in advance

Thank you

### Environment

```markdown
Inferno
```

### Relevant log output

```shell
"fullUrl": "https://sfp-proxy23604.azurewebsites.net/fhir/Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05", "resource": { "resourceType": "OperationOutcome", "id": "3072650f-7d47-4426-ae20-e7ff1264c31d", "issue": [ { "severity": "warning", "code": "forbidden", "diagnostics": "Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05" } ] },
```

**Comment by vohuythao** [comment]
Hello @jawalonoski 

This data I took from Synthea data

**Comment by jawalonoski** [comment]
None of the zip files in `uscore-data-sets` contains `Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2` or `Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05`.

If you loaded data into your FHIR server using the transaction bundles, each Provenance correctly references resources within the transaction using URLs with `urn:uuid:` prefixes. During insertion, the server should rewrite these URLs.

If you loaded data into your FHIR server using the bulk data files, each Provenance references resources using URLs with a `Resource/ID` format. In which case, your server needs to know to map those `ID` identifiers to however it decided to rewrite the IDs of the resources in the other bulk files.

Either way, your screenshot shows an Inferno highlighting an error in your server, in that it is not properly handling `revInclude` parameters. We cannot help with that issue.
