### ISSUE TITLE
not able to build successfully

### ISSUE THREAD

**Issue by Anitha15890** [synthetichealth/synthea#1211]
### What happened?

when I clone the repo and run gradlew build check test, I get the following error

![image](https://user-images.githubusercontent.com/60096871/204151908-ded839e7-551c-441c-878a-0b7731823d07.png)

### Environment

```markdown
- OS: Windows 10 Pro
- Java:jdk1.8.0_351
```

**Comment by hadleynet** [comment]
Synthea requires a minimum of Java 11, you were using Java 8.
