### ISSUE TITLE
Wrong lab value unit or range in colorectal cancer module?

### ISSUE THREAD

**Issue by gotdan** [synthetichealth/synthea#1213]
### What happened?

I think the range for LOINC 2885-2 (Protein [Mass/volume] in Serum or Plasma) in the [colorectal cancer module](https://github.com/synthetichealth/synthea/blob/af4a81e1075a5913fa27056ac43fdfd3474086e1/src/main/resources/modules/colorectal_cancer.json#L1715) may be wrong. I seems like it should have a range of 6-8 or a unit of "g/L" with the current range. See the reference range at https://spectrumhealth.testcatalog.org/show/LAB118-1 .

**Comment by jawalonoski** [comment]
Thanks for the bug report @gotdan, I am confirming this is an error and we'll fix it.

**Comment by jawalonoski** [comment]
Your link is pointing at an old version of the module, and the current version has the corrected values already:

https://github.com/synthetichealth/synthea/blob/d9094e98e4cb51e331d7152b261d9dd1fa944453/src/main/resources/modules/colorectal_cancer.json#L1717-L1731

**Comment by gotdan** [comment]
Awesome, thanks - I'll update to the latest version!
