### ISSUE TITLE
DocumentReference/af20c556-650b-488f-4e2e-764d7ab714fd: DocumentReference.identifier[0]: if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)

### ISSUE THREAD

**Issue by vohuythao** [synthetichealth/synthea#1214]
### What happened?

Hello,

When I run the Inferno test, test 4.10.08, Single Patient.

I met this problem

![image](https://user-images.githubusercontent.com/14121587/204580637-38c7dbc2-fb7c-4f66-9d1c-802e2240bc96.png)

This is the NDJSON DocumentReference.identifier we use

"identifier":[{"system":"urn:ietf:rfc:3986","value":"DiagnosticReport/957e9339-9750-cd16-4733-0fdd47295465"}],

If you guys has any guidance or troubleshoot direction, please let me know

Thank you

### Environment

```markdown
Inferno
```

### Relevant log output

```shell
DocumentReference/af20c556-650b-488f-4e2e-764d7ab714fd: DocumentReference.identifier[0]: if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)
```

**Comment by jawalonoski** [comment]
This is probably not a Synthea bug.

The default format of the FHIR data that Synthea generates is validated against the US Core profiles. You can inspect our source code to see that the `identifier.value` we provide is a full URL.

https://github.com/synthetichealth/synthea/blob/1f76706bf766aa4de4c7c823aaafff9d5e899371/src/main/java/org/mitre/synthea/export/FhirR4.java#L2398-L2400

This means the bug likely exists in the way the server is ingesting the data.
