### ISSUE TITLE
Lupus Corticosteroid Issue

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#124]
Now that I'm throwing exceptions when target_encounter timing conditions aren't met, I'm seeing a persistent problem in the Lupus Module. Here's a trace:

 State Trace:
2017/01/06 08:16 Initial [Initial]
2041/12/31 08:16 Delay_Until_Lupus [Delay]
2017/01/13 08:16 Delay_Until_Lupus [Guard]
2041/12/27 08:16 Lupus [ConditionOnset]
2041/12/27 09:16 Lupus_Diagnosis [Encounter]
2042/01/03 08:16 Lupus_CarePlan [CarePlanStart]
2042/01/03 08:16 Lupus_Nonopioid_Pain_Medication [MedicationOrder]
2042/01/03 08:16 Corticosteroid [MedicationOrder]
2042/01/17 08:16 Corticosteroid_Treatment [Delay]
2042/01/17 08:16 End_Corticosteroid [MedicationEnd]
2043/01/17 08:16 Wait_For_Lupus_Flareup [Delay]
2043/01/17 09:16 Lupus_Flareup [Encounter]
2043/01/17 09:16 Immune_Suppressant [MedicationOrder]
2043/01/17 09:16 Corticosteroid [MedicationOrder]

The issue is that the Corticosteroid MedicationOrder refers to the Lupus_Diagnosis Encounter and that encounter has long passed. I added a new Flareup_Corticosteroid state and that fixed the problem. Here's my fix:

    "Immune_Suppressant": {
      "type": "MedicationOrder",
      "target_encounter": "Lupus_Flareup",
      "reason": "Lupus",
      "remarks": [
        "More aggressive immune suppressants are used for subsequent flares."
      ],
      "codes": [
        {
          "system": "RxNorm",
          "code": "835900",
          "display": "cycloSPORINE, modified 100 MG [Neoral]"
        }
      ],
      "direct_transition": "Flareup_Corticosteroid"
    },

    "Flareup_Corticosteroid": {
      "type": "MedicationOrder",
      "target_encounter": "Lupus_Flareup",
      "reason": "Lupus",
      "remarks": [
        "When introduced in higher levels than those produced by the body, corticosteroids ",
        "inhibit inflammation. However, doctors prefer to use these for as short a time period ",
        "as possible to avoid dangerous side effects."
      ],
      "codes": [
        {
          "system": "RxNorm",
          "code": "567645",
          "display": "predniSONE 2.5 MG [Deltasone]"
        }
      ],
      "direct_transition": "Corticosteroid_Treatment"
    },

**Comment by jawalonoski** [comment]
Fixed by #126
