### ISSUE TITLE
Generate Data for INPATIENT("IMP") 

### ISSUE THREAD

**Issue by arabinda-behera** [synthetichealth/synthea#1285]
### What happened?

How to generate data for INPATIENT("IMP") encounters ? I generated data for 1000 patients and all data generated are for OUTPATIENT("AMB").

### Environment

```markdown
- OS:
- Java:
```

**Comment by jawalonoski** [comment]
I just ran the following command:

```
./run_synthea -p 1000
```

## FHIR Results

FHIR Encounter Class | Count | Percentage | Note
------|-------|---------|------
AMB | 99739 | 95.06% | Equivalent to CSV "ambulatory", "outpatient", "urgentcare", and "wellness"
EMER | 3248 | 3.10% | Equivalent to CSV "emergency"
IMP | 1314 | 1.25% | Equivalent to CSV "inpatient" and "snf"
VR | 85 | 0.08% | Equivalent to CSV "virtual"
HH | 541 | 0.52% | Equivalent to CSV "home" and "hospice"
**TOTAL** | **104927** | **100.00%**

## CSV Results
CSV Encounter Class | Count | Percentage
------|-------|---------
ambulatory | 47701 | 45.46%
emergency | 3248 | 3.10%
home | 378 | 0.36%
hospice | 163 | 0.16%
inpatient | 1146 | 1.09%
outpatient | 14764 | 14.07%
snf | 168 | 0.16%
urgentcare | 7368 | 7.02%
virtual | 85 | 0.08%
wellness | 29906 | 28.50%
**TOTAL** | **104927** | **100.00%**
