### ISSUE TITLE
What Happened To Allergies?

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#142]
They are still referenced by the modules but gone from the wiki.

**Comment by jawalonoski** [comment]
Yes, good point. They seemed to have vanished yesterday.

The food allergies module correctly uses `AllergyOnset` and `AllergyEnd`, but the allergic rhinitis module records allergies as a condition... I believe those should be allergies too.

**Comment by jawalonoski** [comment]
Looking at the history of the state page, it doesn't look like `AllergyOnset` was ever added.

**Comment by dehall** [comment]
Sorry about that, I added the wiki notes to the PR but forgot to copy them over when it got merged. They're in now:  https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#allergyonset
