### ISSUE TITLE
Is Allergic Rhinitis a Condition or an AllergyIntolerance?

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#143]
Is Allergic Rhinitis a Condition or an AllergyIntolerance?

**Comment by cjduffett** [comment]
I think Allergic Rhinitis (AR) is best represented as a condition. Same with asthma, or eczema. These are medical conditions that are _caused_ by one or more allergies.

AllergyIntolerance seems better for describing specific allergies to substances (e.g. latex, pollen, bee stings, medication, etc.), and the severity of those allergies.

**Comment by jawalonoski** [comment]
OK. So, it is a condition. But the allergic rhinitis module gives codes for the condition _caused by_ animal dander and dust mites. Arguably, animal dander is a substance.

**Comment by cjduffett** [comment]
I see your point. I'll revise the module to have codes only for the condition, with no mention of the cause. So basically the patient will either have "Seasonal allergic rhinitis" or "Perennial allergic rhinitis".

**Comment by jawalonoski** [comment]
Let's discuss. Removing information isn't the greatest solution. This is the issue of pre coordinated versus post coordinated codes.

**Comment by cjduffett** [comment]
I made this change in https://github.com/synthetichealth/synthea/pull/150
