### ISSUE TITLE
AllergyIntolerance Types

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#145]
Presently the AllergyIntolerance `category` is hard-coded to `'food'`. However, other types of allergies will soon be modeled in Synthea (pending the Atopic Triad PR). FHIR also allows the following categories:

[`food`, `medication`, `biologic`, `environment`]

I propose we add a `category`, or alternatively `allergy_type` property to the  `AllergyOnset` state to make this configurable.

**Comment by dehall** [comment]
added in #872
