### ISSUE TITLE
FHIR Resources missing

### ISSUE THREAD

**Issue by schowdary55** [synthetichealth/synthea#1467]
[atrial_fibrillation.json](https://github.com/synthetichealth/synthea/files/15476979/atrial_fibrillation.json)
[keep_atrial_fibrillation.json](https://github.com/synthetichealth/synthea/files/15476981/keep_atrial_fibrillation.json)
[Seymour882_Yost751_6d8278e6-8fe3-8dbd-6c0f-b6e72b00ec17.json](https://github.com/synthetichealth/synthea/files/15480214/Seymour882_Yost751_6d8278e6-8fe3-8dbd-6c0f-b6e72b00ec17.json)

### What happened?

Trying to generate only One Patient with FHIR data:

1. Created custom atrial fibrillation module (attached above)
2. Copied it to src/main/resources/modules
3. Commented out below modules in Module.java
`    //retVal.put("Lifecycle", new ModuleSupplier(new LifecycleModule()));
    //retVal.put("Health Insurance", new ModuleSupplier(new HealthInsuranceModule()));
    //retVal.put("Cardiovascular Disease", new ModuleSupplier(new CardiovascularDiseaseModule()));
    //retVal.put("Quality Of Life", new ModuleSupplier(new QualityOfLifeModule()));
    //retVal.put("Weight Loss", new ModuleSupplier(new WeightLossModule()));
    //retVal.put("COVID-19 Immunization Module", new ModuleSupplier(new C19ImmunizationModule()));`
4. Created keep_module file (attached above) and copied it to src/main/resources/keep_modules. removed all other files in that directory
5. Ran command
`./run_synthea -g M -a 60-60 -m *fibrillation* -p 1 -k src/main/resources/keep_modules/keep_atrial_fibrillation.json `
7. Procedure resources requested in the module are never created.

### Environment

```markdown
- OS:
- Java:
```

**Comment by jawalonoski** [comment]
We do not debug or address issues that use the `-m` feature, so I am going to close this issue. https://github.com/synthetichealth/synthea/wiki/The--M-Feature

However, the patient you attached has Atrial Fibrillation (starting on line 211):

```json
    "resource": {
      "resourceType": "Condition",
      "id": "6f551688-67a6-e0d5-3800-0482116d2f41",
      "meta": {
        "profile": [ "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-encounter-diagnosis" ]
      },
      "clinicalStatus": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "active"
        } ]
      },
      "verificationStatus": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed"
        } ]
      },
      "category": [ {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        } ]
      } ],
      "code": {
        "coding": [ {
          "system": "http://snomed.info/sct",
          "code": "49436004",
          "display": "Atrial fibrillation (disorder)"
        } ],
        "text": "Atrial fibrillation (disorder)"
      },
      "subject": {
        "reference": "urn:uuid:6d8278e6-8fe3-8dbd-6c0f-b6e72b00ec17"
      },
      "encounter": {
        "reference": "urn:uuid:7798d3b0-9061-9119-639c-f8327a072ab2"
      },
      "onsetDateTime": "1985-11-16T12:42:03-08:00",
      "recordedDate": "1985-11-16T12:42:03-08:00"
    }
```

As you note, the patient does not have any procedures in that encounter, because the Encounter occurred in 1985, which is well outside the bounds of the default `exporter.years_of_history` value (default is 10 years). Some resources are exempt from the filter under certain conditions, for example, active conditions. See https://github.com/synthetichealth/synthea/issues/1064 and https://github.com/synthetichealth/synthea/blob/e6534b629952a22655c10f57989ee2ec513ca06b/src/main/resources/synthea.properties#L8-L10

**Comment by schowdary55** [comment]
@jawalonoski Thanks for clarification. If I use `exporter.years_of_history = 10 `, then I get some history (Encounter, Immunization, DiagnosticReport, Document reference, Claim, ExplanationOfBenefit resources)  automatically generated every year, which I don't want. How to avoid them?

**Comment by jawalonoski** [comment]
> @jawalonoski Thanks for clarification. If I use `exporter.years_of_history = 10 `, then I get some history (Encounter, Immunization, DiagnosticReport, Document reference, Claim, ExplanationOfBenefit resources) automatically generated every year, which I don't want. How to avoid them?

You can't avoid it. Post process the data.
