### ISSUE TITLE
target_encounter dropped from Wiki States but still appears in modules

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#147]
The following states still have target_encounter references in the modules but not in the wiki:

MedicationOrder
Procedure
CarePlanStart
Observation

From the Encounter Documentation:

"During a single time step, if an Encounter state is processed it becomes the current_encounter. This encounter will be used as the encounter for all subsequent clinical states, for example a Procedure or MedicationOrder. When an EncounterEnd state is reached, the current_encounter ends and remains nil until another Encounter is processed. If Synthea cannot identify a current_encounter for a clinical state an error is raised."

I removed the target_encounter fields from the above states in order to implement the new encounter policy but I'm getting a lot of errors due (I believe) to forward encounter references still in the modules.

**Comment by cjduffett** [comment]
To maintain backwards compatibility our GMF parser simply ignores any "target_encounter" fields, the same way we ignore "remarks". This was a temporary solution until we could find the time to actually go back and update all of the existing modules. Perhaps you could do the same?

**Comment by jeffeastman** [comment]
Digging deeper, they all seem to be "Wellness Encounters". I will code to avoid the exceptions and handle them correctly in this case.

I completely understand the backwards compatibility approach.

**Comment by jeffeastman** [comment]
Here are the target_encounter references that need to be coded around. Only some are Wellness... I'll have to think about this some more...

Record_Diastolic_BP [Observation] target_encounter = Wellness_Encounter
Diagnosis_MMSE_Score [Observation] target_encounter = DiagnosisEncounter
Eczema_Obs_Upper_Extremities [Observation] target_encounter = null
Record_HDL [Observation] target_encounter = Wellness_Encounter
FirstPrescription1 [MedicationOrder] target_encounter = DiagnosisEncounter
Egg_Test_Negative [Observation] target_encounter = null
Record_BMI [Observation] target_encounter = Wellness_Encounter
Grass_Test_Negative [Observation] target_encounter = null
Eczema_Obs_Trunk [Observation] target_encounter = null
Milk_Test_Negative [Observation] target_encounter = null
Record_Triglycerides [Observation] target_encounter = Wellness_Encounter
Mite_Test_Negative [Observation] target_encounter = null
Routine_Colonoscopy_Procedure [Procedure] target_encounter = Routine_Colonoscopy_Encounter
Soy_Test_Negative [Observation] target_encounter = null
Shellfish_Test_Negative [Observation] target_encounter = null
Latex_Test_Negative [Observation] target_encounter = null
Record_Weight [Observation] target_encounter = Wellness_Encounter
Record_Cholesterol [Observation] target_encounter = Wellness_Encounter
Record_LDL [Observation] target_encounter = Wellness_Encounter
Dementia_CarePlan [CarePlanStart] target_encounter = DiagnosisEncounter
Nut_Test_Negative [Observation] target_encounter = null
Wheat_Test_Negative [Observation] target_encounter = null
Eczema_Obs_Head_And_Neck [Observation] target_encounter = null
Eczema_Obs_Lower_Extremities [Observation] target_encounter = null
Med_Rec [Procedure] target_encounter = Wellness_Encounter
Peanut_Test_Negative [Observation] target_encounter = null
Record_Height [Observation] target_encounter = Wellness_Encounter
Record_Systolic_BP [Observation] target_encounter = Wellness_Encounter
Mold_Test_Negative [Observation] target_encounter = null
Dander_Test_Negative [Observation] target_encounter = null
Directed_Use_Prescription3 [MedicationOrder] target_encounter = Enter_Directed_Use_Encounter3
Bee_Test_Negative [Observation] target_encounter = null
Fish_Test_Negative [Observation] target_encounter = null
Tree_Test_Negative [Observation] target_encounter = null

**Comment by cjduffett** [comment]
At a glance, a lot of those states occur in submodules. Does your notion of a `current_encounter` get maintained across submodules?

**Comment by jeffeastman** [comment]
Seems like it should, it's a property of the module. Guess I'll have to check that out. Thanks!

**Comment by jeffeastman** [comment]
Yup, that was my problem. I'm handling the target_encounters as before when they are present, so this resolves the Wellness_Encounter references. And I was not passing the parent module context into the submodule so correcting that makes it all work again.

**Comment by cjduffett** [comment]
Glad to hear it's fixed!
