### ISSUE TITLE
Not able to generate condition specific module

### ISSUE THREAD

**Issue by surajpujari818** [synthetichealth/synthea#1484]
### What happened?

A bug happened!

I am trying to generate ASTHMA module from built in module.
But it is not generating the allergy,device,supplies,imaging studies.

![Screenshot 2024-07-09 202057](https://github.com/synthetichealth/synthea/assets/175134408/8876d8e3-e8b3-4bad-a520-2d903c5fd544)

![Screenshot 2024-07-09 201917](https://github.com/synthetichealth/synthea/assets/175134408/6ba5acee-ffeb-4c72-80cd-974955a28033)

### Environment

```markdown
- Java: java JDK
```

**Comment by jawalonoski** [comment]
1. We don't responding to issues or requests that use the `-m` feature. See https://github.com/synthetichealth/synthea/wiki/The--M-Feature
2. A quick review of the [asthma module](https://synthetichealth.github.io/module-builder/#asthma) clearly shows that it does not directly include any allergies, devices, supplies, or imaging studies... so you should not expect to see any.
