### ISSUE TITLE
output/prevalences.csv does not write if output dir changed

### ISSUE THREAD

**Issue by andrequina** [synthetichealth/synthea#160]
Outputting Metabolic Syndrome Results to output/prevalences.csv
rake aborted!
Errno::ENOENT: No such file or directory - output/prevalences.csv
/Users/aquina/data/workspaces/shr/synthea/lib/world/sequential.rb:108:in `run'
lib/tasks/tasks.rake:58:in `block in (root)'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/rake-12.0.0/exe/rake:27:in `<top>'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:1:in `(root)'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `block in start'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/gems/bundler-1.13.1/exe/bundle:34:in `<top>'
/Users/aquina/.rvm/gems/jruby-9.1.2.0/bin/bundle:22:in `<top>'

**Comment by jawalonoski** [comment]
Did you delete the output folder?
