### ISSUE TITLE
No Statins for Diabetes

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#170]
2 Statin medications are exported in `concepts.csv`:

RxNorm, 312961, Simvastatin 20 MG Oral Tablet
RxNorm, 259255, Atorvastatin 80 MG Oral Tablet

But are never prescribed in any of the modules. I'm guessing these were forgotten when diabetes was ported to GMF. Nonetheless, I'm surprised that these medications aren't prescribed anywhere for high cholesterol.

**Comment by jawalonoski** [comment]
Cardiovascular module?

**Comment by cjduffett** [comment]
If it's prescribed in the Cardiovascular module then why don't any patients have prescriptions for either? Not a single patient out of 1.3M.

**Comment by dehall** [comment]
These should both be prescribed in the cardiovascular module; simvastatin as a treatment for coronary heart disease and atorvastatin as an emergency treatment for heart attack:
https://github.com/synthetichealth/synthea/blob/master/lib/modules/cardiovascular_disease.rb#L404
https://github.com/synthetichealth/synthea/blob/master/lib/modules/cardiovascular_disease.rb#L484

In our module, amlodipine is prescribed in the same situation as simvastatin but was not available until a few years later, and clopidogrel is prescribed in the same situation as atorvastatin but was not available until a few years later - if amlodipine and clopidogrel are prescribed anywhere in those 1.3M patients but the statins aren't then something is up.

**Comment by cjduffett** [comment]
It seems that the only medication of the 4 mentioned that's actually in the data is Clopidogrel (309362). There are hundreds of prescriptions for it, but none for the others.
