### ISSUE TITLE
Target Encounter Futures?

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#172]
Jay wrote on another thread:

"We started transitioning to a scheme where the current encounter was always in context, which eliminated the need for target_encounter in most cases. You can still set these attributes, but their use is deprecated, which is why references have been removed from the wiki."

I tried removing the target_encounters from Observation, Procedure, MedicationOrder and CarePlanStart states. A quick run yielded immediate failures. Surveying the existing modules indicates they are still in wide use.

As long as their use is still widespread and is still required, it seems premature to remove them from the documentation.

Jeff

Wellness Encounters.Record_Height [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Weight [Observation] -> Wellness_Encounter
Wellness Encounters.Record_BMI [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Systolic_BP [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Diastolic_BP [Observation] -> Wellness_Encounter
Wellness Encounters.Record_HA1C [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Glucose [Observation] -> Wellness_Encounter
Wellness Encounters.Record_UreaNitrogen [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Creatinine [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Calcium [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Sodium [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Potassium [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Chloride [Observation] -> Wellness_Encounter
Wellness Encounters.Record_CO2 [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Cholesterol [Observation] -> Wellness_Encounter
Wellness Encounters.Record_Triglycerides [Observation] -> Wellness_Encounter
Wellness Encounters.Record_LDL [Observation] -> Wellness_Encounter
Wellness Encounters.Record_HDL [Observation] -> Wellness_Encounter
Wellness Encounters.Record_ACR [Observation] -> Wellness_Encounter
Wellness Encounters.Record_EGFR [Observation] -> Wellness_Encounter

Allergy Immunotherapy.Immunotherapy_Procedure [Procedure] -> Immunotherapy_Treatment
Appendicitis.Appendectomy [Procedure] -> Appendectomy_Encounter
Asthma.Asthma_Screening [Procedure] -> Asthma_Diagnosis
Attention Deficit Disorder.Behavior_Treatment_Procedure [Procedure] -> Behavior_Treatment_Encounter
Colorectal Cancer.Routine_Colonoscopy_Procedure [Procedure] -> Routine_Colonoscopy_Encounter
Colorectal Cancer.Fecal_Test [Procedure] -> Routine_Colonoscopy_Encounter
Colorectal Cancer.Adenoma_Removal [Procedure] -> Routine_Colonoscopy_Encounter
Colorectal Cancer.Adenoma_Biopsy [Procedure] -> Routine_Colonoscopy_Encounter
Colorectal Cancer.Followup_Colonoscopy_Procedure [Procedure] -> Followup_Colonoscopy_Encounter
Colorectal Cancer.Recurrent_Adenoma_Removal [Procedure] -> Followup_Colonoscopy_Encounter
Colorectal Cancer.Diagnostic_Colonoscopy_Procedure [Procedure] -> Diagnostic_Colonoscopy_Encounter
Colorectal Cancer.Partial_Colectomy_Procedure [Procedure] -> Partial_Colectomy_Encounter
Colorectal Cancer.Diverting_Colostomy_Procedure [Procedure] -> Diverting_Colostomy_Encounter
Colorectal Cancer.Chemotherapy_Procedure [Procedure] -> Chemotherapy_Encounter
COPD.Initial_FEV_Test [Procedure] -> DiagnosisEncounter
COPD.Followup_FEV_Test [Procedure] -> COPD_Followup_Encounter
COPD.Lung_Transplant [Procedure] -> Surgery_Encounter
COPD.Lung_Volume_Reduction [Procedure] -> Surgery_Encounter
COPD.Pulmonary_Rehab [Procedure] -> COPD_Followup_Encounter
Lung Cancer.Chest X-Ray [Procedure] -> Diagnosis Encounter I
Lung Cancer.Chest CT Scan [Procedure] -> Diagnosis Encounter II
Lung Cancer.Sputum Cytology (Phelgm) [Procedure] -> Diagnosis Encounter III
Lung Cancer.Thoracentesis (Fluid) [Procedure] -> Diagnosis Encounter III
Lung Cancer.Needle Biopsy (Cells) [Procedure] -> Diagnosis Encounter III
Lung Cancer.Bronchoscopy (Tube) [Procedure] -> Diagnosis Encounter III
Lung Cancer.MRI Brain [Procedure] -> Diagnosis Encounter IV
Lung Cancer.SCLC Radiation [Procedure] -> SCLC Treatment Encounter
Lung Cancer.NSCLC Radiation [Procedure] -> NSCLC Treatment Encounter
Medication Reconciliation.Med_Rec [Procedure] -> Wellness_Encounter
Opioid Addiction.Enter_Directed_Use_Procedure1 [Procedure] -> Enter_Directed_Use_Encounter1
Pregnancy.Pregnancy_Test [Procedure] -> Prenatal_Initial_Visit
Pregnancy.Induction [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Epidural [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Augmentation [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Episiotomy [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Assisted_Delivery [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Spontaneous_Breech [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Normal_Birth_Procedure [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Premature_Birth_Procedure [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Induced_Birth_Procedure [Procedure] -> Hospital_Admission_For_Birth
Pregnancy.Ectopic_Pregnancy_Surgery_Procedure [Procedure] -> Ectopic_Pregnancy_Surgery_Encounter
Pregnancy.Induced_Abortion_Procedure [Procedure] -> Induced_Abortion_Encounter
Self Harm.Psychiatric_Evaluation [Procedure] -> ED_Visit_For_Attempted_Suicide
Self Harm.Short_Hospital_Stay [Procedure] -> ED_Visit_For_Attempted_Suicide
Self Harm.Followup_Psychiatric_Evaluation [Procedure] -> Attempted_Suicide_Followup
Self Harm.Autopsy_Examination [Procedure] -> Autopsy_Encounter
Sinusitis.Sinus_Surgery [Procedure] -> Chronic_Sinusitis_Followup
Sore Throat.Throat_Culture [Procedure] -> Doctor_Visit
Total Joint Replacement.Knee_Replacement_Procedure [Procedure] -> Joint_Replacement_Encounter
Total Joint Replacement.Hip_Replacement_Procedure [Procedure] -> Joint_Replacement_Encounter

Asthma.Prescribe_Maintenance_Inhaler [MedicationOrder] -> Asthma_Diagnosis
Asthma.Prescribe_Emergency_Inhaler [MedicationOrder] -> Asthma_Diagnosis
Attention Deficit Disorder.Ritalin [MedicationOrder] -> ADHD_Diagnosis
Attention Deficit Disorder.Strattera [MedicationOrder] -> ADHD_Diagnosis
Colorectal Cancer.Chemotherapy_Drugs_I [MedicationOrder] -> Chemotherapy_Encounter
Colorectal Cancer.Chemotherapy_Drugs_II [MedicationOrder] -> Chemotherapy_Encounter
COPD.Prescribe_Medication [MedicationOrder] -> COPD_Followup_Encounter
Dementia.FirstPrescription1 [MedicationOrder] -> DiagnosisEncounter
Dementia.FirstPrescription2 [MedicationOrder] -> DiagnosisEncounter
Dementia.FirstPrescription3 [MedicationOrder] -> DiagnosisEncounter
Dementia.SecondPrescription1 [MedicationOrder] -> ModeratelySevere_Encounter
Dementia.SecondPrescription2 [MedicationOrder] -> ModeratelySevere_Encounter
Dementia.SecondPrescription3 [MedicationOrder] -> ModeratelySevere_Encounter
Fibromyalgia.Strong_NSAID [MedicationOrder] -> Fibromyalgia_Diagnosis
Fibromyalgia.Prescribe_Lyrica [MedicationOrder] -> Fibromyalgia_Episode
Fibromyalgia.Prescribe_Cymbalta [MedicationOrder] -> Fibromyalgia_Episode
Fibromyalgia.Prescribe_Savella [MedicationOrder] -> Fibromyalgia_Episode
Fibromyalgia.Prescribe_Opioid [MedicationOrder] -> Fibromyalgia_Episode
Gout.Strong_NSAID [MedicationOrder] -> Gout_Diagnosis
Gout.Colchicine [MedicationOrder] -> Gout_Diagnosis
Gout.Uric_Acid_Reducer [MedicationOrder] -> Gout_Diagnosis
Lung Cancer.SCLC Chemotheraphy I [MedicationOrder] -> SCLC Treatment Encounter
Lung Cancer.SCLC Chemotheraphy II [MedicationOrder] -> SCLC Treatment Encounter
Lung Cancer.NSCLC Chemotheraphy I [MedicationOrder] -> NSCLC Treatment Encounter
Lung Cancer.NSCLC Chemotheraphy II [MedicationOrder] -> NSCLC Treatment Encounter
Lupus.Lupus_Nonopioid_Pain_Medication [MedicationOrder] -> Lupus_Diagnosis
Lupus.Corticosteroid [MedicationOrder] -> Lupus_Diagnosis
Lupus.Immune_Suppressant [MedicationOrder] -> Lupus_Flareup
Lupus.Flareup_Corticosteroid [MedicationOrder] -> Lupus_Flareup
Opioid Addiction.Directed_Use_Prescription1 [MedicationOrder] -> Enter_Directed_Use_Encounter1
Opioid Addiction.Directed_Use_Prescription2 [MedicationOrder] -> Enter_Directed_Use_Encounter2
Opioid Addiction.Directed_Use_Prescription3 [MedicationOrder] -> Enter_Directed_Use_Encounter3
Osteoarthritis.OA_Pain_Medication [MedicationOrder] -> OA_Diagnosis
Rheumatoid Arthritis.RA_Nonopioid_Pain_Medication [MedicationOrder] -> RA_Diagnosis
Rheumatoid Arthritis.DMARD [MedicationOrder] -> RA_Diagnosis
Rheumatoid Arthritis.Corticosteroid [MedicationOrder] -> RA_Diagnosis
Sinusitis.Prescribe_Antibiotic [MedicationOrder] -> Doctor_Visit
Sore Throat.Prescribe_Antibiotics_Child [MedicationOrder] -> Doctor_Visit
Sore Throat.Prescribe_Antibiotics_Adult [MedicationOrder] -> Doctor_Visit
Urinary Tract Infections.Prescribe_UTI_Antibiotic [MedicationOrder] -> UTI_Diagnosis
Urinary Tract Infections.Prescribe_OTC_Painkiller_For_UTIs [MedicationOrder] -> UTI_Diagnosis
Urinary Tract Infections.Prescribe_Second_Round_Of_Antibiotics [MedicationOrder] -> Followup_Encounter

Allergy Immunotherapy.Immunotherapy_CarePlan [CarePlanStart] -> Immunotherapy_Consultation
Asthma.Smoker_CarePlan [CarePlanStart] -> Asthma_Diagnosis
Asthma.Nonsmoker_CarePlan [CarePlanStart] -> Asthma_Diagnosis
Attention Deficit Disorder.ADHD_CarePlan [CarePlanStart] -> ADHD_Diagnosis
Colorectal Cancer.Colorectal_Cancer_CarePlan [CarePlanStart] -> Oncologist_Encounter
Colorectal Cancer.Partial_Colectomy_CarePlan [CarePlanStart] -> Partial_Colectomy_Encounter
Colorectal Cancer.Diverting_Colostomy_CarePlan [CarePlanStart] -> Diverting_Colostomy_Encounter
COPD.Nonsmoker_CarePlan [CarePlanStart] -> DiagnosisEncounter
COPD.Smoker_CarePlan [CarePlanStart] -> DiagnosisEncounter
Dementia.Dementia_CarePlan [CarePlanStart] -> DiagnosisEncounter
Fibromyalgia.Fibromyalgia_CarePlan [CarePlanStart] -> Fibromyalgia_Diagnosis
Gout.Gout_CarePlan [CarePlanStart] -> Gout_Diagnosis
Lung Cancer.Lung_Cancer_CarePlan [CarePlanStart] -> Diagnosis Encounter IV
Lupus.Lupus_CarePlan [CarePlanStart] -> Lupus_Diagnosis
Opioid Addiction.Opioid_Addiction_CarePlan [CarePlanStart] -> Addiction_Overdose_Encounter
Osteoarthritis.OA_CarePlan [CarePlanStart] -> OA_Diagnosis
Pregnancy.Pregnancy_CarePlan [CarePlanStart] -> Prenatal_Initial_Visit
Rheumatoid Arthritis.RA_CarePlan [CarePlanStart] -> RA_Diagnosis
Self Harm.Suicide_CarePlan [CarePlanStart] -> Attempted_Suicide_Followup
Total Joint Replacement.Post_Op_CarePlan [CarePlanStart] -> Joint_Replacement_Encounter
Urinary Tract Infections.UTI_CarePlan [CarePlanStart] -> UTI_Diagnosis

**Comment by dehall** [comment]
As Jay mentioned, the `target_encounter` field is deprecated and can be removed safely. (the exception is `ConditionOnset` states where the target_encounter is in the future) The way we've implemented this is to track the current encounter within the Context running the module. When the running module hits an `Encounter` state, it maintains a reference to that state as the current encounter. Any subsequent clinical states such as `Procedure`, `Observation`, `MedicationOrder`, etc, occur during that encounter. Once the module hits an `EncounterEnd` state that current encounter is cleared out.  Every clinical state within our modules occurs following an Encounter so there should always be sufficient information to make the `target_encounter` field safe to remove.

**Comment by jeffeastman** [comment]
AllergyOnset is in the wiki too. I tried removing the target_encounters from Observation, Procedure, MedicationOrder and CarePlanStart states but ran into problems. I'll try again.

**Comment by jeffeastman** [comment]
Closing this because I've resolved my internal issues and ignoring the target_encounters is no longer a problem,
