### ISSUE TITLE
Timing Issue in allergies/severe_allergic_reaction.json

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#175]
"The MedicationOrder state type indicates a point in the module where a medication should be prescribed. The MedicationOrder state must come after an Encounter state in the module, but **must have the same start time as that Encounter**; otherwise it will not be recorded in the patient's record. See the Encounter section above for more details."

However, in allergies/severe_allergic_reaction.json there is a 2-6 hr Observation_Period separating the Mild_Steroid medication order from its ED_Visit_For_Allergic_Reaction. This causes an exception every time it occurs, since the order state does not have the same start time as the encounter.

This can be resolved by moving the order to precede the delay.

**Comment by jeffeastman** [comment]
This sequence actually has an Rx with a duration on the MedicationOrder, but the mild steroid order is cancelled within the same submodule. With the duration, the MedicationEnd seems unnecessary.

Timing the order out based upon its duration seems a better solution, though I don't do that now.

**Comment by dehall** [comment]
Thanks for catching this, the wiki is out of date. The start time of clinical states such as MedicationOrder and Procedure no longer have to have the same start time as the Encounter. (In general when there is a discrepancy between the wiki and the code, the code should be assumed to be the correct version. I'll go over the wiki this morning to double check everything.)

For context - one piece of feedback we received regarding realism was the fact that all Encounters had the same duration (15 minutes) regardless of what the encounter entailed. But obviously more complex procedures take longer, so to represent that, we added the `EncounterEnd` state and the `duration` field on `Procedure` states. Now an Encounter may contain many procedures, observations, delays, etc, which don't all start at the exact same time as the start of the encounter. 



Re: the MedicationOrder duration, you're right that given a specific duration the MedicationEnd probably isn't necessary. There are still valid uses for the MedicationEnd state in general, but if there are places we can remove it without losing anything, I think that's a good thing. I'll add an item to review that.

**Comment by jeffeastman** [comment]
Thanks for the update. Does this apply to the other states (CarePlanStart, DiagnosticReport,MultiObservation, Observation) too? I update the Encounter's endDateTime to the time of the last event that is added to it, or to the EncounterEnd's time if there is one (Wellness encounters don't seem to)

**Comment by dehall** [comment]
Yes this applies to the other state types as well. 

Wellness encounters are trickier because many different modules could process states for the same wellness encounter, so it's not possible for a single module to define when that wellness encounter ends. We've punted on this for now so the wellness encounter is just assumed to take 1 hour.  https://github.com/synthetichealth/synthea/blob/master/lib/modules/encounters.rb#L130

**Comment by jeffeastman** [comment]
My approach of updating each encounter's end time whenever an event is added to it works for wellness encounters too. That might work for Synthea too.

I tend to rely upon the Wiki definitions as tracking all of the individual Ruby commits and reverse engineering their definitions doesn't work for me. Its probably a good sanity check of the wiki when I do notice issues there.

BTW, Procedure delays are also not documented in the wiki.

**Comment by cjduffett** [comment]
I added procedure duration to the docs.

**Comment by jeffeastman** [comment]
Closing this issue as its been resolved
