### ISSUE TITLE
Appendicitis Encounter Conflict

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#187]
This module has two encounters that occur in the same iteration in this sequence:

1. Appendicitis_Encounter (an ED visit)
1. History_of_Appendectomy (Condition)
1. Appendectomy_Encounter (an Inpatient encounter)
...
1. End_Appendectomy_Encounter

In my implementation I close the first one when the second occurs. This seems reasonable but wouldn't a better solution be to explicitly close it prior to the condition?

Does Synthea do the same thing?

**Comment by dehall** [comment]
Yes, Synthea does the same thing, and if a new Encounter starts with an existing one still open, it automatically closes the first. 

In general our approach with EncounterEnds has been to omit them when not necessary (such as with wellness encounters) but in this case we should consider an EncounterEnd with an appropriate discharge code to indicate transfer to inpatient care.

**Comment by jawalonoski** [comment]
The general question was answered (a new encounter implicitly closes the previous encounter) and the appendicitis discharge code was changed over 9 months ago.
