### ISSUE TITLE
Opioid Addiction Encounter Issue

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#188]
The opioid addiction module has the following sequence of states:

1. Enter_Directed_Use_Condition3
2. Enter_Directed_Use_Encounter3 (wellness = true)
3. Directed_Use_Prescription3
4. End_Directed_Use_Encounter

This has the effect of ending the wellness encounter prematurely, since other modules that follow (esp. Wellness) need to add additional events. Maybe this shouldn't be a wellness?

**Comment by dehall** [comment]
In our impl the EncounterEnd for a wellness encounter doesn't actually set the end of the encounter: https://github.com/synthetichealth/synthea/blob/master/lib/generic/states.rb#L311 

That said, there's not really a good reason for this encounter to be a wellness encounter anyway. It's an easy change to make this a regular encounter like the other 2 encounters that lead to directed use.
