### ISSUE TITLE
Generated Demographics Age Calculation Bug

### ISSUE THREAD

**Issue by lxbrown** [synthetichealth/synthea#192]
While generating one person at a time, I noticed the age in Generated Demographics is different than the age listed for the individual.

[2017-04-27 10:23:26] 1: Strosin454, Gus267. Black African. 21 y/o M 125 lbs. --
Generated Demographics:
{
  "age": {
    "20": 1
  },

I'm quite new to Synthea, so is there an intentional rounding difference, or is this, in fact, a bug?

**Comment by lxbrown** [comment]
My apologies, I didn't realize it was sorted by increments of 10.

**Comment by jawalonoski** [comment]
No problem. Thanks for the initiative in submitting an issue!
