### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by MatthewVita** [synthetichealth/synthea#193]
Dear Maintainers,

My name is Matthew Vita, a programmer in the healthcare industry. I am trying to help build up the high impact "List of open-source health software" Wikipedia page (https://en.wikipedia.org/wiki/List_of_open-source_health_software) and would love to add your software to the list. However, it appears that your project does not have a page on Wikipedia so I ask you to consider the following:

1) Adding a nice article for your project (see the GNU Health article (https://en.wikipedia.org/wiki/GNU_Health) for a really good example and Ginkgo CADx (https://en.wikipedia.org/wiki/Ginkgo_CADx) for a lightweight, but acceptable example).
2) Adding said article to "List of open-source health software" Wikipedia page (https://en.wikipedia.org/wiki/List_of_open-source_health_software).

(If you’re already on Wikipedia, my search-fu wasn’t working when I looked you up so please consider doing only step 2 above)

Thanks,
Matthew

**Comment by MatthewVita** [comment]
Dear Maintainers,

I just wanted to follow up with a few words in regards to Conflict of Interest (COI). As you can imagine, I have been reaching out to all kinds of mature, reputable, and active open source healthcare projects to help build up this Wikipedia list. However, some project members have (rightly) reached out to me with concerns about COI, so I wanted to clear this up as best as I can. I should first note that my role in this process is of a neutral party that is solely acting in the interests of Wikipedia readers that wish to learn about open source healthcare solutions.

Wikipedia defines COI as "contributing to Wikipedia about yourself, family, friends, clients, employers, or your financial and other relationships. Any external relationship can trigger a conflict of interest." They also go on to say that organizations writing about themselves is a COI.

If you meet one or more of those criteria, I suggest reaching out to a neutral party in your project's community to put together the article. If you do not meet any of those criteria, I suggest putting together an article with material that places the interest of the encyclopedia and its reader above all else.

Assuming you don't have a COI, I encourage you to do as other open source healthcare projects have done by creating a neutral article about the project with the help of the community (users, developers, and subject matter experts) as well as reliable references.

For whatever it's worth, my personal opinion is that if you don't have a COI, it is rather easy to write up an article talking about the software's features, history, usage, and milestones all while being neutral.

Thanks,
Matthew Vita

**Comment by kindofluke** [comment]
I can write the article. I have no conflicts.

**Comment by kindofluke** [comment]
@jawalonoski Could you upload one of the disease maps to the wikimedia commons? That way we can use it in the article? 

Maybe this one 
![ear infections](https://user-images.githubusercontent.com/20745904/32395873-6789a6fa-c0b9-11e7-911e-73066d2a8e66.png)

**Comment by jawalonoski** [comment]
@kindofluke sure thing. thanks!

**Comment by kindofluke** [comment]
@MatthewVita  I have written a draft of the article. [https://en.wikipedia.org/wiki/Draft:Synthea](https://en.wikipedia.org/wiki/Draft:Synthea)

Feel free to give me some feedback but I think its better than nothing for right now. I will submit it for review on Wednesday and may do some edits over the weekend.

**Comment by jawalonoski** [comment]
To use the file in a wiki, copy this text into a page:
```
[[File:Synthea generic module diagram.png|thumb|synthea generic module diagram]]
```
To link to it in HTML, copy this URL:
```
https://commons.wikimedia.org/wiki/File:Synthea_generic_module_diagram.png
```

**Comment by MatthewVita** [comment]
Awesome. Will review it tomorrow!

**Comment by MatthewVita** [comment]
@kindofluke Amazing work for the first draft. We'll be ready to ship this thing in no time!

*Here are the changes I made:*

- Added link to MITRE (https://en.wikipedia.org/wiki/Mitre_Corporation)
- Made architecture its own section (does not make sense to place it under the background)
- Use number bullets
- electrionic -> electronic
- “ -> ", ” -> "
- "with provider" -> "with a healthcare provider"
- "health care" -> "healthcare"
- "and even test results" ->  "and test results"
- Current Usage -> Usage
- Project Background -> History
- Removed "picture at right"

*Here are some additional items for you to explore/incorporate:*

- Add a section to the top right like https://en.wikipedia.org/wiki/GNU_Health (picture is a good idea, if you can)
- Once the top-right section is added, you can add a link to the repository. Therefore, you'll be able to remove "As an open source project, the source code is available on github"
- Add a "Project milestones" section
- You can't say "which are the leading data standards in health care applications." without references... please look for a reference
- You can't say "Synthea is in active use by a number of healthcare organizations to support their research and software development." without references
- The Architecture section reads a tad awkwardly... can you take another pass at it (it's good for a first draft though... just keep it up. Let me know if you want to hop on a Google Hangouts/Whatsapp call and we can write it together)
- I'm a tad worried that "To answer this concern" will not be well received because it almost sounds like an ad. Not sure if I'm thinking too much of it though... please put some thought into this.
- Picture should be aligned with the Architecture section (floating awkwardly)

**Comment by kindofluke** [comment]
Ok thanks will work on it tomorrow.

**Comment by MatthewVita** [comment]
Keep up the great work!

**Comment by kindofluke** [comment]
- [x] Add a section to the top right like https://en.wikipedia.org/wiki/GNU_Health (picture is a good idea, if you can)
- [x ] Once the top-right section is added, you can add a link to the repository. Therefore, you'll be able to remove "As an open source project, the source code is available on github"
- [x] You can't say "which are the leading data standards in health care applications." without references... please look for a reference
- [x ] You can't say "Synthea is in active use by a number of healthcare organizations to support their research and software development." without references
- [ ] The Architecture section reads a tad awkwardly... can you take another pass at it (it's good for a first draft though... just keep it up. Let me know if you want to hop on a Google Hangouts/Whatsapp call and we can write it together)
- [x] I'm a tad worried that "To answer this concern" will not be well received because it almost sounds like an ad. Not sure if I'm thinking too much of it though... please put some thought into this.
- [x ] Picture should be aligned with the Architecture section (floating awkwardly) *almost not quite*.

This what I got done tonight. I did make some changes in the architecture section that made it a little better but I see what you mean.

**Comment by MatthewVita** [comment]
Looking good, @kindofluke !

**Comment by kindofluke** [comment]
I submitted it for review. We will see how it goes.

**Comment by jawalonoski** [comment]
Thanks for the contribution @kindofluke!

**Comment by MatthewVita** [comment]
(Don't be surprised if the review process takes month 😃  )

**Comment by kindofluke** [comment]
@mattewvita our page was published on the ninth which was great. It was then quickly marked for deletion which is not. 

If everyone could hop onto the discussion page and help out with that it would be great.

**Comment by jawalonoski** [comment]
I took down the "help wanted" sign.

I think it would be a conflict of interest for me to defend the article.

The criticism was:
> Obvious commissioned work for non-notable software

**Comment by MatthewVita** [comment]
@kindofluke Just left a comment there. I am thinking we just need a few more references and it will be good to go.

The article is not an ad/spam, not sure how one could conclude that really.

I do agree after reading the feedback that the article it would benefit from a few more references back in the draft form. Hope we can get to that point in the spirit of being practical and helpful to potential readers.

**Comment by dehall** [comment]
Unfortunately the page was deleted this morning. As with Jay I assumed it would be a conflict of interest if I commented. @MatthewVita @kindofluke thank you both for putting the page together, even if it didn't stick. Did either of you save the content? If not it's still in the Google cache as of right now, or there are administrators who may be able to retrieve it: https://en.wikipedia.org/wiki/Category:Wikipedia_administrators_willing_to_provide_copies_of_deleted_articles

**Comment by kindofluke** [comment]
We actually won the argument about the conflict of interest but failed on the search for “notability” 

The consensus was "Some good medical journal articles reviewing it might have cemented it”

so there we go. 

I do have the content but we are going to need some sources for the editors to verify. 

Luke

**Comment by MatthewVita** [comment]
Sigh. Looks like we'll have to let things bake a bit. Also would be nice to have more sources. I am hopeful this project will continue to gain attention!
