### ISSUE TITLE
Upgrade to FHIR DSTU3 3.0.0

### ISSUE THREAD

**Issue by Erstwild** [synthetichealth/synthea#194]
Will this be upgraded to latest FHIR spec? :
https://www.hl7.org/fhir/directory.html

**Comment by jawalonoski** [comment]
Yes. We're working on it. We're upgrading to `3.0.1` on the `fhir_3` branch which hasn't been merged yet.

**Comment by Erstwild** [comment]
@jawalonoski That's great.  When do you think it will be ready to be merged?  Great project.

**Comment by wdaehn** [comment]
+1 
No pressure but I am desperately waiting for that as well. ;-)

**Comment by jawalonoski** [comment]
We have a branch with STU3... I just need to review it and merge it into master. Probably this week.
