### ISSUE TITLE
Last names can still have Hash when append_hash_to_person_names is false

### ISSUE THREAD

**Issue by gteichrow** [synthetichealth/synthea#196]
In lifecycle.rb, there is a section of the code dealing with married women where the last_name was reset but the reset logic did not check the append_hash_to_person_names flag to see if the hash should be appended.  

I have a fix in my fork and will commit, once I figure out git, lol.  I'm an svn fart and I think I have it, but want to get thru the pull request, etc.

**Comment by jawalonoski** [comment]
Great. Looking forward to the pull request!

**Comment by gteichrow** [comment]
Shazam, baby's first pull-request.  w00t.

**Comment by jawalonoski** [comment]
Thanks for the contribution!
