### ISSUE TITLE
Update ruby.

### ISSUE THREAD

**Issue by preston** [synthetichealth/synthea#199]
Ruby 2.1.0 is very old, at least in the Ruby community. Any good reason why this gem should be pegged to such an old release? If not.. could I get a merge in if I submit the PR? 😄

**Comment by jawalonoski** [comment]
No strong reason, other than we were interested in maintaining backwards compatibility. Which is a good practice in general. However, you could add a newer version to the Travis file. In general, yes, we take pull requests so long as they make sense.

**Comment by jawalonoski** [comment]
See #200

**Comment by jawalonoski** [comment]
Fixed by #205
