### ISSUE TITLE
Generating valid C-CDA 

### ISSUE THREAD

**Issue by lmsurprenant** [synthetichealth/synthea#228]
I am doing some FHIR -> CCDA transformation work and I thought this project might be a good source of test data.
Unfortunately, when I ran the sample CCDA output through a validator (e.g. the one at https://sitenv.org/sandbox-ccda/ccda-validator), it pointed to a number of issues.
```
ERROR: Mu2consol US Realm Header SHALL contain at least one [1..*] recordTarget, where its type is Record Target each SHALL contain exactly one [1..1] patientRole, where  patient Role SHALL contain exactly one [1..1] patient, where  patient SHALL contain exactly one [1..1] ethnicGroupCode, where the @code SHALL be selected from OMB Standards for the Classification of Federal Data on Race and Ethnicity.
ERROR: Consol US Realm Header SHALL contain at least one [1..*] author, where its type is Author (CONF:5444) each SHALL contain exactly one [1..1] assignedAuthor, where  (CONF:5448) each SHALL contain at least one [1..*] addr (CONF:5452, R2.1=CONF:1198-5452) addr SHALL contain at least one and not more than 4 streetAddressLine (CONF:7291, R2.1=CONF:81-7291)
ERROR: Consol US Realm Header SHALL contain at least one [1..*] author, where its type is Author (CONF:5444) each SHALL contain exactly one [1..1] assignedAuthor, where  (CONF:5448) each SHALL contain at least one [1..*] addr (CONF:5452, R2.1=CONF:1198-5452) addr SHALL contain exactly one [1..1] city (CONF:7292, R2.1=CONF:81-7292)
...
```

Any plans to address those?  Or maybe I'm missing something?

**Comment by jawalonoski** [comment]
CCDA is not my strong suit (so I'm probably the one missing something), and CCDA is not a big priority at the moment.

That being said, I'd love to take a pull request on those changes to fix your issue and CCDAs.

**Comment by jawalonoski** [comment]
Which options did you use when you ran the ccda-validator?

**Comment by lmsurpre** [comment]
![image](https://user-images.githubusercontent.com/5478798/30539573-2023d3cc-9c41-11e7-9afc-478380da38ae.png)

**Comment by jawalonoski** [comment]
@lmsurpre I think I fixed this issue by updating the `health-data-standards` dependency. Care to verify by updating, generating a CCDA, and validating? I ran a few dozen records through the validator, and I didn't run into any errors.

**Comment by tmaiaroto** [comment]
I thought he was talking about FHIR -> C-CDA conversion (which I think is tricky because there's some missing information once converted to FHIR from what I'm lead to believe...in other words going back is harder).

If we're talking about the current C-CDA output, there's a few things I've noted. More than just the header section, there's some missing things. So while it may be "valid" in a sense, it's missing some key things. For example `<code>` elements contain `nullFlavor` in them so most systems will ignore all of the `<translation>` elements underneath. I've been trying to figure out how to set the `preferred_code` that the `health-data-standards` seems to use, but couldn't figure it out. That would be nice.

If you'd like I can raise more issues with C-CDA related things, but after reading this I just didn't know if it was worthwhile or if it was a real priority for the project. So I basically held off.

**Comment by tmaiaroto** [comment]
I'll also note this tool here (in Node.js), which has worked ok with some modifications. https://github.com/amida-tech/fhir2ccda  ... Not perfect though. Lots of validation errors. The date format is incorrect for starters. Though it generates quite a bit of XML from the FHIR JSON. Might be a good starting point, although it's not in Ruby.

**Comment by jawalonoski** [comment]
@tmaiaroto I assumed he was talking about our C-CDA output... not converting our FHIR JSON output into C-CDA.

The `health-data-standards` project outputs C-CDA based on templates, and not everything can be changed using the API... at least not without editing the templates.

I consider myself a C-CDA newbie. I am much more familiar with FHIR. We output the C-CDA format because people have asked for it and it is in broad use in the industry. I personally don't have a use for it, but as long as the community wants C-CDA support we'll try to maintain it.

**Comment by lmsurpre** [comment]
Yeah, my particular use case is FHIR-to-CCDA but Jason is right; my intent is that this issue be focused on the output of the synthea tool.

@jawalonoski I will try out the changes soon, thanks for doing that!

@tmaiaroto Even if its not a priority for Jason, I'd suggest opening an issue for outstanding issues you see with the C-CDA. There may be others in the community with an interest in C-CDA that might be able to pitch in.

**Comment by lmsurpre** [comment]
OK, I got around to testing it.  This update is way better, but I'm still seeing a few validation issues.
The first one I validated on SITE had no errors, but the second one I tried had 4 instances of this issue:

```Result Description: Consol Vital Sign Observation SHALL contain exactly one [1..1] value (Vital Sign Value) with @xsi:type="PQ" (CONF:7305)
Document Xpath: /ClinicalDocument/component/structuredBody/component[7]/section/entry/organizer/component[27]/observation```

Additionally, when I run them against the latest version of the mdht validator (https://github.com/mdht/mdht-models), I get the following two errors on every instance:
```
ERROR: Mu2consol US Realm Header SHALL have at least one documentationOf/serviceEvent/performer OR have at least one componentOf/encompassingEncounter/responsibleParty OR have at least one componentOf/encompassingEncounter/encounterParticipant
```
```
ERROR: Mu2consol US Realm Header SHALL contain at least one [1..*] recordTarget, where its type is Record Target each SHALL contain exactly one [1..1] patientRole, where  patient Role SHALL contain exactly one [1..1] patient, where  each SHOULD contain zero or more [0..*] languageCommunication, where  languageCommunication languageCode SHALL be selected from ValueSet LanguageCode STATIC where the @code SHALL be selected from the set of alpha-3 codes of ISO 639-2 that are in ISO 639-1
```

Not sure why the SITE validator doesn't complain about those...

**Comment by jawalonoski** [comment]
Blah. OK. I'll take a look at these in the next few days.

**Comment by lmsurpre** [comment]
For the two MDHT-reported issues, I'm guessing those are more about the templateIds you claim to conform to than any particular data issue.  If you intend Synthea to produce C-CDA 2.1 (which I think should be the target), then I think you're supposed to include an extension on the templateIds.
Example:
```
  <templateId root="2.16.840.1.113883.10.20.22.1.2" extension="2015-08-01"/>
  <templateId root="2.16.840.1.113883.10.20.22.1.1"/>
  <templateId root="2.16.840.1.113883.10.20.22.1.1" extension="2015-08-01"/>
```

**Comment by jawalonoski** [comment]
Is there a command-line way to run the mdht validator? I don't really want to have to write a whole bunch of Java code to validate the files...

I haven't been able to recreate these errors yet, I'm guessing I'm going to have to generate a lot of records and bulk validate them to find deep corner-cases.

**Comment by lmsurpre** [comment]
Re: SITE errors, I'm not sure if it will help but here is the synthea-generated file that had those errors: 
[Grady280_Lovie57_57.xml.zip](https://github.com/synthetichealth/synthea/files/1337347/Grady280_Lovie57_57.xml.zip)
I checked about 15 more just now and confirm than none of the others had this...

Re: MDHT, Unfortunately not, but you shouldn't need to write a bunch of java code to validate.  You should be able to download the latest release from https://github.com/mdht/mdht-models/ and write a main class that calls the validator (http://www.cdatools.com/docs/developeruserguide/org.openhealthtools.mdht.cda.doc.developerguide/tasks/t_Validate_CDA.html).  I understand if its not a priority.

**Comment by lmsurpre** [comment]
In case it helps, I just pushed a 1-class project that will invoke the MDHT validator on a directory of files:  https://github.com/lmsurpre/mdht-validator
The only part I forgot to mention above is that you need to load the MDHT EMF "packages" before calling the validator.

**Comment by jawalonoski** [comment]
@lmsurpre Made a bunch of changes for R2.1 upstream in `health-data-standards`. Generated and successfully validated a few thousand patients with https://github.com/lmsurpre/mdht-validator. Can you confirm and close this issue if you are satisfied?

**Comment by lmsurpre** [comment]
I confirm that with these updates, the generated files are passing validation. I don't have the power to close the issue, but please do. Thanks!
