### ISSUE TITLE
Knee Injury Care Plan Reason

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#235]
`PriorStates [Knee_Injury_CarePlan, ED_Visit_For_Knee_Injury, Knee_Injury, Adult_Incidence_Rates, Wait_For_Injury, Initial, ]`

Here the care plan references a "knee_injury" condition onset that has not yet occurred. I can't figure out an easy fix for this one, since the onset logic cannot just be moved before the care plan.

Maybe just remove the reason for now?

**Comment by jeffeastman** [comment]
Same problem with Spinal Injury

`PriorStates [Spinal_Injury_CarePlan, ED_Visit_For_Spinal_Injury, Spinal_Injury, Adult_Incidence_Rates, Wait_For_Injury, Initial, ]`

**Comment by jawalonoski** [comment]
@jeffeastman thanks for this set of issues... we'll start taking a look at them.
