### ISSUE TITLE
DSTU2 vs DSTU3 bundles

### ISSUE THREAD

**Issue by chaitanyachuri** [synthetichealth/synthea#237]
Hi, I'm trying to generate some sample FHIR bundles but in the DSTU2 specification. I see in the README for synthea that there appears to be support for DSTU2 as well, but I'm not sure I'm seeing how to generate DSTU2 spec bundles. Apologies if I'm missing something obvious but could you please help mw with this?

**Comment by jawalonoski** [comment]
Edit the `config/synthea.yml` file.

Edit line 11-12 so it looks like this:
```
    fhir_dstu2:
      export: true
```

On the command line, run
```
bundle exec rake synthea:generate
```

The output will be located in the `output/fhir_dstu2` folder.

Let me know if that works for you.

**Comment by jawalonoski** [comment]
Closed as "answered" and "no issue"
