### ISSUE TITLE
Notice to Community: Migration to Java

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#238]
The current implementation of Synthea is written in the Ruby programming language.

Ruby is fast, fun, and powerful. 

However, our runtime performance has suffered. We've attempted multithreading, jRuby, dockerization and other schemes.

In the meantime, we've quietly been rewriting the core engine in Java for a performance boost. You can explore that code here https://github.com/synthetichealth/synthea_java

In the next month or so, we plan to migrate the java engine into this repository, and remove the Ruby engine entirely.

We welcome questions, feedback, and commentary on this decision.

Thanks,
Jay.

**Comment by jamesagnew** [comment]
My mind is reeling with ideas for Synthea-HAPI integrations right now..... ;)

**Comment by jawalonoski** [comment]
This has been completed.
