### ISSUE TITLE
Uploading to HAPI-FHIR Server impossible

### ISSUE THREAD

**Issue by jspazierer** [synthetichealth/synthea#241]
Hello everybody,

when trying to upload data to my HAPI-FHIR server as described (bundle exec rake synthea:fhirupload[http://server/fhir/baseDstu3]) I get an 400 error for almost every patient.
What's going wrong (maybe my mistake, I'm a newbie to both FHIR and Synthea).
Here's the output:

Response:
Response Headers: {"server"=>"nginx/1.10.3 (Ubuntu)", "date"=>"Wed, 01 Nov 2017
11:08:40 GMT", "content-type"=>"application/fhir+json;charset=utf-8", "transfer-
encoding"=>"chunked", "connection"=>"keep-alive", "x-powered-by"=>"HAPI FHIR 3.1
.0-SNAPSHOT REST Server (FHIR Server; FHIR 3.0.1/DSTU3)"}
Response Body: {
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "Operation Outcome ERROR Transaction bundle contains multiple resources with ID: ClaimResponse/url
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Transaction bundle contains multiple resources with ID: Cl
aimResponse/url"
    }
  ]
}
  Error: 400

**Comment by jawalonoski** [comment]
Yes, this is a bug. Standby.

**Comment by jawalonoski** [comment]
This should be fixed in `master` now.
