### ISSUE TITLE
Missing required field in CarePlan

### ISSUE THREAD

**Issue by Ethan826** [synthetichealth/synthea#242]
Hi,

Unless I'm mistaken, under FHIR v3.0.1, [`CarePlan`](https://www.hl7.org/fhir/careplan.html) requires an `intent` field, which is to be a `code` from the valueset `care-plan-intent`. In the `Structure` tab on the FHIR website, the `intent` field is listed as `1..1`, ditto the UML version, and in the JSON version the red `R!` for _required_ appears.

But in the sample patients, at least `fhir/00/002/002fbbcb-3bcb-4b61-bf78-867620988911.json` appears to be missing the `intent` field. In relevant part, that patient contains the following data:

```json
{
  "status": "completed",
  "category": [{
    "coding": [{
      "system": "http://snomed.info/sct",
      "code": "53950000",
      "display": "Respiratory therapy"
    }]
  }],
  "subject": {
    "reference": "urn:uuid:9a8d83f0-1ea6-421f-91aa-3a8a0b793e11"
  },
  "context": {
    "reference": "urn:uuid:d65fb8da-7f98-4557-be32-649916a5a52e"
  },
  "period": {
    "start": "2009-01-09",
    "end": "2009-05-14"
  },
  "addresses": [{
    "reference": "urn:uuid:9f64468a-6f63-42b6-b5bf-24ab9da2dd79"
  }],
  "activity": [{
      "detail": {
        "code": {
          "coding": [{
            "system": "http://snomed.info/sct",
            "code": "304510005",
            "display": "Recommendation to avoid exercise"
          }]
        },
        "status": "completed"
      }
    },
    {
      "detail": {
        "code": {
          "coding": [{
            "system": "http://snomed.info/sct",
            "code": "371605008",
            "display": "Deep breathing and coughing exercises"
          }]
        },
        "status": "completed"
      }
    }
  ],
  "resourceType": "CarePlan"
}
```

**Comment by jawalonoski** [comment]
This was fixed just yesterday in #240. We have no yet updated the available sample data.

**Comment by Ethan826** [comment]
Ahh, great. Sorry for the duplication. I'll generate some new test patients locally. Thanks!

**Comment by jawalonoski** [comment]
No problem! Let us know if you find any other issues.
