### ISSUE TITLE
FHIR STU3 Claim has incorrect item.encounter.reference

### ISSUE THREAD

**Issue by XiaoYang-Code4Fun** [synthetichealth/synthea#255]
Hi,

The item.encounter.reference in the Claim is supposed to be a reference type, but the generated result expands it to the actual resource:
{
      "fullUrl": "urn:uuid:c8fdb007-a66f-4a20-94cf-8104a9ca4945",
      "resource": {
        "id": "c8fdb007-a66f-4a20-94cf-8104a9ca4945",
        "status": "active",
        "use": "complete",
        "patient": {
          "reference": "urn:uuid:e5329f62-4112-4eb6-9723-ed3b2a5af99a"
        },
        "billablePeriod": {
          "start": "2009-03-14T11:10:32-05:00",
          "end": "2009-03-14T11:10:32-05:00"
        },
        "organization": {
          "reference": "urn:uuid:41169063-b32c-48e1-bb89-0586fda6cbf3"
        },
        "diagnosis": [
          {
            "sequence": 1,
            "diagnosisReference": {
              "reference": "urn:uuid:e5b7fcba-c5a9-48eb-b33e-0feaf2abbaab"
            }
          },
          {
            "sequence": 2,
            "diagnosisReference": {
              "reference": "urn:uuid:1fa4f67f-82bd-46a4-9fba-35e9647b82a3"
            }
          }
        ],
        "item": [
          {
            "sequence": 1,
            "net": {
              "value": 125.0,
              "system": "urn:iso:std:iso:4217",
              "code": "USD"
            },
            "encounter": [
              {
                "reference": {
                  "fullUrl": "urn:uuid:f9387aae-176b-43b7-8d9c-4adf4295042f",
                  "resource": {
                    "id": "f9387aae-176b-43b7-8d9c-4adf4295042f",
                    "meta": {
                      "profile": [
                        "http://standardhealthrecord.org/fhir/StructureDefinition/shr-encounter-Encounter"
                      ]
                    },
                    "status": "finished",
                    "class": {
                      "code": "ambulatory"
                    },
                    "type": [
                      {
                        "coding": [
                          {
                            "system": "http://snomed.info/sct",
                            "code": "185347001"
                          }
                        ],
                        "text": "Encounter for problem"
                      }
                    ],
                    "subject": {
                      "reference": "urn:uuid:e5329f62-4112-4eb6-9723-ed3b2a5af99a"
                    },
                    "period": {
                      "start": "2009-03-14T11:10:32-05:00",
                      "end": "2009-03-14T11:10:32-05:00"
                    },
                    "reason": [
                      {
                        "coding": [
                          {
                            "system": "http://snomed.info/sct",
                            "code": "239872002",
                            "display": "Osteoarthritis of hip"
                          }
                        ]
                      }
                    ],
                    "serviceProvider": {
                      "reference": "urn:uuid:41169063-b32c-48e1-bb89-0586fda6cbf3"
                    },
                    "resourceType": "Encounter"
                  }
                }
              }
            ]
          },
          {
            "sequence": 2,
            "diagnosisLinkId": [
              1
            ],
            "net": {
              "value": 0.0,
              "system": "urn:iso:std:iso:4217",
              "code": "USD"
            }
          },
          {
            "sequence": 3,
            "diagnosisLinkId": [
              2
            ],
            "net": {
              "value": 0.0,
              "system": "urn:iso:std:iso:4217",
              "code": "USD"
            }
          }
        ],
        "total": {
          "value": 125.0,
          "system": "urn:iso:std:iso:4217",
          "code": "USD"
        },
        "resourceType": "Claim"
      }
    },

**Comment by jawalonoski** [comment]
Thanks for the bug report.
