### ISSUE TITLE
Examplitis Confusion

### ISSUE THREAD

**Issue by scottschreckengaust** [synthetichealth/synthea#264]
I need help please.

My attempt at an example generic JSON module is that 100% of the population over 45 gets an ambulatory encounter of "Examplitis", yet they never show up.  What am I missing?

Here is the JSON file (I see it load in the output):
```
{
	"name": "Examplitis",
	"remarks": [
		"100% of the population over 45 develop Examplitis." 
	],
	"states": {

		"Initial": {
			"type": "Initial",
			"direct_transition": "Guard"
		},

		"Guard": {
			"type": "Guard",
			"allow": {
				"condition_type": "Age",
				"operator": ">",
				"quantity": 45,
				"unit": "years"
			},
			"direct_transition": "ConditionOnset"
		},

		"ConditionOnset": {
			"type": "ConditionOnset",
			"target_encounter": "Encounter",
			"codes": [
				{
					"system": "SNOMED-CT",
					"code": "123",
					"display": "Examplitis"
				}
			],
			"direct_transition": "Encounter"
		},

		"Encounter": {
			"type": "Encounter",
			"encounter_class": "ambulatory",
			"codes": [
				{
					"system": "SNOMED-CT",
					"code": "456",
					"display": "Diagnosis"
				}
			],
			"direct_transition": "End_Encounter"
		},

		"End_Encounter": {
			"type": "EncounterEnd",
			"direct_transition": "Terminal"
		},

		"Terminal": {
			"type": "Terminal"
		}
	}
}
```

**Comment by dehall** [comment]
This looks fine to me. I put the file as `examplitis.json` in `src/main/resources/modules/` and deleted all the other modules. Attached are a couple sample records that show examplitis was added.

[Text - Markus389 Lueilwitz711_1e1d9381-bf87-4b02-a3cf-eaad4a195e03.txt](https://github.com/synthetichealth/synthea/files/1718167/Markus389.Lueilwitz711_1e1d9381-bf87-4b02-a3cf-eaad4a195e03.txt)
[FHIR JSON - Markus389 Lueilwitz711_1e1d9381-bf87-4b02-a3cf-eaad4a195e03.json.txt](https://github.com/synthetichealth/synthea/files/1718169/Markus389.Lueilwitz711_1e1d9381-bf87-4b02-a3cf-eaad4a195e03.json.txt)

[Text - Vinnie529 Gaylord332_fb0995e5-9ab4-48ae-8e90-2bcd2255b788.txt](https://github.com/synthetichealth/synthea/files/1718168/Vinnie529.Gaylord332_fb0995e5-9ab4-48ae-8e90-2bcd2255b788.txt)


One suggestion to check is that the records aren't being filtered - by default Synthea only exports the most recent 10 years of each patient's history. You can disable this filtering and set it to export the entire history by changing the value of `exporter.years_of_history` = 0 in `src/main/resources/synthea.properties`

**Comment by scottschreckengaust** [comment]
Setting `exporter.years_of_history = 0` resulted in output.  Thank you.
