### ISSUE TITLE
Create national population

### ISSUE THREAD

**Issue by kbrown42** [synthetichealth/synthea#272]
It seems that synthea only creates populations at the state or city level.  Is there a built in way to easily generate a population at the national level?

**Comment by jawalonoski** [comment]
Sure, we could add a task for that. So far, that has not been the typical use-case, although I am aware of one professor who has done that. His method, while not convenient, was to run the software for each state and aggregate the results.

**Comment by kbrown42** [comment]
We're going to do the same thing as the professor for now.  The group I'm working with is going to be using Synthea heavily in our research and I'd be interested in working together on modifications to the software.  Maybe we could get in touch over e-mail or slack?

**Comment by jawalonoski** [comment]
We don't have a public slack channel. Email me at `jwalonoski@mitre.org`
