### ISSUE TITLE
Can snythea create a Transcation type of Bundle?

### ISSUE THREAD

**Issue by filimon1** [synthetichealth/synthea#281]
Currently, the Bundle type in Synthea is"Collection" but was wondering if there is a way to generate a Bundle type that is "transaction" in which each resource within the bundle is distinct? 
Thank you

**Comment by jawalonoski** [comment]
There is not a simple configuration change to make that happen. You'd have to modify the one of the FHIR exporters (STU3 or DSTU2) to do that. You'd also have to add the appropriate `Bundle.entry.request` element with `POST` details. We'd be happy to take a pull request to do that, with an option to use `collection` or `transaction`.
