### ISSUE TITLE
Smoking Data

### ISSUE THREAD

**Issue by dlipt** [synthetichealth/synthea#282]
I saw the formula takes into account smoking information, but smoking is not listed in the personal information. How can I get that info to come up in the patient.csv?

**Comment by jawalonoski** [comment]
There is no easy configuration change to make the smoking data show up in the CSV.

One could alter the CSV exporter to include that as a column, alternatively we could export smoking status as an observation (which would be nice, because it would conform to the ONC CCDS approach).

**Comment by jawalonoski** [comment]
Fixed with #388
