### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by SimonUzL** [synthetichealth/synthea#283]
Hello,
I have created a PostgreSQL database to import the csv files produced by synthea. I used the schema given by the wiki entry "CSV File Data Dictionary". 
In Observations the entry value should be numeric and in CarePlans the reasoncode is not allowed to be null according to the wiki article. But i have found csv records which are violating these constraints.
In Observations there is a string "Natural death with unknown cause" for the column value which is numeric and in CarePlans there is a null reasoncode. 
Am I doing something wrong? Could that be a bug?

I can reproduce it with the command 

> ./run_synthea -p 100

 every time.

**Comment by jawalonoski** [comment]
It is a bug... Either in the wiki or the exporter. Or both.

We'll have to investigate the CarePlan issue -- a patient shouldn't be assigned a careplan for no reason... although `CarePlanStart.reason` is optional (see https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#careplanstart) so maybe that is something we need to change to required.

Re: observations. Hmm. We'll need to think about that. Our primary exporter is FHIR, which technically allows a choice of datatypes for `Observation.value` -- it seems we have some that aren't just numerics, but it looks like the FHIR exporter code handles that correctly.

Suggestions?

**Comment by jawalonoski** [comment]
Some fact finding.... Technically, the value for that observation is a code:
```json
"valueCodeableConcept": {
  "coding": [{
    "system": "http://snomed.info/sct",
    "code": "9855000",
    "display": "Natural death with unknown cause"
  }],
  "text": "Natural death with unknown cause"
}
```
When converted to CSV, only the `text` gets exported.

**Comment by SimonUzL** [comment]
The FHIR standard allows different types for the value in Observations:

[https://www.hl7.org/fhir/observation-definitions.html#Observation.value_x_](url)

But it is not possible in a relational schema to have different data types in one column. My idea would be to have three columns to solve this problem: value, unit and additionally type. For example it could look like this (I have omitted the other columns in this example):

```
... other columns |      value       | unit  |  type   
------------------+------------------+-------+---------
...               | unexpected death |       | string
...               | 32.5             | kg/m2 | decimal
...               | 82.9             | mmHg  | decimal

 Column | Type | Modifiers 
--------+------+-----------
... other columns
 value  | text | not null  
 unit   | text |           
 type   | text | not null  
```

Maybe this is a solution? 

It looks like that mapValueToFHIRType which can return StringType is used for Observation.value there:

https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/FhirStu3.java#L923

Is this the reason for the strings for Observation.value?

**Comment by jawalonoski** [comment]
> Is this the reason for the strings for Observation.value?

In FHIR, yes.

Your proposal looks reasonable. The only downside is that `type` will be duplicative, and observation is already our biggest table by far. I don't have a better proposal in mind, however.

If you want to submit a pull request against `CSVExporter.java` adding the additional `type` column, we'll happily accept it. Otherwise, I'll add it to my backlog and get to it when I can.

**Comment by SimonUzL** [comment]
Yes I can do it.

**Comment by SimonUzL** [comment]
We should update the Wiki. Do I have the permission to do that?

**Comment by jawalonoski** [comment]
I updated the wiki, thank you!

**Comment by SimonUzL** [comment]
The unit of an observation can be null.

**Comment by jawalonoski** [comment]
Correct. Fixed the wiki.
