### ISSUE TITLE
Clinical Notes

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#286]
We want to generate clinical notes in addition to the structured data.

See these resources:

Here is one link that goes beyond examples to provide guidance on content of notes:   https://www.med-ed.virginia.edu/courses/pom1/pexams/hpexam/THE%20PAST%20MEDICAL%20HISTORY_HO.htm
 
And here are some links with examples.  Although these are mostly complete history and physical exam notes, the typical daily notes are usually modeled after the same framework.
 
https://www.med.unc.edu/medclerk/files/hp1
https://www.med.unc.edu/medclerk/files/hp8
https://www.med.unc.edu/medclerk/files/hp9
http://www.columbia.edu/itc/hs/medical/physicalDiagnosis/06-07/SampleWriteUp.pdf

**Comment by garypgryan** [comment]
got it!

**Comment by jawalonoski** [comment]
See
- *Repo* https://github.com/ebegoli/SynthNotes
- *Documentation* https://synthnotes.readthedocs.io/en/latest/ 
- *Paper* https://www.osti.gov/servlets/purl/1465041

**Comment by dehall** [comment]
I'm closing this since we do now have clinical notes generated by a template (as of #571). We can open a new issue if we want to make specific enhancements to the notes.
