### ISSUE TITLE
Update wiki for distributed transitions based on attributes

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#289]
The wiki does not reflect that this is allowed:

```json
"distribution": { "attribute" : "probability_of_fall_injury", "default" : 0.06 },
```

The module builder does not support this either, probably because of this oversight.

**Comment by dehall** [comment]
That's this section: https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Transitions#named-probabilities
