### ISSUE TITLE
What is the intended use of HealthRecord.Entry.type?

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#290]
What is the `type` field of a `HealthRecord.Entry` intended for? Is it intended to always match the name of the specific entry type that extends `Entry`? For example, would the `type` of an `Encounter` state be "Encounter"?

***

`Entry.type` seems to be used in contradictory ways throughout the `HealthRecord`. For example, the `encounterClass` is set as the encounter `type` during `encounterStart`:
https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/engine/State.java#L490

In contrast, a MedicationOrder's `primaryCode` is set as the `type` during `medicationStart`:
https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/engine/State.java#L778

Also in contrast, a Report's `primaryCode` is set at the `type` during a `report`, but the primaryCode appears to be arbitrarily chosen as the code of the first observation in that ObservationGroup, whatever that observation may be:
https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/engine/State.java#L1207-L1208

***

I also see places where the `type` is used to lookup a specific state in `present`, for example to check for `conditionActive` in the HealthRecord:
https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java#L400-L402

Is `type` then intended to be a unique identifier for a state within a module? Across all modules?

**Comment by dehall** [comment]
Agree - we need this to be more clearly defined and consistently used.
