### ISSUE TITLE
increasing data

### ISSUE THREAD

**Issue by rahul-n** [synthetichealth/synthea#296]
will changing to distribution =0.99; insist of
{
          "distribution": 0.01,
          "transition": "Delay_Until_Arthritis"
} 
of  rheumatoid_arthritis.json will give 99% of RA records ?

**Comment by jawalonoski** [comment]
Yes.

**Comment by rahul-n** [comment]
But when I check encounter.csv file,  and filter data according to reasondescription= rheumatoid arthritis , I am getting lesser number of records (~8% records).Am I interpretation the encounter.csv wrong just to get RA records ??

**Comment by rahul-n** [comment]
ok , Thanks Jason.

**Comment by rahul-n** [comment]
Jason , just a small query , how is the logic for age progression is written in synthea code? 
For example :- Person is generated and he/she progress to complete age of 100 odd years or there is a bunch of population generated in starting and they progress to 100 odd year cycle.

and what is age progression interval ? I guess that is 1 week..

**Comment by jawalonoski** [comment]
Aging logic is here:
https://github.com/synthetichealth/synthea/blob/57153110be898749ec8f55975abb688ffec4b8fa/src/main/java/org/mitre/synthea/modules/LifecycleModule.java#L262

The timestep of the simulation is configured with the `generate.timestep` property which defaults to 7 days. Here:
https://github.com/synthetichealth/synthea/blob/57153110be898749ec8f55975abb688ffec4b8fa/src/main/resources/synthea.properties#L31

Patients are born on a date that is determined by the demographics of the location you are running. They then age until the present day, or die along the way.

**Comment by rahul-n** [comment]
Thanks mate :-)
