### ISSUE TITLE
Wrong MedicationOrder.prescriber references generated for fhir/DSTU2

### ISSUE THREAD

**Issue by vlad-ignatov** [synthetichealth/synthea#304]
When I attempt to insert DSTU2 bundles into my FHIR server I get OperationOutcome errors with message `Invalid reference found at path 'MedicationOrder.prescriber'. Resource type 'Organization' is not valid for this path`. I checked the reference URIs and they point to an organization indeed.

**Comment by jamesagnew** [comment]
MedicationOrder.prescriber is only allowed to be a Practitioner reference in DSTU2. Ref: http://hl7.org/fhir/DSTU2/medicationorder-definitions.html#MedicationOrder.prescriber
