### ISSUE TITLE
Filtering out conditions 

### ISSUE THREAD

**Issue by ShreyaPrasad31** [synthetichealth/synthea#308]
Hey! Is it possible to filter out and then simulate patients who have lung cancer using synthea?

**Comment by jawalonoski** [comment]
There currently isn't an out of the box way to say _"generate 100 patients with lung cancer."_

The modules are based on probabilities. So, you have a couple of options:

- Generate a lot of patients, for example into CSV, and then query the data for the subset of patients with a lung cancer diagnosis.
- Alternatively, you can modify the lung cancer module and change the probabilities or force every patient to get lung cancer. You can use the module builder for this (remember to download your changes). See https://synthetichealth.github.io/module-builder/#lung_cancer

The solution to the second option is to edit the `Lung Cancer Probabilities` state and change the transition type from `Distributed` to `Direct`. After you download it, the change will look like this:

```json
    "Lung Cancer Probabilities": {
      "type": "Simple",
      "remarks": [
        "Overall, the chance that a man will develop lung cancer in his lifetime is about 1 in 14; for a woman, the risk is about 1 in 17.",
        "http://www.cancer.org/cancer/lungcancer-non-smallcell/detailedguide/non-small-cell-lung-cancer-key-statistics",
        "Men who smoke are 23 times more likely to develop lung cancer. Women are 13 times more likely, compared to never smokers.",
        "http://www.lung.org/lung-health-and-diseases/lung-disease-lookup/lung-cancer/learn-about-lung-cancer/lung-cancer-fact-sheet.html",
        "In a 2006 European study, the risk of developing lung cancer was: 0.2 percent for men who never smoked (0.4% for women); 5.5 percent of male former smokers (2.6% in women); 15.9 percent of current male smokers (9.5% for women); 24.4 percent for male “heavy smokers” defined as smoking more than 5 cigarettes per day (18.5 percent for women)",
        "https://www.verywell.com/what-percentage-of-smokers-get-lung-cancer-2248868"
      ],
      "direct_transition": "Onset_Lung_Cancer"
    }
```

**Comment by ShreyaPrasad31** [comment]
Thanks alot! However,after changing the module, and running the command run_synthea 
I get two different types of patients 
1. Lung Cancer = 2009-10-24T17:39:57.543Z 254637007
and 
2.probability_of_lung_cancer = 0.055

I have changed the module as you suggested. Is there a way to completely remove the patients who dont have lung cancer?

**Comment by jawalonoski** [comment]
You can force everyone to be old with:

```
./run_synthea -a 65-80
```

The `-a` argument sets patient ages to be in a range. In the above example, patients will be between the ages of 65 and 80.

**Comment by ShreyaPrasad31** [comment]
Amazing! This works for most patients.

**Comment by jawalonoski** [comment]
Great. I'm going to close this issue. Let us know if you have any other issues or questions.

**Comment by ShreyaPrasad31** [comment]
Hi sorry I'm opening this again, but running 
run_synthea -a 65-80 is no longer working, its giving the following error,


> Task :run FAILED                                                                                                                                                                                                                           ERROR: unable to load demographics                                                                                                                                                                                                           java.lang.Exception: The city 10-50 was not found in the demographics file.                                                                                                                                                                          at org.mitre.synthea.world.geography.Location.<init>(Location.java:47)                                                                                                                                                                       at org.mitre.synthea.engine.Generator.init(Generator.java:124)                                                                                                                                                                               at org.mitre.synthea.engine.Generator.<init>(Generator.java:96)                                                                                                                                                                              at App.main(App.java:63)

**Comment by jawalonoski** [comment]
Hmm. I can't recreate -- can you pull the latest code from `master` and try again:

```
./run_synthea -a 65-80
```

I'm not sure why it is saying `The city 10-50 was not found in the demographics file` that leads me to believe you forgot a command line switch. The `run_synthea` command considers the last argument to the be city name (and here it thinks it is `10-50`) unless it is proceeded by a command line switch (e.g. `-a`).
