### ISSUE TITLE
Possible Improper SNOMED Code for PneumoniaEncounter

### ISSUE THREAD

**Issue by rbisewski** [synthetichealth/synthea#320]
When using synthea to generate data for a [VDEC](https://github.com/VaccineAndDrugEvaluationCentre) project, I noticed that several SNOMED codes appear to differ with regards to hospitalization encounters, some of which pointed to a code that does not exist. So I took a few minutes to look at the output and attempted to trace down what might be causing it.

After examining at the source files, I believe [this entry](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/modules/dementia.json#L668) is the origin.

Is this intended? I figure this `PneumoniaEncounter` should be SNOMED code `32485007` as it ought to simulate a hospitalization, but currently it is `34285007` which is a not a SNOMED code (at least to my current knowledge).

**Comment by jawalonoski** [comment]
You are correct. That appears to be a typo. Thanks!
