### ISSUE TITLE
Non-standardized Letter Casing with 'Emergency Room Admission' Description String

### ISSUE THREAD

**Issue by rbisewski** [synthetichealth/synthea#323]
Not an urgent issue (workarounds exist since I can check via SNOMED code), but when attempting to plot data of medical description strings in case-sensitive databases, I notice that there appears to be at least two separate strings for emergency room admissions:

* `Emergency room admission`
* `Emergency Room Admission`

Glancing at the JSON files themselves, it seems that a few files use `Emergency room admission`, of note specifically:
* [self_harm.json](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/modules/self_harm.json)
* [injuries.json](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/modules/injuries.json)
* [sever_allergic_reaction.json](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/modules/allergies/severe_allergic_reaction.json)

Other files use the `Emergency Room Admission` style for their string description instead.

I think perhaps this ought to be standardized to one style or the other? Otherwise if this is intentional, feel free to close this issue.

**Comment by jawalonoski** [comment]
Fixed in #449
