### ISSUE TITLE
How can I import synthea in Eclipse?

### ISSUE THREAD

**Issue by meSmashsta** [synthetichealth/synthea#337]
Did you use IntelliJ IDEA's IDE? I want to tinker around with the code for research purposes. There's no wiki on how to configure this to an IDE.

**Comment by jawalonoski** [comment]
In Eclipse:

`File` -> `Import...` -> `Gradle` -> `Existing Gradle Project`

Select the synthea folder. `Finish`

**Comment by meSmashsta** [comment]
Thank you so much @jawalonoski!!!
