### ISSUE TITLE
Diabetes - Multiple H1AC readings per day

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#345]
There is a bug in the metabolic syndrome modules somewhere that is causing patients to have multiple H1AC readings in a single encounter. Verbally reported by @gotdan (thanks Dan!)

I recreated this bug just by executing:
```
./run_synthea -p 100
```

CSV Observation results (filtered, sorted, and truncated):

DATE | PATIENT | ENCOUNTER | CODE | DESCRIPTION | VALUE | UNITS | TYPE
-- | -- | -- | -- | -- | -- | -- | --
9/5/89 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | 7e33a720-7e74-4d82-bad8-ab7acdf7e6b6 | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 5.9 | % | numeric
9/5/89 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | 7e33a720-7e74-4d82-bad8-ab7acdf7e6b6 | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.1 | % | numeric
9/11/90 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | f4ec75b1-e5e2-4400-9606-f9da6b2bb90b | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.2 | % | numeric
9/11/90 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | f4ec75b1-e5e2-4400-9606-f9da6b2bb90b | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.3 | % | numeric
9/17/91 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | 63b948f1-a502-453f-a680-e85fdaa1468f | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.1 | % | numeric
9/17/91 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | 63b948f1-a502-453f-a680-e85fdaa1468f | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.4 | % | numeric
9/22/92 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | ae49c3f8-a81a-4144-ae63-88b45dae7474 | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6.3 | % | numeric
9/22/92 | 065ac17c-4c99-49d0-8ab0-c5c9f6d4f873 | ae49c3f8-a81a-4144-ae63-88b45dae7474 | 4548-4 | Hemoglobin A1c/Hemoglobin.total in Blood | 6 | % | numeric

**Comment by dehall** [comment]
Issue is that two modules perform the hba1c observation at wellness encounters: the "Wellness Encounters" module as well as the Metabolic Syndrome Care module.
 I'll remove that Observation from the "wellness encounters" module since that test is associated with a specific condition. It makes more sense to me to have the metabolic care module handle it.
