### ISSUE TITLE
Guard date granularity

### ISSUE THREAD

**Issue by hadleynet** [synthetichealth/synthea#367]
Currently a guard can specify a particular year but no finer granularity. Being able to specify a year and month or a full date would be great for situations where you want to simulate the results of a specific event (e.g. a disease outbreak).

**Comment by jawalonoski** [comment]
Fixed by #377

**Comment by dehall** [comment]
One important thing to note here is that `Guard` states don't "rewind time" in the same way that `Delay` states do. Instead the Guard just checks once per timestep, and if the condition evaluates to true then it progresses forward from whatever the current date is.

What this means is that if a date is specified in a Guard, the patient may not progress through to the next state for up to a full timestep (1 week) later. Depending on the timescale involved that may or may not be an issue (ex, I expect it would be fine for a flu outbreak which takes place over months, but if people want to represent a hyper-localized incident that takes place over hours or days we may need to revisit that.)

What makes it tough to implement the same "rewind time" concept here is the fact that the Guard can check for arbitrary conditions, for instance "Date > 2007-07-07 OR attribute X is true" so digging through the logic to find the time the Guard condition became true would be complex.
