### ISSUE TITLE
Using "Week Year" instead of "Year" for date formatter

### ISSUE THREAD

**Issue by dehall** [synthetichealth/synthea#376]
TL;DR: Don't use YYYY in date format strings, use yyyy. See https://rules.sonarsource.com/java/RSPEC-3986 for a detailed explanation

https://github.com/synthetichealth/synthea/blob/v2.0.0/src/main/java/org/mitre/synthea/export/ExportHelper.java#L71
```java
 private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("YYY-MM-dd");
```

Also, should this have 4 `y`s instead of 3?

(Found by running the code through SonarLint. SonarLint found a lot of other issues in the code, but nothing else stands out as being able to produce incorrect results)

**Comment by jawalonoski** [comment]
Weird. I swear I fixed that already. Should be four `y`'s.
