### ISSUE TITLE
logo proposal for synthea

### ISSUE THREAD

**Issue by orlant** [synthetichealth/synthea#385]
hello my name is orlando velasquez I am graphic designer I like to make contributions in open source projects if you allow me I can create a Logo for this project simulator

**Comment by jawalonoski** [comment]
@orlant We already have a logo that we are happy with (see below). Though we appreciate your interest in the project and your generous offer, at this time we humbly decline.

![image](https://user-images.githubusercontent.com/1054765/42757652-cdf50762-88ce-11e8-9985-e2129679c5f3.png)

**Comment by orlant** [comment]
thank you very much for your humility friend do not worry. for a future I'm here
