### ISSUE TITLE
Encounter Physician/Provider Data

### ISSUE THREAD

**Issue by SQLDataNinja** [synthetichealth/synthea#390]
It might be useful to add one or multiple fictitious physician/provider(s) to the Encounters. This would be useful for demonstrating physician & operational analytics off of the datasets. Types of physicians I've seen on datasets that are also interesting to consider: Supervising Physician,  Referring Physician, Attending Physician, Admitting Physician, Resident Physician.

**Comment by jawalonoski** [comment]
Another pull request to export the data in FHIR #430.

**Comment by jawalonoski** [comment]
Implemented with merged PR #430
