### ISSUE TITLE
Add Encounter class to CSV files

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#405]
Add Encounter class to CSV files: e.g. inpatient, outpatient, emergency, urgent, etc.

**Comment by KeeyanGhoreshi** [comment]
How does this look?  Is it sufficient to just add the string to the `encounters.csv`?

| ID                                   | START             | STOP              | PATIENT                              | CODE      | DESCRIPTION                        | COST   | REASONCODE | REASONDESCRIPTION                    | ENCOUNTERCLASS | 
|--------------------------------------|-------------------|-------------------|--------------------------------------|-----------|------------------------------------|--------|------------|--------------------------------------|----------------| 
| 6169ff9b-2fb7-4b8e-bce4-fb4414f664a4 | 1990-03-12T18:53Z | 1990-03-12T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| 9ff6da5e-ff52-4128-9008-d01d7d73e96c | 2003-08-11T18:53Z | 2003-08-11T19:38Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 424441002 | Prenatal initial visit             | 129.16 | 72892002   | Normal pregnancy                     | ambulatory     | 
| 1708b652-4b43-491f-a04a-12b29f0808a8 | 2006-04-03T18:53Z | 2006-04-03T19:23Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| 673e1816-36be-4ef9-a418-41988639d4a8 | 2008-08-15T18:53Z | 2008-08-15T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| 4308d653-db34-41f1-973f-6703ff1bfb22 | 2009-04-06T18:53Z | 2009-04-06T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| c58aaacb-4e7a-47bb-8d98-5c2cb839dc77 | 2009-08-10T18:53Z | 2009-08-10T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| 9a0728d2-e2c7-4c64-9b95-7f298aed247c | 2009-08-13T18:53Z | 2009-08-13T20:05Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 308335008 | Patient encounter procedure        | 129.16 |            |                                      | outpatient     | 
| 89aed401-dd54-42f4-a516-d3f1aaa99e00 | 2010-08-12T18:53Z | 2010-08-12T19:19Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| b15c4c2d-274b-4bde-ac80-54cbb44f97b4 | 2011-11-19T18:53Z | 2011-11-19T19:23Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185345009 | Encounter for symptom              | 129.16 | 195662009  | Acute viral pharyngitis (disorder)   | ambulatory     | 
| 68b6f104-e07e-404a-80f9-a70b2fa712f9 | 2011-11-28T18:53Z | 2011-11-28T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| 2a200d6c-11db-490e-a499-6668459e1594 | 2012-08-01T18:53Z | 2012-08-01T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| 14d0871a-9ce2-431a-85ee-1294635ccc08 | 2013-07-27T18:53Z | 2013-07-27T19:21Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| 3904844b-9bb2-4601-8b52-c028e2cec40f | 2013-12-02T18:53Z | 2013-12-02T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| 9d994efd-5d0d-4e43-b55d-d308d7cb9ae8 | 2014-07-22T18:53Z | 2014-07-22T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| daac8c37-b80f-4188-be38-0e6852e9ba67 | 2014-07-24T18:53Z | 2014-07-24T19:56Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 308335008 | Patient encounter procedure        | 129.16 |            |                                      | outpatient     | 
| 30713c0f-0c5e-482d-8b45-4717b590d2d6 | 2014-08-11T18:53Z | 2014-08-11T19:49Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 308335008 | Patient encounter procedure        | 129.16 |            |                                      | outpatient     | 
| 3502b5db-a14f-4463-b026-3afbdb249b29 | 2015-07-23T18:53Z | 2015-07-23T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 698314001 | Consultation for treatment         | 129.16 |            |                                      | outpatient     | 
| cd61a911-6098-4893-9124-a35fd5d50699 | 2015-12-07T18:53Z | 2015-12-07T19:23Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for check up (procedure) | 129.16 |            |                                      | wellness       | 
| 63421053-0a2a-4f18-aea0-dce1b09dfc20 | 2016-06-13T18:53Z | 2016-06-13T19:53Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 50849002  | Emergency room admission           | 129.16 |            |                                      | emergency      | 
| ce1315d4-73d5-462f-a234-ea0a6ed921fc | 2016-07-11T18:53Z | 2016-07-11T19:08Z | b52fcd5d-7880-4dfe-860f-15220da4ca17 | 185349003 | Encounter for 'check-up'           | 129.16 | 403191005  | Second degree burn                   | ambulatory     |

**Comment by dehall** [comment]
@KeeyanGhoreshi Yeah that should do it
