### ISSUE TITLE
Injuries Module Is Killing A Lot of People

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#406]
When I run a 10 yr simulation of 4k patients and have only the Injuries module loaded I'm getting a big increase in deaths from the older version I was using. I'm investigating to see if its my GMF's issue or whether there's a problem in the module but the number of Bullet wound deaths especially seems inordinately high.

```
Causes of Death by year:
2016:
	2 of Bullet wound
2017:
	21 of Bullet wound
	4 of Concussion injury of brain
	1 of Fracture of the vertebral column with spinal cord injury
2018:
	261 of Bullet wound
	56 of Concussion injury of brain
	30 of Fracture of the vertebral column with spinal cord injury
2019:
	197 of Bullet wound
	38 of Concussion injury of brain
	25 of Fracture of the vertebral column with spinal cord injury
2020:
	32 of Bullet wound
	7 of Concussion injury of brain
	8 of Fracture of the vertebral column with spinal cord injury
2021:
	34 of Bullet wound
	13 of Concussion injury of brain
	5 of Fracture of the vertebral column with spinal cord injury
2022:
	23 of Bullet wound
	6 of Concussion injury of brain
	6 of Fracture of the vertebral column with spinal cord injury
2023:
	16 of Bullet wound
	4 of Concussion injury of brain
	3 of Fracture of the vertebral column with spinal cord injury
2024:
	5 of Bullet wound
	1 of Fracture of the vertebral column with spinal cord injury
2025:
	1 of Bullet wound

```

**Comment by dehall** [comment]
The injuries module hasn't changed significantly in quite a while. And the Bullet wound track is one of the least common injuries in the module -- only a 0.0318% chance of injury per year, and then only a 29.8% chance of death from it. It may be the most common cause death in the module (the others are the concussion and spinal cord injury noted above, plus burns) but it should be far from a common cause of death overall.

**Comment by jeffeastman** [comment]
Agreed, it’s illogical for there to be more gunshot deaths than the other fatal injuries, though its mortality rate is certainly higher even if its incidence rate is lower. I’m guessing its uncovering an issue in my GMF. Here are some runtimes using the same parameters but different sets of modules:

All modules except Injuries = 274 sec
All modules with Injuries = 1926 sec
Only Injuries module = 1787 sec

From this I conclude there must be a lot of time wasted within the module. Haven’t yet figured out why though.

**Comment by jeffeastman** [comment]
Closing because the problem was introduced by my ImagingStudy implementation, which first appears in the Injuries module.
