### ISSUE TITLE
Broken Images in Gallery

### ISSUE THREAD

**Issue by cmoesel** [synthetichealth/synthea#407]
There seem to be a lot of broken images in the [Module Gallery](https://github.com/synthetichealth/synthea/wiki/Module-Gallery).

![image](https://user-images.githubusercontent.com/2278253/44489552-c728a600-a629-11e8-98c4-f1605c99ff6f.png)

**Comment by dehall** [comment]
Thanks, good catch. Apparently graphviz is breaking on the name of one of the states because it contains a `<`. We'll have to escape those.

**Comment by jawalonoski** [comment]
In the interim, please browse modules here: https://synthetichealth.github.io/module-builder/

**Comment by jawalonoski** [comment]
Temporarily fixed by removing the `<`
