### ISSUE TITLE
Run a module in isolation

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#415]
Several users, including members of the [OSEHRA Synthetic Patient Data Working Group](https://www.osehra.org/groups/synthetic-patient-data-project-group) have expressed the desire to run a single module in isolation. This would be useful in testing a new module by itself. For example,

```
./run_synthea -m path/to/module/new_disease_module.json
```

A potential issue with this is the occasional interdependencies between modules, often in the form of attributes, and maybe also submodules.

**Comment by evenaglia** [comment]
A PR has been submitted that should address this feature request: https://github.com/synthetichealth/synthea/pull/453
