### ISSUE TITLE
standardhealthrecord canonical uris are not valid

### ISSUE THREAD

**Issue by cknaap** [synthetichealth/synthea#419]
The canonical uris used for the meta.profile in the FHIR STU3 readymade dataset are different from those defined by the Standard Health Record IG: http://standardhealthrecord.org/fhir/index.html
e.g.
shr-demographics-PersonOfRecord (in dataset) / shr-entity-Person (in current code, FhirStu3.java) / cimi-entity-Person (in the IG)

Since I cannot find the profiles that do belong to the used canonical uris, I cannot validate the resources from the dataset.

**Comment by jawalonoski** [comment]
OK. We'll have to fix that. In the meantime, as a work-around you can stop using the SHR profiles by changing `src/main/resources/synthea.properties`:

```properties
exporter.fhir.use_shr_extensions = false
```
