### ISSUE TITLE
FHIR Bulk Load ndjson format

### ISSUE THREAD

**Issue by niquola** [synthetichealth/synthea#420]
It would be nice to generate in format friendly to easy upload data into FHIR server.

I.e. transaction bundle or even Bulk API like files

**Comment by niquola** [comment]
Do you have ndjson option for bulk load?

**Comment by jawalonoski** [comment]
Not yet. I'll reopen for ndjson.

**Comment by jawalonoski** [comment]
You can now output ndjson bulk format. Edit `src\main\resources\synthea.properties`:
```properties
exporter.fhir.bulk_data = true
```

**Comment by neerajshri78** [comment]
Thank you very much, I was able to generate data in NDJSON format, however practitioner and hospital still gets generated in JSON and not NDJSON, is there a separately property or a known issue\limitation

**Comment by jawalonoski** [comment]
> Thank you very much, I was able to generate data in NDJSON format, however practitioner and hospital still gets generated in JSON and not NDJSON, is there a separately property or a known issue\limitation

Perhaps clear your output folder first, or update your version of Synthea.

With NDJSON you should get these files:

```
AllergyIntolerance.ndjson		DocumentReference.ndjson		MedicationAdministration.ndjson		Procedure.ndjson
CarePlan.ndjson				Encounter.ndjson			MedicationRequest.ndjson		Provenance.ndjson
CareTeam.ndjson				ExplanationOfBenefit.ndjson		Observation.ndjson			SupplyDelivery.ndjson
Claim.ndjson				ImagingStudy.ndjson			Organization.1721218811633.ndjson	parameters.json
Condition.ndjson			Immunization.ndjson			Patient.ndjson
Device.ndjson				Location.1721218811633.ndjson		Practitioner.1721218811633.ndjson
DiagnosticReport.ndjson			Medication.ndjson			PractitionerRole.1721218811633.ndjson
```

The file names will be the same, except the stamp `1721218811633` will change.
