### ISSUE TITLE
Export FHIR Practitioner resources

### ISSUE THREAD

**Issue by okeefm** [synthetichealth/synthea#424]
Now that `Encounter`s are populated with Synthea `Clinician`s, it would be helpful to export them in the FHIR output as `Practitioner` resources. Probably the most logical place is in the `HospitalExporter`, where the `Organization`s are being exported now.

**Comment by jawalonoski** [comment]
Work in progress: #430

**Comment by jawalonoski** [comment]
Implemented with merged PR #430
