### ISSUE TITLE
CSV export does not working

### ISSUE THREAD

**Issue by hurcy** [synthetichealth/synthea#426]
I set 'exporter.csv.export = true'. But, I couldn't export csv files.

**Comment by SimonUzL** [comment]
Have you tried these steps in the following order?
1. Set exporter.csv.export to true
2. ./gradlew build check test
3. ./run_synthea -p 100 (for example)

Now you should find the CSV files under output/csv/.

**Comment by hurcy** [comment]
Thanks! I didn't know I had to rebuild. 
I wrote about this in https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary

**Comment by akshayklr057** [comment]
Hi, @SimonUzL I have done the steps mentioned above. Also, my Gradle build was successful but it still didn't generate any CSV for me.

**Comment by jawalonoski** [comment]
Try adding `--exporter.csv.export=true` to the command line if your `synthea.properties` file isn't getting picked up.

E.g.
```
./run_synthea --exporter.csv.export=true
```
