### ISSUE TITLE
Adding O2 saturation

### ISSUE THREAD

**Issue by hurcy** [synthetichealth/synthea#435]
Hi,

I want to generate O2 saturation, but I'm not sure where to start.
Could you list java class and config files I should edit?

**Comment by hurcy** [comment]
Just to check O2 saturation is generated I edited these files.
- biometircs.yml
`      oxygen_saturation: [80,100] # mmHg`
- modules/congestive_heart_failures.json
```
"observations": [
        {
          "category": "laboratory",
          "vital_sign": "Oxygen saturation",
          "codes": [
            {
              "system": "LOINC",
              "code": "2710-2",
              "display": "Oxygen saturation"
            }
          ],
          "unit": "mmHg"
        },
 ...
```
- org.mitre.synthea.world.concepts.VitalSign.java
definition of oxygen_saturation
- org.mitre.synthea.modules.LifecycleModule.java
definition of oxygen_saturation and its range

**Comment by jawalonoski** [comment]
Hello. First, this looks like a reasonable approach. Second, thank you for answering your own question.

Make sure the value of the `"vital_sign"` JSON attribute matches the serialized text of your oxygen saturation as declared in `VitalSign.java` -- it is might be case-sensitive.

E.g.

```java
@SerializedName("Oxygen Saturation") OXYGEN_SATURATION, 
```
and

```json
"vital_sign": "Oxygen Saturation",
```

**Comment by hurcy** [comment]
@jamesagnew You are spot on!
It is case-sensitive. Thanks.
