### ISSUE TITLE
CSV: Excel CSV import returns an SYLK file format error

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#443]
Apparently some versions of MS Excel will throw errors opening our CSV files if the very first characters in the file are "`ID`" -- as it incorrectly assumes they are SYLK files and fails to properly load them.

Reference: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_win10-mso_o365b/sylk-error-when-opening-csv-files-in-excel/3764f46e-52de-49f2-a77a-21ab9cf84f75

For the time being, I'm setting the "status" of this issue as `Won't Fix` but I'm willing to discuss and interested in feedback from the community.

**Comment by dehall** [comment]
According to the following, two possible simple fixes for this are to ensure the file is UTF-8, or rename the field to "Id" instead of "ID".

https://superuser.com/questions/879802/how-to-disable-sylk-warning-for-csv-files-in-excel

**Comment by ramdesh** [comment]
I can pick this up if it's not being worked on.

**Comment by jawalonoski** [comment]
Go for it.

**Comment by ramdesh** [comment]
@jawalonoski Does renaming `ID` to `Id` seem like a good fix? Wouldn't that make the headers sort of inconsistent?

**Comment by jawalonoski** [comment]
@ramdesh Yes, it would. I'm not sure it matters except aesthetically. Of course, if someone wrote some code that was case-sensitive, they'd have to fix it. But I'm OK with the change.

**Comment by shusson** [comment]
> Of course, if someone wrote some code that was case-sensitive, they'd have to fix it.

@jawalonoski  I did :D

I updated the wiki to reflect this change
