### ISSUE TITLE
procedure missing in generated fhir output

### ISSUE THREAD

**Issue by bbutzin** [synthetichealth/synthea#458]
It seems that some Procedures from the modules are not generated in the fhir output.

**What I've tried:**
I've created my own [module](https://github.com/bbutzin/synthea-endoscopy-module/blob/master/endoscopy.json)
The module shall ensure that all patients (>50yr) had an endoscopic procedure.

I've copied the module file into synthea <SYNTHEA_PATH>\src\main\resources\modules\
(using master branch commit: c09557283bebd05689b265cb2025514236a4e98c)

I have run it with:
Settings (diff-to-default):
generate.log_patients.detail = detailed
generate.track_detailed_transition_metrics = true
generate.append_numbers_to_person_names = false

.\run_synthea -p 1 -a 50-80 -o false > out.log

**What I have expected:**
Within the module there is no chance not to have an endoscopy, so I expected to find a procedure with the respective SNOMED-CT Code 423827005 "Endoscopy" at all patients that are older than 50 years.

**What actually happend:**
In some (but not all) cases the procedure is not added as expected.

I have uploaded such a case to my [repo](https://github.com/bbutzin/synthea-endoscopy-module)
In the console log [out_reduced.log](https://github.com/synthetichealth/synthea/files/2672039/out_reduced.log) I can clearly see that the respective state 'endoscopy_procedure' was processed. (The full log is also available in the repo)

However, in those cases where procedure is not generated , sometimes the follow up visit (after the procedure) is still generated.
In my [example output](https://github.com/bbutzin/synthea-endoscopy-module/blob/master/output/fhir/Andres_Schmitt_11255e61-595d-4655-be47-711c9f77c805.json) the follow up visit is "urn:uuid:bd42ddf4-fd20-43d3-8016-ac3974fc81b0" but ther is no respective .

**Comment by dehall** [comment]
In your sample output the follow up visit is dated 1994, so it looks like what happened here is that the Procedure was added to the record but then filtered out by the export filter before writing the file. By default, Synthea only keeps record entries from within the past 10 years, including any "open" items from more than 10 years ago. This is done for a few reasons, including reducing file size, the fact that real patient health records rarely contain a full lifetime of history, and the fact that our modules are based on contemporary medical practices, so the further back in time you look the less realistic the record tends to be.
In this specific instance, the Hematoma condition is still open (has no end date) so it's preserved, but the Encounter where the Endoscopy occurred contains no "open" conditions or medications so it was filtered out.

If you want to ensure that all entries are kept in the record, there is a configuration setting `exporter.years_of_history` in synthea.properties, which you can change to `0` to keep all history and not do any filtering, or change to another higher number to keep more years. https://github.com/synthetichealth/synthea/wiki/Common-Configuration

**Comment by bbutzin** [comment]
Okay that was the reason!
Thank you very much for your help.
