### ISSUE TITLE
lib/records/lookup.rb contains constants that are meant to be mutated

### ISSUE THREAD

**Issue by eedrummer** [synthetichealth/synthea#47]
This file defines a bunch of module level constants. However, lib/generic/states.rb provides a method to modify these constants. These lookup tables should be refactored to not use constants if the intention is to modify them.

**Comment by jawalonoski** [comment]
Originally the were not meant to be modified. That happened when the generic modules were introduced. We'll have to refactor this at some point.

**Comment by dehall** [comment]
Closing this as OBE since it only applies to the Ruby implementation. Java impl doesn't use lookup tables
