### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by organsnyder** [synthetichealth/synthea#470]
I'd like to use Synthea as a library within another application (the command-line runner isn't quite what I need). Ideally, it would be nice to be able to have Synthea in Maven Central. If I were to create a PR with the necessary changes to the Gradle build config, would that be welcome? There would also need to be some changes to the Travis build to publish the artifacts—I'd be willing to help with that as well.

**Comment by jawalonoski** [comment]
Yes, that sounds reasonable and would be welcome.

**Comment by jawalonoski** [comment]
Synthea has been modified to run as a jar in #557 but is not published in any dependency management repositories.

**Comment by jawalonoski** [comment]
See https://github.com/synthetichealth/synthea/wiki/Embedding

**Comment by shabiel** [comment]
Wow!
