### ISSUE TITLE
failed to build tests when working with JDK 11

### ISSUE THREAD

**Issue by Sobhym** [synthetichealth/synthea#473]
Related issue: #349. 

I couldn't run the tests when working with JDK 11. Here is the output
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> failed to read class file \path\synthea\build\classes\java\test\apptest.class

```
I found that the issue was reported to gradle, refer to,
https://github.com/gradle/gradle/issues/7059

It should have been fixed for gradle 5.0-milestone-1, please upgrade gradle.

Thanks

**Comment by jawalonoski** [comment]
Let me know if this fixes your issue or not. Thanks.

**Comment by Sobhym** [comment]
The issue is fixed. Thanks.
