### ISSUE TITLE
Improve UCUM code for "millimeter Mercury column"

### ISSUE THREAD

**Issue by alexzautke** [synthetichealth/synthea#495]
According to http://unitsofmeasure.org/ucum.html#datyp2apdxatblxmp, the correct code for "millimeter Mercury column" is "mm[Hg]", although it recognises that "mmHg" is used commonly (See §44 units used predominantly in clinical medicine). My suggestion would be to use the official unit in Observation.component.valueQuantity.code when exporting to FHIR. Observation.component.valueQuantity.unit could still refer to the "old" unit.

**Comment by jawalonoski** [comment]
Thank you for the bug report!
