### ISSUE TITLE
Issue with Synthea Installation on Windows 10

### ISSUE THREAD

**Issue by YY0598** [synthetichealth/synthea#498]
I tried to install it on Windows 10 and followed the below instruction: 
git clone https://github.com/synthetichealth/synthea.git
cd synthea
 .\gradlew.bat build check test 

it reports "bash: .gradlew.bat: command not found". 

I also tried "./gradlew build check test". It was 99% successful. It failed on FHIRDSTU2ExporterTest. testFHIRDSTU2Export.

I have successfully installed JDK and Gradle. I also set "git config --global core.autocrlf false". 

Any help would be greatly appreciated!
![Synthea setup test](https://user-images.githubusercontent.com/48924115/54941293-df83da80-4f02-11e9-8787-dc27cd9d4244.JPG)

**Comment by YY0598** [comment]
Thank you very much for your prompt response! 

It works this time. However, I am still wondering why "./gradlew build check test" works on Windows 10? And why it reports "bash: .gradlew.bat: command not found" on ".\gradlew.bat build check test"?

**Comment by jawalonoski** [comment]
I don't know. There is a `gradlew.bat` file in the repo, as part of gradle. I do not use Windows, so I cannot help you debug that.

**Comment by dehall** [comment]
@YY0598 are you using the "Windows Subsystem for Linux" or "Bash on Ubuntu on Windows" or anything like that? That would explain why you're those results for those commands. It is technically running on Windows but it's a Linux-based environment within Windows so you would use the Linux/Mac versions of the commands instead.

**Comment by YY0598** [comment]
@dehall Thank you so much! I am using Git Bash, which may explain the issue. Thank you!
