### ISSUE TITLE
Patient population generation within R or Python

### ISSUE THREAD

**Issue by onenonlykpro** [synthetichealth/synthea#501]
Hi - I have been incredibly interested in using Synthea, but I am working from a machine where I have severely limited installation privileges. The data science implications for Synthea are vast, but I cannot find any R or Python libraries that utilize Synthea. Being able to simulate patient populations within either one of those data science languages/programs would be incredibly helpful. Did I miss it, or is that something that is still needed?

**Comment by jawalonoski** [comment]
There is the Bunsen project (https://github.com/cerner/bunsen-tutorial) which uses Synthea FHIR data in a Jupyter notebook.

You could also use our [csv](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary) output and pull that into Python or R.

But that would be using Synthea data after it was already generated. I'm not aware of any R or Python tools that call out to Synthea to generate data on the fly, if that is what you're asking about.

Anyone know about any others?

**Comment by onenonlykpro** [comment]
> There is the Bunsen project (https://github.com/cerner/bunsen-tutorial) which uses Synthea FHIR data in a Jupyter notebook.
> 
> You could also use our [csv](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary) output and pull that into Python or R.
> 
> But that would be using Synthea data after it was already generated. I'm not aware of any R or Python tools that call out to Synthea to generate data on the fly, if that is what you're asking about.
> 
> Anyone know about any others?

Thank you for the quick reply. That is exactly what I am asking about:  R or Python tools that call out to Synthea to generate data on the fly.

**Comment by tiloc** [comment]
I have had some success in importing the Synthea FHIR output with the Smart-on-FHIR library for Python.
https://github.com/smart-on-fhir/client-py

**Comment by jawalonoski** [comment]
There are tools and methods for _using_ Synthea generated data within R or Python. But _generating_ patients within R or Python is out of scope for this project, so I'm going to close this issue.
