### ISSUE TITLE
Uploading synthea generated fhir patient data to Google FHIR storage failing

### ISSUE THREAD

**Issue by hsyedsplineai** [synthetichealth/synthea#515]
Hi,

I found the following error on uploading a synthea generated FHIR json file to Google Cloud FHIR storage. The command and the error message is given below:
-------------------------------------------------------------
 curl -X POST     -H "Authorization: Bearer "$(gcloud auth print-access-token)     -H "Content-Tye: application/fhir+json; charset=utf-8"     --data @Desktop/Winston220_Metz686_a990fa9d-0d58-4094-b38a-9c25d05c6ed4.json "https://healthcare.googleapis.com/v1beta1/projects/clinic-data/locations/us-central1/datasets/patientinfodemo/fhirStores/patientinfofhir15/fhir"
{
  "issue": [
    {
      "code": "structure",
      "details": {
        "text": "unparseable_resource"
      },
      "diagnostics": "error at \"entry[4].resource\": unknown field \"encounter\"",
      "severity": "error"
    }
  ],
  "resourceType": "OperationOutcome"
}
-------------------------------------------------------

The fhir json file is generated using the command: "run_synthea -s 100 -p 100" with "bulk" option switched-off from the configuration.
Could you Pls suggest why it failed to upload the fhir data in GCP. What is the reason for this format error? Is there any particular setup options we have to use create fhir json data files to upload to GCP.
Some suggestion I found that changing "encounter" on a care plan to "context" will work.

**Comment by jawalonoski** [comment]
The default FHIR output in Synthea is FHIR R4.

The Google FHIR API is FHIR STU3, so you need to turn STU3 on, and try to upload that instead.

```properties
# Exporting FHIR STU3
exporter.fhir_stu3.export = true
```
