### ISSUE TITLE
Identifying minimal set of required modules when generating data for a single module

### ISSUE THREAD

**Issue by ReinierKop** [synthetichealth/synthea#518]
I'm trying to generate "clean" patients, i.e. patients with only a single isolated disease or condition using the `-m` switch.

I already understand that there are some default modules which will always run; that's fine. I want to basically "turn off" as many other modules as I can for each disease/module I'm trying to investigate. However, there are obvious strong inter-modular interactions which leads me to believe I can't just single out a specific module like this. (this potential issue is also mentioned [here](https://github.com/synthetichealth/synthea/issues/415#issue-359067996))

For example, when generating the course of pregnancies, I've found that the command below does not generate any pregnant women (no people will ever have more than their default encounters/procedures, also when increasing population count)

```bash
./run_synthea -p 50 -m "Pregnancy" -g F -a 25-40 --exporter.baseDirectory ./output/pregnancy/ --exporter.fhir.export false --exporter.csv.export true
```

But in the command below I've apparently added enough dependent modules (through trial and error) that I do start seeing pregnancies. Removing any one of these modules will stop any pregnancies from being generated once again.

```bash
./run_synthea -p 50 -m "Contraceptives;Female_Reproduction;Pregnancy;Sexual_Activity" -g F -a 25-40 --exporter.baseDirectory ./output/pregnancy_with_added_modules/ --exporter.fhir.export false --exporter.csv.export true
```

The issue is that I can never be sure if there are other/more dependent modules which will make the generated data more reliable for each of the modules I'm interested in.

My question is this: how can I find out what is the minimal set of modules I need to add for a specific module to start generating sensible data? And is this not something that can be automatically picked up by the pregnancy module, that it also loads its dependencies somehow?

**Comment by jawalonoski** [comment]
@ReinierKop great questions. Bottom-line: currently, there is no automatic way to find the minimal set of modules (other than the submodules, which are always loaded). This would be a nice change to make.

Synthea is designed to run with all the modules a vast majority of time.

In my mind, the `-m` switch is meant really for testing out modules as you develop them, or for other testing cases like you mentioned, e.g. having "clean" data only related to a single condition or family of conditions.

But you've managed to find the weakness in this approach -- dependencies between modules. Most of the modules are linked together using either submodules or Patient attributes. But also [Active Condition](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Logic#active-condition), [Active Medication](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Logic#active-medication), [Active CarePlan](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Logic#active-careplan).

You can generate a complete list of Patient attributes and which modules read/write to those attributes:

```
./gradlew attributes
```

Some files are generated:
```
./output/attributes.json
./output/attributes_all.png
./output/attributes_readwrite.png
```

The JSON looks something like below. For example, the attribute `pregnant` has a list of modules that `read` and `write` to that attribute. In the snippet below, the `Contraceptive Maintenance` module reads the `pregnant` attribute from three different states (e.g. 'IUD_Maintenance', 'Implant_Maintenance', 'Injectable_Maintenance').
```json
  "pregnant": {
    "read": {
      "Contraceptive Maintenance": [
        "IUD_Maintenance",
        "Implant_Maintenance",
        "Injectable_Maintenance"
      ],
      "Contraceptives": [
        "Reset_Contraceptive_Use"
      ],
      "Female Reproduction": [
        "Female_Reproductive_Cycle"
      ],
      "HealthInsuranceModule": [],
      "Implant Contraceptive": [
        "Initial"
      ],
      "Injectable Contraceptive": [
        "Initial"
      ],
      "Intrauterine Device": [
        "Initial"
      ],
      "Oral Contraceptive": [
        "Initial"
      ],
      "Patch Contraceptive": [
        "Initial"
      ],
      "Vaginal Ring Contraceptive": [
        "Initial"
      ],
      "anemia_sub": [
        "Female"
      ]
    },
    "write": {
      "Female Reproduction": [
        "Become_Pregnant"
      ],
      "LifecycleModule": [],
      "Pregnancy": [
        "Initially_Not_Pregnant",
        "Unset_Pregnant_Attribute"
      ]
    },
    "example_values": [
      "Boolean",
      "false",
      "true"
    ]
  }
```

**Comment by ReinierKop** [comment]
Thanks for your lengthy response! I've been checking out the attributes json and I think I should be able to make sense of it using that as a resource. I'll close this issue for now. Thanks again.
