### ISSUE TITLE
quiet flag

### ISSUE THREAD

**Issue by fdefalco** [synthetichealth/synthea#519]
Would it be possible to add a "quiet flag" to suppress console output?  When scaling to some of the larger data sets we are generating (in the millions of patients) we notice a significant difference in speed if we background the process output so it doesn't write to console.  A flag would be preferable especially when we're moving between operating systems and the background syntax varies.

**Comment by dehall** [comment]
You can reduce the output by changing the setting `generate.log_patients.detail` to the value `none` in the file `src/main/resources/synthea.properties`, or alternatively with command line arg `--generate.log_patients.detail=none`

This will disable the logging of a line for each individual patient, though it will still print a message every 30 seconds displaying the "waiting" message with some stats of how many patients have been queued and completed.
