### ISSUE TITLE
City Distribution in Synthea

### ISSUE THREAD

**Issue by anujm03** [synthetichealth/synthea#520]
When generating Synthea samples from each state, the cities of residence for the patients do not appear representative of the population at the city level.
 
For example, 11,023 patients were generated in Texas. If the patient population were truly representative of the state, we would expect a lot more patients from the 3 largest cities in Texas. In the generation, there were only 8 patients from Houston and 0 from Dallas and San Antonio. The three most common cities were El Paso, Arlington, and Lubbock; reasonably large cities but significantly smaller than the top 3.
 
2 spreadsheets are attached.
 
One is what the actual city breakdown was in the Synthea sample.
 
The other is what the breakdown would look more like if it was stratified at the city level.

[Sample Texas Patients 060319.xlsx](https://github.com/synthetichealth/synthea/files/3253240/Sample.Texas.Patients.060319.xlsx)

[Patients at City Level.xlsx](https://github.com/synthetichealth/synthea/files/3253245/Patients.at.City.Level.xlsx)

**Comment by dehall** [comment]
Just commenting to say I confirmed the issue when generating Texas. Houston, San Antonio, and Dallas are all listed in the demographics file as being the largest cities so there should be more patients generated there.
I also ran the state of Massachusetts for comparison and it was generally as expected: ~1/10 people in Boston, also large numbers in Worcester, Springfield, etc.

**Comment by jawalonoski** [comment]
The issue is that there are multiple entries for Houston, and they override each other. It just so happens that the last one in is the winner:

```csv
30338,157.0,Houston,Texas,42127.0,Fort Bend County,716087.0,0.4917125991674196,0.5082874008325804,0.5680482958076323,0.2411327115280685,0.2094982872192904,0.1948268855599948,0.005837279548434758,0.001,0.06708123454273014,0.07878511968517792,0.08258773026182573,0.07365585466570403,0.05972877597275191,0.05622361528696932,0.06847073051179535,0.07417394813758664,0.07879629151206488,0.07253029310684317,0.06885755501775623,0.06649471363116492,0.053591253576730204,0.04033588097535635,0.024668790244760763,0.015214631741673847,0.009331268407330394,0.009472312721778219,0.07,0.05,0.11,0.1,0.14,0.16,0.1,0.11,0.04,0.06,0.21,0.29,0.39,0.09
30339,201.0,Houston,Texas,2248403.0,Harris County,4538028.0,0.4974460272171084,0.5025539727828916,0.7017931577328302,0.4197768281729421,0.19559465036354998,0.07206786736441467,0.011106806745132466,0.001,0.07669410589798036,0.07699688058337234,0.0733970790836901,0.06796101742871573,0.07205883260306019,0.08148693661652154,0.08056869635885895,0.07344776189128846,0.06960600507533228,0.06404433820152719,0.06228057649710403,0.05899919524515935,0.04799088943479415,0.03551322292414238,0.023244237364776064,0.015080559220877438,0.010319460347093495,0.010310205225705967,0.07,0.05,0.11,0.1,0.14,0.16,0.1,0.11,0.04,0.06,0.21,0.29,0.39,0.09
30340,339.0,Houston,Texas,5694.0,Montgomery County,537559.0,0.49557908992315264,0.5044209100768474,0.8930684817852552,0.2311653232482388,0.05010054710273663,0.02783136362706233,0.009818457136798008,0.001,0.06730982087547599,0.07530708257140147,0.0777942514217044,0.0704294784386458,0.06041569390522715,0.060769143480064514,0.06566162970018175,0.06684475564542683,0.06959794180731789,0.0692612345807623,0.07027321652134928,0.06747910461921389,0.055835731519702954,0.04590937924953354,0.03213786765731762,0.02022475672437816,0.012874865828681132,0.011874045453615324,0.07,0.05,0.11,0.1,0.14,0.16,0.1,0.11,0.04,0.06,0.21,0.29,0.39,0.09
```

So the system thinks Houston has 5694 people.

Working on a fix....

**Comment by jawalonoski** [comment]
Fixed.
