### ISSUE TITLE
Missing Cities in Synthea

### ISSUE THREAD

**Issue by anujm03** [synthetichealth/synthea#525]
The following cities do not show up in Synthea.

Indianapolis, Indiana; pop. 853,431
Nashville, Tennessee; pop. 654,187
Louisville, Kentucky; pop. 615,478
Baton Rouge, Louisiana; pop. 227,549
Augusta, Georgia; pop. 196,899
Lafayette, Louisiana; pop. 126,476
Athens, Georgia; pop. 122,292

It may be have something to do with the way the census defines them. For example, Indianapolis is a consolidated city-county with something called a "balance" population.

https://en.wikipedia.org/wiki/Indianapolis

**Comment by jawalonoski** [comment]
- [ ] `Indiana Indianapolis`
- [ ] `Tennessee Nashville`
- [ ] `Kentucky Louisville`
- [ ] `Louisiana "Baton Rouge"`
- [ ] `Georgia Augusta`
- [ ] `Louisiana Lafayette`
- [ ] `Georgia Athens`
- [ ] `"District of Columbia" Washington`

**Comment by jawalonoski** [comment]
I managed to fix those cities, but I've found some interesting bugs. I'm not making sure that it will run for all states out of the box. Fixes pending...
