### ISSUE TITLE
Provider vs. Organization Mixup in Encounters Table

### ISSUE THREAD

**Issue by anujm03** [synthetichealth/synthea#547]
I am going through the encounter table, and I notice that there is a column called “provider”, but it actually maps to the “organization” facility, rather than the provider. I also noticed that there are now some organizations with more than 1 provider, but an overwhelming majority still only have 1. This means that in a lot of cases we do not know who the provider or physician is in an encounter. When we do know, it's because we have the issue of only having one provider in the facility.

Below is a sample query, and attached are the query output and the Synthea generation. The output is a join of the encounters and organization table, and the columns are color coded based on the table.

select *
from national300k.encounters_filtered e
--join national300k.providers300k prov on e.provider = prov.id--"provider" column does not map to "provider" table
join national300k.organizations_filtered o on e.provider = o.id--"provider" column maps to "organization" table, output attached
limit 10

[encounters_organizations_joined.xlsx](https://github.com/synthetichealth/synthea/files/3408463/encounters_organizations_joined.xlsx)
[states_300K.txt](https://github.com/synthetichealth/synthea/files/3408467/states_300K.txt)

**Comment by ramdesh** [comment]
Is this on database output? If so, you validate if it is the same for a file-based output such as CSV?

**Comment by anujm03** [comment]
Yes, if you run the code in the attached text file for even just one state, you will notice the same issues in the csv output when looking at the encounters, organizations, and providers csvs.

**Comment by JLMoszkowicz** [comment]
This is tripping us up as well.  Is there a plan to address this?

**Comment by jawalonoski** [comment]
Fixed.

**Comment by JLMoszkowicz** [comment]
Thanks!  As I understand this change, though, this just clarifies that it is the organization that is referred to in the encounters table.  We are really hoping to get to the provider for the encounter.  Is there a way to get that?

**Comment by jawalonoski** [comment]
The change did do that. I added a new organization column, and changed the provider column to refer to the provider.

**Comment by JLMoszkowicz** [comment]
Fantastic!  Will you be updating the CSV download?

**Comment by jawalonoski** [comment]
> Will you be updating the CSV download?

Eventually. Not a high priority at the moment. You should be able to run the project locally and get new data pretty easily.
