### ISSUE TITLE
Replace UUID as float

### ISSUE THREAD

**Issue by rick1314** [synthetichealth/synthea#552]
I have everything working as I require, only thing is, the data I am trying to generate needs the IDs to be float instead of UUID. 
Can someone suggest modification so that I can achieve this?

**Comment by jawalonoski** [comment]
# FHIR DSTU2

**Comment by jawalonoski** [comment]
# Person ID
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/modules/LifecycleModule.java#L124

# FHIR DSTU2
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/FhirDstu2.java#L1588-L1591

# FHIR STU3
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/FhirStu3.java#L2394-L2397

# FHIR R4
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/FhirR4.java#L2222-L2225

# CSV
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/CSVExporter.java#L471
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/CSVExporter.java#L794
https://github.com/synthetichealth/synthea/blob/75bc9d2b6e8d444bdf99a591bf92fae70b00615e/src/main/java/org/mitre/synthea/export/CSVExporter.java#L471
