### ISSUE TITLE
Can't create API key because can't click e-mail

### ISSUE THREAD

**Issue by PatriciaNguyen** [synthetichealth/synthea#563]
Hi, 

Working on PDM with goinvo team and can't create an API key following these instructions:

https://synthea.mitre.org/api-keys

click on email button does nothing.

**Comment by PatriciaNguyen** [comment]
OK thanks! Clearing cache didn't help. But got it to work on Edge (of all things...chrome didn't work for me).

**Comment by jawalonoski** [comment]
OK, weird. I'm going to close this as a fluke, but if anyone else can replicate this issue, or can supply detailed debugging data, I can try to look into it.
