### ISSUE TITLE
New Feature: Auto Renewal of Medication Orders

### ISSUE THREAD

**Issue by shabiel** [synthetichealth/synthea#564]
This is a proposal to be able to automatically renew medications (i.e. new prescription; not refills of a current prescription) according to rules in the model, rather than code the repeat of the medication inside of the model itself.

The proposal is to add the attribute `auto_renew` to the Generic Module Framework's `MedicationOrder > prescription` model; and `auto_renew_duration_years` for how long the auto_renew should go on.

`auto_renew` will result in the creation of the same medication order when the previous prescription runs out. This is calculated by the formula: `(prescription.refills + 1) x prescription.duration.quantity x prescription.duration.unit (in days)`. If there is no `auto_renew_duration_years`, the auto-renewal will continue till the death of the patient.

**Comment by jawalonoski** [comment]
When does the auto renewed `MedicationOrder` (DTSU2) or `MedicationRequest` (STU3, R4) get created? At the next encounter with the same provider? Or does it get created exactly when it should (i.e. according to the formula) without being linked to an encounter? Or is it linked to the original encounter, but the `MedicationRequest` has a different/later time?

**Comment by shabiel** [comment]
That is a great question. I did not think this far ahead yet.

In real life, when I worked as a pharmacist, I would tell the patients that they need to call their doctor/provider. Sometimes the doctor/provider will just perform a "telephone encounter", and prescribe a medication; and sometimes they will see the patients in an in person encounter. So I think the right answer is: Create a new encounter at the time the patient needs a new medication with the same provider. We are still discussing how to get the diagnoses for the new encounter.

**Comment by jawalonoski** [comment]
It would be easier to just link to the original encounter, but that might not be "correct." Creating a new encounter, out of band from the module that originally prescribed the medication, might have a strange effect especially if it wasn't the primary care physician that prescribed it. Worth exploring though and seeing what it looks like.

**Comment by shabiel** [comment]
I am talking with @petercyli right now and we are thinking of an alternate implementation based on the wellness encounter. Each wellness encounter will re-prescribe "chronic" medications. So the new flag will be called "chronic". The old medications in the module would be stopped and they will be re-issued.

**Comment by shabiel** [comment]
Here's the current plan Jason.

1. Add a Chronic Medications Map <Code, Medications> to Person.Java and include in initialization.
2. Add code to State.java here to add/remove to Chronic Medications Map based on the presence of "chronic": true in prescription JSON: https://github.com/synthetichealth/synthea/blob/7b7d9fb5426c37aac72e8d5922553beced74891e/src/main/java/org/mitre/synthea/engine/State.java#L794
3. Add Chronic Meds Renewal code to the wellness encounter code here: https://github.com/synthetichealth/synthea/blob/7b7d9fb5426c37aac72e8d5922553beced74891e/src/main/java/org/mitre/synthea/engine/State.java#L490

**Comment by jawalonoski** [comment]
Fixed with #568
