### ISSUE TITLE
Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_221 contains a valid JDK installation.

### ISSUE THREAD

**Issue by dikokob** [synthetichealth/synthea#575]
When running the following command:

`gradlew build check test`

I get this error:

`:versionTxt
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_221 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
2 actionable tasks: 2 executed`

Here is the gradle scan: https://scans.gradle.com/s/odv6gd45tem3u/

**Comment by jawalonoski** [comment]
JRE is the Java Runtime Environment, it does not include a compiler.

You need the JDK: Java Development Kit.

You can install a JDK from a lot of sources. Here is one: https://adoptopenjdk.net

**Comment by chrissten** [comment]
@dikokob, I had the same problem. I just had to modify my JAVA_HOME to point to the jdk instead of the jre:
`SET JAVA_HOME=C:\Program Files\Java\jdk-12.0.2`

**Comment by fluttercorner1** [comment]
This Solution may help you [https://fluttercorner.com/how-to-solve-flutter-could-not-find-tools-jar/](https://fluttercorner.com/how-to-solve-flutter-could-not-find-tools-jar/)

**Comment by jordanrzymski** [comment]
> JRE is the Java Runtime Environment, it does not include a compiler.
> 
> You need the JDK: Java Development Kit.
> 
> You can install a JDK from a lot of sources. Here is one: https://adoptopenjdk.net

this fixed my android build after and up grade to bug sur  - just in case someone is looking for this answer

**Comment by DuCouscous** [comment]
I have jdk 1.8, for making 1.8.9 mods, but build fail too for 
"Execution failed for task ':compileJava'.
> Could not find tools.jar"
I have JAVA_HOME(C:\Program Files\Java\jdk1.8.0_281), I edited Path to add "%JAVA_HOME%\lib" but it always do that :(

**Comment by z7b** [comment]
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.utils.SynchronizedFile$ActionExecutionException: java.io.IOException: com.android.ide.common.signing.KeytoolException: Failed to create keystore.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 1s
Exception: Gradle task assembleDebug failed with exit code 1

```
```

**Comment by ayan383** [comment]
> @dikokob, I had the same problem. I just had to modify my JAVA_HOME to point to the jdk instead of the jre: `SET JAVA_HOME=C:\Program Files\Java\jdk-12.0.2`

where do u write that?

**Comment by Sunilkumarchoudari** [comment]
To Solve ERROR: Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_151 contains a valid JDK installation Error You Just need to add java home JDK path in gradle.properties Just like this: org.gradle.java.home=C:\\Program Files\\Java\\jdk1.8.0_144 Then try to rebuild project. Now your error must be solved. Second solution is You just need to add tools.jar file to C:\Program Files\Java\jre1.8\lib this Path. First of all Copy tools.jar file from C:\Program Files\Java\jdk1.8.0_121\lib and then Paste in C:\Program Files\Java\jre1.8\lib Here. Now your error must be solved

**Comment by ASHU9827** [comment]
jdk1.8 does not contained the tools.jar file go to the other versions.

**Comment by niyamk** [comment]
> jdk1.8 does not contained the tools.jar file go to the other versions.

can u tell me how to do that?

**Comment by niyamk** [comment]
> To Solve ERROR: Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_151 contains a valid JDK installation Error You Just need to add java home JDK path in gradle.properties Just like this: org.gradle.java.home=C:\Program Files\Java\jdk1.8.0_144 Then try to rebuild project. Now your error must be solved. Second solution is You just need to add tools.jar file to C:\Program Files\Java\jre1.8\lib this Path. First of all Copy tools.jar file from C:\Program Files\Java\jdk1.8.0_121\lib and then Paste in C:\Program Files\Java\jre1.8\lib Here. Now your error must be solved

but there is no tools.jar file.Can u please help me am trying to solve this error from 2 days

**Comment by TanishaShrotriya96** [comment]
Thanks for this solution, it worked for me with randoop 4.2.5
