### ISSUE TITLE
Resources missing ID

### ISSUE THREAD

**Issue by laurendukes** [synthetichealth/synthea#583]
I'm not sure whether this is the right place to file feedback, so please feel free to redirect.

In the Synthetic Mass dataset, some files have Resources that do not have IDs. For example, from `Abbott44_Barrett268_50.json`:

```
{
      "resource": {
        "status": "in-progress",
        "description": {
          "text": "Hemoglobin A1c total in Blood < 7.0"
        },
        "addresses": [
          {
            "reference": "urn:uuid:5d69edd0-f0d4-44f7-bf28-b470f2c61289"
          }
        ],
        "resourceType": "Goal"
      }
    },
```

Is this resolved in the current version of Synthea, and is there any plan to update the Synthetic Mass dataset to bring it up to standard and fix other validation errors perhaps fixed in https://github.com/synthetichealth/synthea/pull/240 ? Thanks!

**Comment by jawalonoski** [comment]
The Goal ids should be fixed in the latest version of the code.

We occasionally post updated data in the downloads section of SyntheticMass https://synthea.mitre.org/downloads, but for now, we have no plans to update the data that is available through the FHIR API.

**Comment by fhirfly** [comment]
The references in the Synthea data are all off.  This is causing errors on FHIR servers where references are checked.  Can I help fix this?

**Comment by jawalonoski** [comment]
> The references in the Synthea data are all off. This is causing errors on FHIR servers where references are checked. Can I help fix this?

Possibly, yes.

Are you using the downloads or generating data locally from the latest code?

Please describe the reference errors you are experiencing.
