### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#59]
At the bottom of the [wiki home page](https://github.com/synthetichealth/synthea/wiki) there is a broken link back to the synthea repository. In the ["Guide to Synthea Projects"](https://github.com/synthetichealth/synthea/wiki#guide-to-synthea-projects) section the link is currently:

https://github.com/synthethichealth/synthea

Note the typo: "**synthethic**health".

**Comment by jawalonoski** [comment]
Fixed. Next time, just fix it. No need to report the issue.
