### ISSUE TITLE
health data

### ISSUE THREAD

**Issue by Abd-A-M** [synthetichealth/synthea#595]
I need to know if you can provide me with medical data about 50,000 patient with specific attributes; attribute like diabetes, stroke, hypertension.....

**Comment by shabiel** [comment]
You should be able to generate 50,000 yourself by cloning or
downloading the synthea source code and running ./run_synthea -p
50000.

--Sam

**Comment by jawalonoski** [comment]
You can also download pregenerated data sets here: https://synthea.mitre.org/downloads
