### ISSUE TITLE
Alive-Dead Status Issue in Synthea

### ISSUE THREAD

**Issue by bainchri** [synthetichealth/synthea#603]
![Synthea_Debug_1](https://user-images.githubusercontent.com/56910694/67614141-0987dd00-f803-11e9-9ac3-857f21d623a1.PNG)

Hi ... am new to Synthea .... and just as a user 

..... most things are "working" .... and I can get SOME outputs in the output folder 

But I have this persistent Java error  seemingly in relation to the assigned "Alive-Dead" status of the patients when they are being generated (Please see attached pic) 

Anyone have any suggestions as to why ? Is it a known issue ?

Many thanks in advance 

Chris

**Comment by dehall** [comment]
There was an issue with the jar file not working correctly on Windows last week but that should be resolved now -- could you re-download the jar file and try it again? 
https://synthetichealth.github.io/synthea/build/libs/synthea-with-dependencies.jar

**Comment by bainchri** [comment]
Thanks dehall ... indeed ....reinstalled  jar and it did work at least in generating accurate number of JSON output files (I went to 10K patients). Much appreciated  

Got another issue issue but will explore  more first before raising
