### ISSUE TITLE
Population size max number

### ISSUE THREAD

**Issue by albamoralest** [synthetichealth/synthea#605]
Hi!

I am generating health records, but I would like to generate a big sample. Which is the maximum number of population it could generate? (living patients) is it any restriction?

**Comment by dehall** [comment]
No individual run of Synthea can produce more than 2147483647 patients (that's over 2 billion), but you can certainly run multiple times using different seeds to produce a larger aggregate patient set if that's not enough. 
If you're using FHIR or CCDA each patient record can be up to several MB in size, especially for older patients that have a lifetime of medical history, so be aware that the storage requirements for large patient datasets is very substantial. As one data point, we recently generated a population of roughly 6 million patients, and the FHIR data is nearly 20 TB uncompressed.

**Comment by albamoralest** [comment]
Thank you for your reply. Excuses if my next question is a bit silly. The seed number could be any random value? or is it specified in a file?

**Comment by dehall** [comment]
The seed is a number that is used to setup the randomness in the simulation. The idea is that using the same seed means the same numbers always get picked in the same order, so in a simulation like Synthea, using the same seed and all the same settings for 2 runs means you get 2 identical populations. In your case I mention the seed just to make sure you don't specify the same seed twice and then get the same population twice. 

You can either specify a seed using the `-s` flag, and yes it's allowed to be any random value, or if you don't specify one synthea will pick one automatically based on the current time in milliseconds, so if you run 2 in a row they will have different seeds.
Ex,
```
java -jar synthea-with-dependencies.jar -s 12345
or
run_synthea -s 12345
```
