### ISSUE TITLE
Providers CSV exports UUIDs with duplicates

### ISSUE THREAD

**Issue by SimonUzL** [synthetichealth/synthea#608]
Hello, it seems that even with a small population of 10 that the id of some providers is not unique in the csv export. Is this possibly the line of code that is the cause for that
https://github.com/synthetichealth/synthea/blob/bcb17a9532645f03f6410b7d5cf67092592842e7/src/main/java/org/mitre/synthea/world/agents/Provider.java#L476
or am I doing something wrong?

**Comment by JLMoszkowicz** [comment]
I am also seeing duplicates in the providers table in the pre-generated CSV files that are available for download here: https://storage.googleapis.com/synthea-public/synthea_sample_data_csv_sep2019.zip
