### ISSUE TITLE
Hourly measurements

### ISSUE THREAD

**Issue by andreluizbnu** [synthetichealth/synthea#618]
Hello guys.

Is it possible to generate hourly measurements?
I would like to generate the data within a 24 hours period to display in a graph or something.

As far as i saw, this is not possible using Synthea.
Correct me if I'm wrong.

Thanks in advance.

**Comment by jawalonoski** [comment]
Yes, this is possible.

You can create a module (with the [module builder](https://synthetichealth.github.io/module-builder/) if you prefer) that has, for example, an inpatient encounter. Just make an observation (looping with a counter, if you like) with a Delay state of 1 hour (or whatever resolution you want) between measurements.

https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#delay

Valid units of time are "years", "months", "weeks", "days", "hours", "minutes", and "seconds".

**Comment by andreluizbnu** [comment]
Great, thats what i'll do.
Thanks.

**Comment by andreluizbnu** [comment]
I created a new module based on your instruction in the Module Builder.
Am I missing something?

`{
  "name": "trending-graphs",
  "remarks": [
    "A blank module"
  ],
  "states": {
    "Initial": {
      "type": "Initial",
      "direct_transition": "Starting Values"
    },
    "Terminal": {
      "type": "Terminal"
    },
    "Minimum Age for Analysis": {
      "type": "Guard",
      "allow": {
        "condition_type": "Age",
        "operator": ">",
        "quantity": 40,
        "unit": "years"
      },
      "direct_transition": "Patient Hospitalization"
    },
    "Patient Hospitalization": {
      "type": "Encounter",
      "codes": [],
      "encounter_class": "inpatient",
      "remarks": [
        "Aaq"
      ],
      "direct_transition": "Record_BP"
    },
    "Record_BP": {
      "type": "MultiObservation",
      "category": "vital-signs",
      "codes": [
        {
          "system": "LOINC",
          "code": "55284-4",
          "display": "Blood Pressure"
        }
      ],
      "observations": [
        {
          "category": "vital-signs",
          "codes": [
            {
              "system": "LOINC",
              "code": "8480-6",
              "display": "Systolic Blood Pressure"
            }
          ],
          "unit": "mm[Hg]",
          "range": {
            "low": 40,
            "high": 150
          }
        },
        {
          "category": "vital-signs",
          "codes": [
            {
              "system": "LOINC",
              "code": "8462-4",
              "display": "Diastolic Blood Pressure"
            }
          ],
          "unit": "mm[Hg]",
          "range": {
            "low": 30,
            "high": 120
          }
        }
      ],
      "direct_transition": "Hourly Measurement"
    },
    "Hourly Measurement": {
      "type": "Delay",
      "exact": {
        "quantity": 1,
        "unit": "hours"
      },
      "direct_transition": "Increment Total"
    },
    "Increment Total": {
      "type": "Counter",
      "attribute": "delay_counter",
      "action": "increment",
      "conditional_transition": [
        {
          "transition": "Patient Discharge",
          "condition": {
            "condition_type": "Attribute",
            "attribute": "delay_counter",
            "operator": ">",
            "value": 24
          }
        },
        {
          "transition": "Record_BP"
        }
      ]
    },
    "Patient Discharge": {
      "type": "EncounterEnd",
      "direct_transition": "Terminal"
    },
    "Starting Values": {
      "type": "SetAttribute",
      "attribute": "delay_counter",
      "direct_transition": "Minimum Age for Analysis",
      "value": 1
    }
  }
}`

**Comment by jawalonoski** [comment]
Yes, the Encounter code is required.

```json
{
  "name": "trending-graphs",
  "remarks": [
    "A blank module"
  ],
  "states": {
    "Initial": {
      "type": "Initial",
      "direct_transition": "Starting Values"
    },
    "Terminal": {
      "type": "Terminal"
    },
    "Minimum Age for Analysis": {
      "type": "Guard",
      "allow": {
        "condition_type": "Age",
        "operator": ">",
        "quantity": 40,
        "unit": "years"
      },
      "direct_transition": "Patient Hospitalization"
    },
    "Patient Hospitalization": {
      "type": "Encounter",
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": "1234",
          "display": "SNOMED Code"
        }
      ],
      "encounter_class": "inpatient",
      "remarks": [
        "Aaq"
      ],
      "direct_transition": "Record_BP"
    },
    "Record_BP": {
      "type": "MultiObservation",
      "category": "vital-signs",
      "codes": [
        {
          "system": "LOINC",
          "code": "55284-4",
          "display": "Blood Pressure"
        }
      ],
      "observations": [
        {
          "category": "vital-signs",
          "codes": [
            {
              "system": "LOINC",
              "code": "8480-6",
              "display": "Systolic Blood Pressure"
            }
          ],
          "unit": "mm[Hg]",
          "range": {
            "low": 40,
            "high": 150
          }
        },
        {
          "category": "vital-signs",
          "codes": [
            {
              "system": "LOINC",
              "code": "8462-4",
              "display": "Diastolic Blood Pressure"
            }
          ],
          "unit": "mm[Hg]",
          "range": {
            "low": 30,
            "high": 120
          }
        }
      ],
      "direct_transition": "Hourly Measurement"
    },
    "Hourly Measurement": {
      "type": "Delay",
      "exact": {
        "quantity": 1,
        "unit": "hours"
      },
      "direct_transition": "Increment Total"
    },
    "Increment Total": {
      "type": "Counter",
      "attribute": "delay_counter",
      "action": "increment",
      "conditional_transition": [
        {
          "transition": "Patient Discharge",
          "condition": {
            "condition_type": "Attribute",
            "attribute": "delay_counter",
            "operator": ">",
            "value": 24
          }
        },
        {
          "transition": "Record_BP"
        }
      ]
    },
    "Patient Discharge": {
      "type": "EncounterEnd",
      "direct_transition": "Terminal"
    },
    "Starting Values": {
      "type": "SetAttribute",
      "attribute": "delay_counter",
      "direct_transition": "Minimum Age for Analysis",
      "value": 1
    }
  }
}
```

I added a SNOMED code of 1234 (obviously, that doesn't really exist), tested the module, and it works as expected. Just note that by default Synthea only exports the last 10 years of data, so the data might not show up in everyone's record.

**Comment by andreluizbnu** [comment]
Nice!

It works like I expected.
Thanks for the answers and nice work with Synthea!
