### ISSUE TITLE
simple example of generating one patient with several temperature observations

### ISSUE THREAD

**Issue by adrian-herscu-ge** [synthetichealth/synthea#625]
I am amazed about the richness and amount of options in this tool :)

However, after one day of digging through the documentation I am still not sure whether it fits my use case.

For a start, I need to understand whether it is possible to generate just one Patient with several temperature Observations. How can I control the amount the generated Observations, their value range, their units ?... Am I expecting the right thing from this tool? Or, should I look into something else?

**Comment by jawalonoski** [comment]
Thanks @adrian-herscu-ge -- we hope it helps!

You can generate a single patient by running `./run_synthea -p 1` (if you cloned the repo) or `java -jar synthea-with-dependencies.jar -p 1` (if you downloaded the JAR).

The clinical data (e.g. Observations, values, units of measure) that is written into the patient record is a direct result of the disease models that are being executed. You can read more about the [models and how they work on our Wiki](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework) or browse and edit the models with the online [Module Builder](https://synthetichealth.github.io/module-builder/).

If you aren't seeing the data that you want, you may want to edit an existing model or create a new one. You can try pasting the JSON below into the module builder to see what it _might_ look like, or you can edit the existing wellness encounter model.

After editing or reviewing the model, drop it into the local module folder following these [instructions](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Running-New-Modules).

**Example Body Temperature Module**

Copy and paste this into the module builder JSON tab.

```json
{
  "name": "Body Temperature",
  "remarks": [
    "This example module adds a body temperature reading to every wellness encounter.",
    ""
  ],
  "states": {
    "Initial": {
      "type": "Initial",
      "direct_transition": "Encounter State"
    },
    "Encounter State": {
      "type": "Encounter",
      "reason": "",
      "direct_transition": "Take Temperature",
      "wellness": true
    },
    "Take Temperature": {
      "type": "Observation",
      "category": "vital-signs",
      "unit": "Cel",
      "codes": [
        {
          "system": "LOINC",
          "code": "8310-5",
          "display": "Body temperature"
        },
        {
          "system": "LOINC",
          "code": "8331-1",
          "display": "Oral temperature"
        }
      ],
      "direct_transition": "Wait Until Next Time",
      "range": {
        "low": 36,
        "high": 38
      }
    },
    "Wait Until Next Time": {
      "type": "Delay",
      "exact": {
        "quantity": 1,
        "unit": "days"
      },
      "direct_transition": "Encounter State"
    }
  }
}
```

**Comment by adrian-herscu-ge** [comment]
Thanks for the fast reply :)
I am still missing something... Now I am getting an NPE.
Besides, it still appears to find all other modules somewhere -- below is the output.
From where these all 60 modules come from?

Well... found an workaround.... I put my module into the `build\resources\main\modules` directory, run without the `-d` parameter and now it works. 

However, I am still getting three Organizations, three Practitioners, Claims, CarePlan, Goal, ExplanationOfBenefits, Encounters, MedicationRequests, Conditions... oh my god!!!
From where all these came? Have I asked for these? Is it possible to suppress these?

Then, there are Observations, which is really the thing that I am trying to generate.
Now I am finding "Body Mass Index", "Blood Pressure", "Tobacco smoking status NHIS" -- all-in-all there are 105 Observations, among these 10 "Body temperature", and 1 "Oral temperature".

Is it possible to generate just one Patient with exactly X specific Observations and nothing else?
Perhaps there is a lower level tool better suited for such tasks? I found that MDHT is used inside. Should I look into it?


```
C:\projects\synthea>run_synthea -p 1 -d modules
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run
Scanned 60 modules and 36 submodules.
Scanned 1 local modules and 0 local submodules.
Loading submodule modules\breast_cancer\tnm_diagnosis.json
Loading submodule modules\allergies\allergy_incidence.json
Loading submodule modules\dermatitis\moderate_cd_obs.json
Loading submodule modules\dermatitis\severe_cd_obs.json
Loading submodule modules\contraceptives\female_sterilization.json
Loading submodule modules\allergies\outgrow_env_allergies.json
Loading submodule modules\lung_cancer\lung_cancer_probabilities.json
Loading submodule modules\contraceptives\patch_contraceptive.json
Loading submodule modules\allergies\allergy_panel.json
Loading submodule modules\breast_cancer\surgery_therapy_breast.json
Loading submodule modules\allergies\severe_allergic_reaction.json
Loading submodule modules\dermatitis\early_severe_eczema_obs.json
Loading submodule modules\total_joint_replacement\functional_status_assessments.json
Loading submodule modules\contraceptives\ring_contraceptive.json
Loading submodule modules\anemia\anemia_sub.json
Loading submodule modules\medications\otc_pain_reliever.json
Loading submodule modules\breast_cancer\hormone_diagnosis.json
Loading submodule modules\medications\ear_infection_antibiotic.json
Loading submodule modules\medications\strong_opioid_pain_reliever.json
Loading submodule modules\allergies\immunotherapy.json
Loading submodule modules\dermatitis\mid_moderate_eczema_obs.json
Loading submodule modules\contraceptives\clear_contraceptive.json
Loading submodule modules\surgery\general_anesthesia.json
Loading submodule modules\veterans\veteran_suicide_probabilities.json
Loading submodule modules\contraceptives\oral_contraceptive.json
Loading submodule modules\medications\moderate_opioid_pain_reliever.json
Loading submodule modules\medications\otc_antihistamine.json
Loading submodule modules\dermatitis\mid_severe_eczema_obs.json
Loading submodule modules\dermatitis\early_moderate_eczema_obs.json
Loading submodule modules\contraceptives\intrauterine_device.json
Loading submodule modules\contraceptives\male_sterilization.json
Loading submodule modules\contraceptives\implant_contraceptive.json
Loading submodule modules\breast_cancer\hormonetherapy_breast.json
Loading submodule modules\contraceptives\injectable_contraceptive.json
Loading submodule modules\allergies\outgrow_food_allergies.json
Loading submodule modules\breast_cancer\chemotherapy_breast.json
Loading module modules\opioid_addiction.json
java.lang.NullPointerException
        at org.mitre.synthea.engine.Module.lambda$null$2(Module.java:90)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:344)
        at org.mitre.synthea.engine.Module.lambda$getModules$5(Module.java:170)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.mitre.synthea.engine.Module.getModules(Module.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:214)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:354)
        at org.mitre.synthea.engine.Module.lambda$getModules$5(Module.java:170)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.mitre.synthea.engine.Module.getModules(Module.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:214)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Caused by: java.lang.NullPointerException
        at org.mitre.synthea.engine.Module.lambda$null$2(Module.java:90)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:344)
        ... 6 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_192\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
4 actionable tasks: 4 executed

C:\projects\synthea>
```

**Comment by jawalonoski** [comment]
> Is it possible to generate just one Patient with exactly X specific Observations and nothing else?

Synthea is bundled with lots of built-in disease modules, which accounts for all the data you are seeing.

You can run only your module using the `-m` parameter and `-p 1` for a single patient, but Synthea isn't designed to do what you want. 

The primary goal of the project is to generate electronic health records, which generally contain more information than a single patient and a handful of observations.

> I found that MDHT is used inside. Should I look into it?

MDHT is used in this project to support the HL7 CDA standard. It may have other uses, but as far as we know, generating synthetic data is not one of them.
