### ISSUE TITLE
Edge weights

### ISSUE THREAD

**Issue by pratiklalwani** [synthetichealth/synthea#634]
Hi, I want to assign weights to edges with recurring visits by the same patient ID however I am not able to link the recurring visits with patient ID. Please advise.

**Comment by jawalonoski** [comment]
Are you saying that you want the transition probabilities to change based on how many times the same patient already followed a given path?

If so, it sounds like you want to use a Complex Transition (https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Transitions#complex) coupled with a Counter state (https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#counter).
