### ISSUE TITLE
Generating a training set for a symptom checker

### ISSUE THREAD

**Issue by alexissmirnov** [synthetichealth/synthea#639]
Hello,

Would it be appropriate to consider synthea as a basis for the system that would generate a dataset to train a model for a symptom checker system?

The symptom checker system collects findings from the patient and predicts a differential diagnosis. The training dataset needs to include patients with specific conditions (disorders) and symptoms (findings). All conditions and symptoms would have to have a SNOMED code, so that the name finding can correspond to different disorders.

The existing modules already express the relationship between conditions and symptoms, so it would appear that this project could be extended to be used for this use-case.

If this use-case makes sense, what would be the best way to extend the system to support it?

**Comment by jawalonoski** [comment]
Well, as described in #638, symptoms are not recorded in the EHR. That could theoretically be changed by either recording the text description of the symptom in a note, or adding enough information that they can be encoded as observations or conditions.

So, if symptoms were recorded, you could use the output data to train a model. However, it would be an academic or educational exercise only, the model would not be useful in a real-world operational setting.

**Comment by alexissmirnov** [comment]
In order to create a training set for a symptom checker, one would need to have symptoms appear in the training set as structured data, eg. as SNOMED expressions as opposed to text notes. Encoding them as observations is a great idea. Can an observation that can be coded with SNOMED that that code would be serialized in the output?

If it does make sense to extend synthea along this direction, then the the steps would be to create generic modules that fully define symptoms (observations) and their possible presentations for the disorders that the symptom checker would understand.

Would you see this as a feasible/useful extension to this project:
- allow modules express observations as SNOMED expressions (instances of Clinical Finding class, with attributes). If a "symptom" isn't the right concept, perhaps "observation" can be mapped to SNOMED's nodes in "Clinical observation" hierarchy)
- output SNOMED-coded symptoms/observations/findings, so the training set can be created
- develop a potentially large number of generic modules that express Onset Condition (SNOMED's Disease(disorder) ) and associated symptoms/observations/findings

Does this make sense? Or this idea is pushing this project into a different direction from where it's going?

**Comment by jawalonoski** [comment]
> Can an observation that can be coded with SNOMED that that code would be serialized in the output?

Yes. Traditionally in Synthea, if you want to use _only_ a SNOMED code, then you use [ConditionOnset](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#conditiononset) states. 

If you want to represent a "_question and answer_" or "_name-value pair_" then you use [Observation](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#observation) states. Today, the way Synthea is written, observation requires a LOINC code as the "_question_" or "_name_", but the "_answer_" or "_value_" can be some quantity (e.g. a number with units of measurement) or a SNOMED code.

If you want to do something else with observations, the system cannot support it, and it would probably take some work.

> Does this make sense? Or this idea is pushing this project into a different direction from where it's going?

I don't know. I'm not sure how common this paradigm or behavior is in the real-world. There is a dormant and dated (but not dead) pull request to use Value Sets that we to plan to rebase and reevaluate sooner or later. See issues #347 and #403 and pull request #380.

**Comment by alexissmirnov** [comment]
Ok, thanks for the context. 

Would you accept a PR to extend Observation to support SNOMED as `system` for the `codes` attribute, in addition to LOINC? 
To represent a clinical finding What would `category` be set to, to represent an Observation in the form of "question and answer"?

**Comment by jawalonoski** [comment]
> What would category be set to, to represent an Observation in the form of "question and answer"?

I did not mean a literal "_Q&A_", I meant it figuratively. That being said, if you did have a literal Q&A you could use `survey`.

> Would you accept a PR to extend Observation to support SNOMED as system for the codes attribute, in addition to LOINC?

To be honest, I'm not sure. I'm hesitant, but I could be persuaded. Technically, FHIR allows for SNOMED to be used in `Observation.code` but I have never seen it in practice or in Implementation Guide (IG) profiles. If you have any examples that use SNOMED or profiles that require a SNOMED binding, please share. An IG in particular would make me much more willing. Also, if this change was made, corresponding changes would need to be made in the [Module Builder](https://github.com/synthetichealth/module-builder).

**Comment by alexissmirnov** [comment]
Thanks again! I'm still learning, so don't feel qualified to persuade you about this :)

It seems that to fully define the observation one would need to specify both the LOINC code (the question) and the SNOMED expression (the answer). To quote https://loinc.org/faq/loinc-and-other-standards/ "LOINC provides codes for the question while SNOMED provides codes for the answers"

In terms of the implementation guidance, it seems the advice from both LOINC and SNOMED is similar 
For vital signs: Use LOINC to identify the vital sign observable. Use SNOMED CT for vital sign coded result values. Reference: https://danielvreeman.com/guidelines-for-using-loinc-and-snomed-ct-together-without-overlap/ 

Based on this, it seems that the observation would need to include both a LOINC code (to define what we're observing) and a SNOMED expression (to define the value of the observation)
 
For example, to model the following part of the examination:
System: "How is your heart rate?"
Patient: "Very fast"
```
"Observation_123": {
  "type": "Observation",
  },
  "codes": [
    {
      "system": "LOINC",
      "code": "8867-4",
      "display": "Heart Rate"
    },
    {
      "system": "SNOMED",
      "code": "3424008",
      "display": "Tachycardia (finding)"
    }
  ]
}
```

The example I'm thinking about is a set of generic modules that would make sytnthea produce training set for a symptom checker. We already have a large structured KB of odds-ratios (probabilities) of findings given a specific disorder, so we'd be able to create those generic modules. From this perspective, there's really no need to use both SNOMED and LOINC because the primary use-case isn't interoperability and it is simpler to just use one standard everything, and SNOMED's "Observable entity" concept seems to be expressive enough.

**Comment by jawalonoski** [comment]
Based on the sources you linked, I believe the module state should use the `codes` (the question) and `value_code` (the answer) fields, which would look like this:

```json
    "Example": {
      "type": "Observation",
      "category": "vital-signs",
      "codes": [
        {
          "system": "LOINC",
          "code": "8867-4",
          "display": "Heart Rate"
        }
      ],
      "value_code": {
        "system": "SNOMED-CT",
        "code": 3424008,
        "display": "Tachycardia (finding)"
      }
    }
```

The module builder and Synthea support the above example already. Your second example -- which is currently unsupported -- would become:

```json
    "Example": {
      "type": "Observation",
      "category": "vital-signs",
      "codes": [
        {
          "system": "SNOMED",
          "code": "364075005",
          "display": "Heart rate (observable entity)"
        }
      ],
      "value_code": {
        "system": "SNOMED-CT",
        "code": 3424008,
        "display": "Tachycardia (finding)"
      }
    }
```

**Comment by teliov** [comment]
Hi @jawalonoski , following up on this thread especially with the idea of using Observations to encode the symptoms.

In theory, assuming that a database with conditions and a probabilistic model of its symptoms is available, it should be possible to construct synthea generic modules that use the conditional logic and transitions to capture the probabilistic distribution of the symptoms and encode them using Observations right?

With this particular approach, since the aim is to get patients who have the modeled conditions and present the corresponding symptoms, it might not be necessary to have "target encounters" specifically for diagnosis for instance. Also symptoms could be completely replaced by the Observations. 

Will the absence of symptoms for instance affect the way Synthea models the patients and the conditions ? (In this case emphasis is mainly on the patients, the conditions and the observations aka "symptoms")

**Comment by jawalonoski** [comment]
@teliov 

> In theory, assuming that a database with conditions and a probabilistic model of its symptoms is available,

Such datasets do exist.

> it should be possible to construct synthea generic modules that use the conditional logic and transitions to capture the probabilistic distribution of the symptoms and encode them using Observations right?

Correct.

>  it might not be necessary to have "target encounters" specifically for diagnosis for instance.

Correct. Target encounter is not a required field in the modules, it is only used if you specifically want diagnosis to happen in a specific encounter. Otherwise, it can be ignored.

> Also symptoms could be completely replaced by the Observations.

Words have many meanings, so I want to be precise. In Synthea, `Symptoms` drive patient behavior. As symptoms accumulate, a patient will seek medical care. On the other hand, `Observations` are what the clinicians actually record. An observation may be a symptom, but it could also be a measurement or lab value, or answer to a question (e.g. "_is the patient homeless?_").

> Will the absence of symptoms for instance affect the way Synthea models the patients and the conditions ?

No.

Hope that helps.

**Comment by alexissmirnov** [comment]
Thanks @jawalonoski (FYI @teliov and I had an offline discussion on this topic and we have a shared interest in this use-case)

> `Observations` are what the clinicians actually record.
This makes sense and better represents our use-case, because we'd want the system to ask specific questions of the patient, answer to which may or may not be a symptom.

> Such datasets do exist.

We see that some published papers in this area use http://www.symcat.com/symptoms and http://www.symcat.com/conditions

Can you refer to other accessible databases we could look at, that link findings to disorders in a probabilistic graph model?

**Comment by jawalonoski** [comment]
I don't have a list of these datasets, but here is one I was recently looking at: https://github.com/clinicalml/HealthKnowledgeGraph/blob/master/DerivedKnowledgeGraph_final.csv

**Comment by jawalonoski** [comment]
Symptom data can now be exported (without terminology codes) with the merging of PR #685
