### ISSUE TITLE
providing seed to CLI generates data with slight inconsistencies

### ISSUE THREAD

**Issue by ethnhll** [synthetichealth/synthea#657]
Providing a seed value to the command-line interface does not produce completely consistent results between invocations. The differences in output appear to be related to UUIDs, URLs, start and end dates (for periods for example), etc.
While relatively minor compared to the rest of the output generated which is consistent, it makes testing that would require perfect consistency between invocations difficult.

```bash
java -jar synthea-with-dependencies.jar -s 42 -p 2
mv output/ output-1/
java -jar synthea-with-dependencies.jar -s 42 -p 2
diff  -qr output-1/fhir/ output/fhir/
```
The above shows diffs between all files.

This was run on MacOS Mojave, using Synthea v2.5.0 downloaded as a jar.

**Comment by jawalonoski** [comment]
Yes, this is a known issue.

The dates vary because the reference point for the dates is the current system time you are running the simulation. The way to fix that would be to freeze the reference point (e.g. `01-JAN-2020`) or make that an input parameter.

On the other hand, the UUID and URL variation are a result of using `UUID.randomUUID()` to generate identifiers. UUID uses the system time. It is possible to use `UUID.nameUUIDFromBytes(bytes)` where pseudo-random `bytes` come from using `Person.random`.

**Comment by ethnhll** [comment]
>The dates vary because the reference point for the dates is the current system time you are running the simulation. The way to fix that would be to freeze the reference point (e.g. 01-JAN-2020) or make that an input parameter.
Can you point me to where this happens in the code?

Is there a plan for a fix for this in the works already? If not, I'd be happy to take a stab at it

**Comment by jawalonoski** [comment]
> Is there a plan for a fix for this in the works already?

No.

> If not, I'd be happy to take a stab at it

Please. Give it a shot.

**Comment by jawalonoski** [comment]
> Can you point me to where this happens in the code?

https://github.com/synthetichealth/synthea/blob/0719985b48c84db8e80109f235c294547678df96/src/main/java/org/mitre/synthea/engine/Generator.java#L186

As for the UUIDs, just search for "UUID" throughout the src folder. It is littered around in a lot of places. The URLs are based on the UUIDs, so once you fix the UUIDs, the URLs will probably be all set.

**Comment by ethnhll** [comment]
alright, I'll give it a shot then, thank you!

**Comment by jawalonoski** [comment]
This should be fixed now, if you supply a `seed`, `clinician seed`, and `reference date`.

E.g.

```
./run_synthea -s 0 -cs 0 -r 2020607
```
