### ISSUE TITLE
classes compiled with Java12, can't use as library with Java8

### ISSUE THREAD

**Issue by ethnhll** [synthetichealth/synthea#658]
When using Synthea as a library, execution fails with:
```java
/Users/testuser/projects/synthea-test/src/main/java/TestSynthea.java:1: error: cannot access Generator
import org.mitre.synthea.engine.Generator;
                               ^
  bad class file: /Users/testuser/.gradle/caches/modules-2/files-2.1/org.mitre.synthea/synthea/2.5.0/74637dbf5e258231a75cb80ebf45090b0bda5565/synthea-2.5.0.jar(org/mitre/synthea/engine/Generator.class)
    class file has wrong version 56.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Example code I used to get this output:
```java
// file:///Users/testuser/projects/synthea-test/src/main/java/TestSynthea.java
import org.mitre.synthea.engine.Generator;

public class TestSynthea {
    public static void main(String[] args) {
        Generator.GeneratorOptions options = new Generator.GeneratorOptions();
        options.population = 10;
        Generator generator = new Generator(options);
        generator.run();
    }
}
```
And here is my `build.gradle`
```groovy
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.mitre.synthea:synthea:2.5.0'
}
```
Additionally, here is my java compiler info, gradle info, and OS
```bash
>>> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G95)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      [...]

>>> java -version  
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

>>> gradle --version

------------------------------------------------------------
Gradle 6.1
------------------------------------------------------------

Build time:   2020-01-15 23:56:46 UTC
Revision:     539d277fdba571ebcc9617a34329c83d7d2b259e

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_232 (AdoptOpenJDK 25.232-b09)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by jawalonoski** [comment]
We could alter the gradle build file to specifically target JDK 8.

See https://docs.gradle.org/current/userguide/building_java_projects.html and the `sourceCompatibility` and `targetCompatibility` options.

In the meantime, do not compile with a newer version of the JDK than what you want to execute with.

**Comment by ethnhll** [comment]
When compiling the project locally using Java8, the project has no issue.
This happens with the jar coming from Mavencentral, when trying to use Synthea as an "SDK" so to speak. No compilation is being done at that point on my end.

**Comment by irjudson** [comment]
+1 this is an embedding issue, the sample code fails to compile with the provided pom.xml and code with JDK 1.8.

**Comment by amohajerani** [comment]
Hi everyone, are there any plans to make Synthea compatible with current version of JDK?

**Comment by hadleynet** [comment]
This issue was closed with a fix. Are you seeing an error?

**Comment by amohajerani** [comment]
Hi @hadleynet , thanks for quick note. I don't see an error. I am not reporting an issue. I just had a questions, and I was not sure where I should ask, so I put it here. Sorry about confusion.
I am just wondering if there are any plans to make Synthea compatible with the current version (v. 16) of JDK.

Thanks

**Comment by hadleynet** [comment]
Our CI tests run on both Java 8 and Java 16 so everything should be good with the latest JDK. Let us know if you run into issues.
