### ISSUE TITLE
ear_infections generates encounters before birthdate

### ISSUE THREAD

**Issue by adambozson** [synthetichealth/synthea#673]
I have generated a population of 10,000 patients only using the ear infections module:
```
./run_synthea -p 10000 -m ear_infections
```

A few hundred patients then have encounters that occur before their birthdate, e.g.
```
ENCOUNTER                2d600621-564e-4e9a-9278-2493289dd0c7
ENCOUNTER_START                          1943-01-30T22:58:14Z
ENCOUNTER_STOP                           1943-01-30T23:13:14Z
PATIENT                  a7f0cd4f-f70a-4e21-ab1f-6505b2c17bb6
ENCOUNTER_CODE                            SNOMED-CT_185345009
ENCOUNTER_DESCRIPTION                   Encounter for symptom
ENCOUNTER_START_TS                               -8.49496e+08
AGE                                                   -554954
```
where the patient looks like:
```
{'birthdate': '2006-05-23',
 'birthdate_timestamp': 1148338800.0,
 'deathdate': nan,
 'deathdate_timestamp': nan,
 'patient_id': 'a7f0cd4f-f70a-4e21-ab1f-6505b2c17bb6',
 'window_end_timestamp': 1581516000.0}
```
i.e. this person born in 2006 has an encounter in 1943. This doesn't happen when running Synthea with all modules, nor does it happen when running with e.g. `-m asthma` or `-m metabolic*`.

Also, the UUIDs for encounters and patients are not consistent between CSV and FHIR outputs. I'm not sure if this is related.

**Comment by eedrummer** [comment]
@adambozson Thanks for taking the time to report this bug. 

I can replicate this on a set of 1000 patients running just the ear infections module. I had someone born in 2014 with an encounter in 2008. I'll take a look into what is going on.

**Comment by eedrummer** [comment]
@adambozson can you test again? We just merged a fix that should address your issue.

**Comment by adambozson** [comment]
@eedrummer Looks like this has solved the issue. I have run for 10k ear infections and confirmed that our tests pass. Thanks!
