### ISSUE TITLE
FHIR JSON has numbers in scientific notation?

### ISSUE THREAD

**Issue by gotdan** [synthetichealth/synthea#675]
I generated 100 patients with the default FHIR R4 JSON config and each has a couple of Observation resources in their bundle that have values that appear to be in scientific notation. This is valid JSON according to the spec, but is causing the Google FHIR server to reject the transactions. The example below is in the value for a systolic BP (the diastolic is correctly structured.) Can anyone else reproduce? Any thoughts on why this is occurring in only a few instances?
```
"valueQuantity": {
     "value": 1.2E+2,
    "unit": "mm[Hg]",
    "system": "http://unitsofmeasure.org",
   "code": "mm[Hg]"
}
```

**Comment by jawalonoski** [comment]
@gotdan thanks for the report.

After a quick check, it seems to happen when the value ends with a zero. e.g. `120`

**Comment by jawalonoski** [comment]
It might have to do with how we trim off excess precision here:

https://github.com/synthetichealth/synthea/blob/1f116ca29dfb57d0c9bc0feb867647a00418fa4f/src/main/java/org/mitre/synthea/export/FhirR4.java#L1534-L1540

Or it could be the JSON library underneath HAPI.

**Comment by jawalonoski** [comment]
Yes, it looks like `stripTrailingZeros()` is the culprit.

But that also does some other stuff for us...

For example, it would make sure `67.120` becomes `67.12`.

If we remove the `stripTrailingZeros()` we can lose that.

**Comment by hadleynet** [comment]
There's a BigDecimal.toPlainString method that would solve this problem but we would need the Quantity class to use that instead of toString.

**Comment by hadleynet** [comment]
Or we could subclass BigDecimal and override toString to call toPlainString instead.
