### ISSUE TITLE
Interest for the list of conditions and related symptoms

### ISSUE THREAD

**Issue by afansi** [synthetichealth/synthea#678]
Hi @jawalonoski, Thanks for the amazing work you are doing with the Synthea project.
As far as I understood, Synthea allows us to simulate a population life cycle  given demographic data while generating the EMR for each simulated person.
In my project, I am interested not in the EMR but in the list of conditions that a person has suffered from during his life together with the related symptoms. Also I want to take advantage of the Simulation power of Synthea and especially the Synthea Generic Modules.
Here is an example of a given module describing a pathology with the related symptom (please remove the txt extension to obtain a json file that cold be visualize easily with the framework): 
[abdominal-hernia_new.json.txt](https://github.com/synthetichealth/synthea/files/4314416/abdominal-hernia_new.json.txt)
After analyzing the code, it seems that Synthea does not support this functionality out of the box. Therefore, I am considering the following solution:
- Add the field `condition_symtoms` to the class `Person` of type Dict that would be indexed as follows: [age -> [condition -> [symptom -> value]]] where each bracket represents a dictionary.
- Modify the `set_symptom` function of the class `Person` to update the newly introduced field concurrently when the symptoms are created.
- Add an export flag that, when set, will allow me to dump the newly introduced field in a file (JSON, CSV) while taking care to not alter the EMR file generated so far.

Do you think the solution makes sense? If so, would it be possible to integrate back the solution as part of the Synthea code?

Regards,

**Comment by jawalonoski** [comment]
@afansi you are welcome.

Your idea makes sense.

Ideally, I would like to track symptoms on the patient with a single data structure, so if you want to make this change and contribute it back to the project, I would ask that you consider replacing the `Person.symptoms` and `Person.symptomsStatuses` objects and modifying the methods that access that data accordingly -- rather than add another data structure that duplicates the data.

Unless they serve completely different purposes, and we can't think of a resolution. Currently symptoms drive patient care-seeking behavior and they can be resolved -- they are transient. But it seems like you want a historical record.

One question that pops into mind -- how do you deal with symptoms across ages? A symptom I have now won't disappear just because I get a year older. You need some way to carry them forward.

Or symptoms within an age? What if I get a symptom at age 6, but it resolves when I'm still aged 6?

Also, as an alternative to age, you may want something to do with time of onset/resolution. Depends on how much detail you want in the tracking. But I don't feel strongly about that.

**Comment by afansi** [comment]
Hi @jawalonoski,

Thanks you for the feedback. The questions you raised made me think of a new way to approach the problem while using/modifying existing fields. In the following, I described a sketch of the proposed approach.

- Beacuse in Synthea, a `Condition` can be onset, but never be diagnosed (and thus, never be recorded in the EMR), I suggest to introduce a new field `onsetConditions` in the `Person` class that will keep track of all the conditions being onset for a given person. The type of the introduced field will be: `ConcurrentHashMap<String, Map<String, List<Pair<Long, Long>>>>()`. It will allow to store, for each module, the condition that will be onset together with the time the condition has been onset and, eventually, the time it ended. Here, we assume a general settin where a module could lead to several "types" of conditions be onset, and each of those conditions could occur more than once. 

- The field `symptoms` of the class `Person` will be altered to be of the type `Map<String, Map<String, Map<Long, Integer>>>()` to take into account the time a symptom is set, that is [Symptom, [Cause, [Time, Value]]]. Also, because the `Cause` is not currently used later on in any part of the code except for thing related to symptoms management, I propose to use `Module name` instead as it will allow me to make the conection with the previously introduced field.

- The field `symptomStatuses` of the class `Person` is left unchaged as if a symptom from a given cause is addressed, then the time it occurs does not matter.

- The `process` method of the `ConditionOnset` state is altered to update the introduced field in the current person being processed. This will create a new Pair initialized with the provided `time` as the begin of the condition. 

- The `setSymptom` method of the `Person` class is modified to take into account the `time` when the symptom is set.

- The `process` method of the `Symptom` state is modified to provide the `time` to the `Person.setSymptom` method calls. 

- The `process` method of the `ConditionEnd` state is altered to update the introduced field in the current person being processed. This will update the last pair in the list with the provided `time` as the time the condition ended. 

- As the `resetSymptoms` of the class `Person` is never used througout the project, I propose to remove it as we will not erase the recorded symptoms.

- At any point of time, the value associated to a `Symptom` caused by a given `Cause`/`Module` will be the value associated with the most recent time in the map. With this in mind, the methods `getSymptom`, `addressLargestSymptom` of the class `Person` will be modified accordingly. Futhermore, the methods `symptomTotal` and `getSymptoms` of the class `Person` will be left unchanged.

- Finally, I propose to add an export flag that, when set, will first aggregate the symptoms for each conditions the person suffered from using the saved `init_time` and `end_time` in the introduced field as well as the `time` information in the `symptoms` data structure, and then dump that information in a file (JSON, CSV) while taking care to not alter the EMR file generated so far. In the case there are several entries for a given symptoms/cause that fall within the `[init_time, end_time]` interval of a given condition, we will export the least recent one as it characterized the first value assocaited with that symptom when the condition did occur.

What do you think about the proposed approach? Do I have your "Go" fo implementing it?

Regards,

**Comment by jawalonoski** [comment]
@afansi Thanks for the thorough write up. Took me a while to find time to review it.

Your proposal looks good. Some things to consider:

- Any new export formats should default to being disabled.
- Once the pull request is merged, you'll have to add a page on the wiki that documents the export format.
- Please run the simulation with 1k or 10k patients before and after your changes and see what the performance impacts are. Could be minimal, but I am curious to see how this alters performance. Probably just a very minor memory impact.
- Last but not least, please add sufficient unit test coverage for the changes.

**Comment by afansi** [comment]
Thanks @jawalonoski . I am on it.

**Comment by malynome** [comment]
Hey @afansi , I'm also doing something related to symptoms, and its awesome to see you take the initiative! I know you probably have it all planned out, but if there is anything I can do to help, let me know - I definitely have an interest in this feature. 
Thanks in advance!

**Comment by afansi** [comment]
Hi @jawalonoski , the work is done on my side. I have included new unit tests as well as modifying existing ones for accounting to the modification made.

Also, regarding the performance, as suggested, I ran simulations with 1k or 10k patients before and after the changes I made. Here are the stats (all the simulations made csv exports as well as the default fhir exports):
- Before the change: 1k (1min 14s), 10k (9min 36s)
- After the change (but with the new export flag set to false): 1k (1min 15s), 10k (9min 35s) 
- After the change (but with the new export flag set to true): 1k (1min 16s), 10k (9min 28s)

Finally, I would like to push my modification and open a PR, but I do not have the permission yet. Would you please arrange that for me? Thanks in advance.

**Comment by afansi** [comment]
> Hey @afansi , I'm also doing something related to symptoms, and its awesome to see you take the initiative! I know you probably have it all planned out, but if there is anything I can do to help, let me know - I definitely have an interest in this feature.
> Thanks in advance!

Hi @malynome , glad to see that there is a real interest for that feature. The proposed solution is already implemented and I am in the process of opening a PR. You can definitely take advantage of it. 
Regards,

**Comment by jawalonoski** [comment]
@afansi You should be able to submit a PR using your fork. Looking forward to seeing it.

**Comment by afansi** [comment]
> @afansi You should be able to submit a PR using your fork. Looking forward to seeing it.

@jawalonoski I just opened the PR #685.
Regards,

**Comment by jawalonoski** [comment]
Resolved with the merging of #685
