### ISSUE TITLE
Differences between exports and across formats are inconsistent

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#682]
IDs consistency from run to run.

- Export FHIR using seed zero, and then again with seed zero. Do we get different resource IDs or other identifiers?
- IDs between CDA, FHIR, and CSV -- are they consistent? Nice for mapping.

Dates consistency from run to run.

- Two runs with seed zero, back to back, will produce different date timestamps in the data.

**Comment by dehall** [comment]
Can we close this with the recent changes to ID generation and reproducibility?
