### ISSUE TITLE
Provider foreign key in encounters table

### ISSUE THREAD

**Issue by tracyedinger** [synthetichealth/synthea#714]
Hello. I recently dowloaded the 1K sample synthetic patient records CSV (8 mb, Synthea_sampledata_csv_jan2020). When I join the encounters table to the provider table (encounter provider to provider ID), there are no matches. Is there an update to the provider or encounter CSV with matching providers?

**Comment by jawalonoski** [comment]
This has been fixed in the project, see https://github.com/synthetichealth/synthea/issues/547#issuecomment-595466592.

I've been too lazy to post the updates. Fixing it now...

**Comment by jawalonoski** [comment]
Fixed.
