### ISSUE TITLE
Permission denied when building cloned repo

### ISSUE THREAD

**Issue by lyndbacon** [synthetichealth/synthea#723]
I've cloned the repo using git clone https://github.com/synthetichealth/synthea.git

When I then run run each of the following from a CLI prompt: 

cd synthea
./gradlew build check test

I get permission denied messages from bash, regardless of how I set all file permissions in the synthea directory and below it, or whether I do the above as su.

I'm doing this on Ubuntu 18.04 LTS, Java 11, either Oracle or Open.

Are there files outside the synthea dir tree that the gradle script is trying to write to?

**Comment by dehall** [comment]
On the initial run of `gradlew`, it fetches the full version of gradle from the internet which then gets installed outside the synthea directory, I believe in `~/.gradle`. Can you check that you have full permissions to write there?
That said since you said you tried it as su, could you post the full error message you're getting? There might be something else going on.

**Comment by lyndbacon** [comment]
I don't find a ~/.gradle directory. Maybe creating it is the prob? However, 

(base) me@zdog:/media/sdb2/synthea$ sudo ./gradlew build check test
sudo: unable to execute ./gradlew: Permission denied
(base) me@zdog:/media/sdb2/synthea$ sudo su
root@zdog:/media/sdb2/synthea# ./gradlew build check test
bash: ./gradlew: Permission denied

**Comment by hadleynet** [comment]
Perhaps the execution permission isn't set on the `gradlew` script? If you `ls -l gradlew` what does the output look like? If there aren't `x` in the first column try `chmod ugo+x gradlew` and then re-run the `./gradlew check` command. Alternatively you could use `bash gradlew check`.

**Comment by lyndbacon** [comment]
Thanks.  Yes, I checked the permissions before opening this issue.  I also tried chmod'ing for execution all files in the synthea directory and below it.   I'll try some other things today as I get a little time to do so.

**Comment by lyndbacon** [comment]
Update:  I moved the synthea directory from /media/sdb2 to under ~/ and the script ran.  Check produced 65 errors.  I can provide the log files if you'd like to review them.

**Comment by jawalonoski** [comment]
Checkstyle errors? If so, we know about those. If they are unit test errors, then please share.

**Comment by lyndbacon** [comment]
Eight errors listed in the test.html file.  I'll post soon.

**Comment by lyndbacon** [comment]
Just noticed that all the errors are in test.html that is under ~/synthea/build/reports/checkstyle.  So are these checkstyle errors, not unit test errors?  The file ~/synthea/build/reports/tests/test/index.html  contains a test summary showing zero errors.

**Comment by jawalonoski** [comment]
> Just noticed that all the errors are in test.html that is under ~/synthea/build/reports/checkstyle. So are these checkstyle errors, not unit test errors?

Yes, checkstyle errors. You can ignore those.
