### ISSUE TITLE
FhirR4 Export: wrong SNOMED CT code in careTeam

### ISSUE THREAD

**Issue by LtSurgekopf** [synthetichealth/synthea#726]
I just noticed that the SNOMED CT code for the role of the patient in the `careTeam` resource is wrong 

https://github.com/synthetichealth/synthea/blob/4a8e8c688b6b664cf3e70faa3d050b50a51318ed/src/main/java/org/mitre/synthea/export/FhirR4.java#L2446-2451
```
participant.addRole(mapCodeToCodeableConcept(
        new Code(
            SNOMED_URI,
            "116153009",
            "Patient"),
        SNOMED_URI));
```
That CUI resolves to `Donor of control material (person)` (see https://ontoserver.csiro.au/shrimp/?concept=116153009&system=http://snomed.info/sct&versionId=http://snomed.info/sct/900000000000207008/version/20200309).

The correct CUI for `Patient (person)` is `116154003`. I'll create a PR to fix.

**Comment by jawalonoski** [comment]
Thank you for the pull request!
