### ISSUE TITLE
Generate Test data for Extensions using synthea

### ISSUE THREAD

**Issue by kathipavan** [synthetichealth/synthea#733]
Hi Team, 
we have added extensions to Patient Resource to capture additional information as shown below..
Is there any information available on how to use synthea to populate test data for these added extensions.

Thank you,
Pavan. 

"resourceType": "Patient",
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/birthPlace",
      "valueAddress": {
        "city": "Columbus"
      }
    }
  ]
}

**Comment by kathipavan** [comment]
Thank you for your response, for example , lets say I am using contactpoint-extension (http://hl7.org/fhir/StructureDefinition/contactpoint-extension) that is not part of FHIR R4 exporter you shown above to capture extension for given phone number as part of patient resource. Is there a way to extend default FHIR R4 exporter to include test data even for phone extension as  well?  Thank you..

**Comment by jawalonoski** [comment]
There is no way to do that through configuration today. We have discussed making a generic configuration based method to do something like this, especially if you want to export arbitrary FHIR Implementation Guides, but today the mechanism does not exist.

As of today, you can either modify the FHIR exporter code, or you can implement post-processing.

**Comment by kathipavan** [comment]
Thank you for the clarification..
