### ISSUE TITLE
Encounters that end after death due to procedures with duration

### ISSUE THREAD

**Issue by eedrummer** [synthetichealth/synthea#735]
There is currently a bug in Synthea that can cause encounter end times to be after a person's death date.

The way to reproduce this is to have a `Death` state after an `EncounterEnd` state, where the encounter contains procedures with duration.

When `HealthRecord` ends an encounter, it will cycle through any procedures with a duration and [append this time to the end of the encounter](https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java#L998). If a `Death` state is executed in the same time step, it will be before the encounter end because the death will happen at the time step, but the encounter end will be time step + procedure duration(s).

Depending on the number and length of procedures, this can cause a pretty big gap in times. An example of this is the ICU stay in the COVID-19 module. Since this has the chance of several long dialysis sessions, it can push the end date of the stay back by a couple of days.

A quick fix would be to check the encounter end if the patient is dead to ensure it never exceeds the death date. This would be consistent with procedure duration's use in the COVID-19 module, but I'm not sure what side effects it would have on other modules.

**Comment by dehall** [comment]
Closed with #742
