### ISSUE TITLE
Prescription data is not loaded for MedicationOrder

### ISSUE THREAD

**Issue by pete-thompson** [synthetichealth/synthea#748]
The prescription attribute in the MedicationOrder class has been marked as 'transient' as part of commit [https://github.com/synthetichealth/synthea/commit/8fe563b736ad77f009f38ab4a02c9edac54d5944](https://github.com/synthetichealth/synthea/commit/8fe563b736ad77f009f38ab4a02c9edac54d5944). I don't know why that change was made, but it has had the effect of not loading prescription information for medication orders.

**Comment by jawalonoski** [comment]
@pete-thompson I believe that change was made because the GSON library objects are not Java Serializable. The intent is that the prescription attribute needs to be changed into a full-fledged class, just like Code or the Transitions. But that change was not made during the initial serialization implementation.

**Comment by hadleynet** [comment]
MedicationOrder has overridden the readObject and writeObject methods to handle serialization of the prescription attribute. Can you say a bit more about the issue you are seeing wrt to not loading prescription information - where do you see this?

**Comment by pete-thompson** [comment]
I'm working on a (sadly private for now) fork to simulate clinical trials and am exporting medication data. I found that there were no prescription details when I came to export, so looked back to figure out why.

I can also reproduce the problem by enabling the CDW exporter - the dosageform.csv file only ever contains a single row, but you'd expect it to contain lots of values based on different prescription requirements.

**Comment by hadleynet** [comment]
Just checking - you are using the -u and -i switches to create snapshots of populations that evolve over time?

If so, did you export medication data from the initial snapshot prior to serialization and did that contain the prescription information you expected?

**Comment by pete-thompson** [comment]
No, I'm not using -u or -i. The problem appears to be in deserialisation of the module json files. GSON ignores attributes marked as transient, so it makes no attempt to load the prescription data from the module file, meaning that prescription information is never built into the patient records.

**Comment by pete-thompson** [comment]
I've created a pull request that I think gets this working
