### ISSUE TITLE
How to generate patients with the flu?

### ISSUE THREAD

**Issue by ErwanT-Synodis** [synthetichealth/synthea#754]
Hi,

I would like to know if it's possible to generate patient with **influenza** (the flu).
I tried : `./run_synthea -p 1000 -m *flu`, but there are no modules for it. So I'd like to know if there is another way to do it.

Thank you for your help.

**Comment by jawalonoski** [comment]
We do not have a module for Influenza.

If you'd like to make one, you can use the [module builder](https://synthetichealth.github.io/module-builder/#example_module). There is a tutorial here: https://github.com/synthetichealth/synthea/wiki/Module-Builder-Tutorial
