### ISSUE TITLE
CSV Exporter: Export all instances of all series for ImagingStudies 

### ISSUE THREAD

**Issue by kgoyal1988** [synthetichealth/synthea#765]
The CSV Exporter exports only the first instance of the first series for the imaging studies resource. See [line](https://github.com/synthetichealth/synthea/blob/cf1bfab5f29637764d965bea59c08160e10b295c/src/main/java/org/mitre/synthea/export/CSVExporter.java#L939). It would be great if all the instances of all the series can be exported. This can be achieved if each row represents an instance of a series of a study. The end-user can then groupBy the Study and SOP UID if required. To do so these UIDs should also be exported.

**Comment by jawalonoski** [comment]
Happy to take pull request on this if anyone would like to have a go.

**Comment by ramdesh** [comment]
@kgoyal1988 @jawalonoski I have provided a fix for this in #837. Review and feedback would be appreciated.

**Comment by jawalonoski** [comment]
Fixed with #837
