### ISSUE TITLE
Death Date Exported for Living Patients

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#77]
Occasionally _living_ patients are exported with their death date set (for sometime in the future). This is typically for patients with lung cancer that haven't died yet, but will shortly. **Synthea should only export death dates for patients that are actually deceased.**

Also the `deceasedBoolean` in the FHIR record should be set alongside the `deceasedDateTime` to make it easier to query deceased/living patients.

**Comment by jawalonoski** [comment]
FYI, `deceasedBoolean` and `deceasedDateTime` cannot both be set -- it is a choice element in FHIR. You can have one or the other, but not both.
