### ISSUE TITLE
Setting seed and population_size has inconsistent results

### ISSUE THREAD

**Issue by gitpushdashf** [synthetichealth/synthea#775]
I'm running into a similar problem as #752, running with `-s 12345 -p 1` results in two patients but `-s 1234 -p 1` is just one. The output seems stable, however. This is using the latest published .jar from master.

Please let me know if I can provide any better examples on this.

Also, will there be a new official release any time soon? Would be nice to reference that .jar rather than master.

Thank you!

**Comment by jawalonoski** [comment]
Please read the solution to #752 which is #756 

For recreation of a dataset, you are required to use a random seed (`-s`), a clinician seed (`-cs`), and a reference date (`-r`).

Yes, there will be a new official release soon. Exact date is TBD.

**Comment by jawalonoski** [comment]
Also, `-s 12345` and `-s 1234` are different seeds, so they will give you two different results. Every random number seed will produce different data. Even if the numbers look similar, they are not, and will result in very divergent random number generation patterns.

**Comment by gitpushdashf** [comment]
I see, thank you.

For me the UUIDs were the same every run. I understand that `-s 1234` and `-s 12345` are both different seeds, I was just confused that with `-p 1` 12345 gives me two patients and 1234 gives me one as I would expect.

**Comment by jawalonoski** [comment]
`-p` refers to how many _living_ patients you want.

If patients die along the way, another will be generated. Which is why you sometimes see more patients than you specified.

**Comment by gitpushdashf** [comment]
Gotcha, thank you for explaining!
