### ISSUE TITLE
Synthea running for hours

### ISSUE THREAD

**Issue by IoTFier** [synthetichealth/synthea#776]
Hello,

I am running Synthea for the following configuration on Windows 10 Pro, 2004 ver on a AMD Phenom II X6 PC having 16gb RAM and 512 db SSD. The repo was cloned at a folder stored in a SATA HDD that runs at 7200/10000 rpm.

It has been running for hours. Powers scheme put my PC to sleep after 2 hours, but as of now the from the log the process has been running for last 4h, 45 m, 49 seconds. I am still continuing this process.
The CPU consumption is in the range of 40-40%, memory in the range of 68-78%.

This is the latest console log related to waitthread - Waiting for threads to finish... java.util.concurrent.ThreadPoolExecutor@44924587[Shutting down, pool size = 8, active threads = 8, queued tasks = 6444, completed tasks = 548]. 

Does 548 means it has created only 548 alive patients so far .. from the math it sounds like? 
I wished it had dumped the counter of # of deceased patients so far on the console log as well or at least put alive and deceased patients in separate buckets.

At this rate Is this process going to take another 24 hours or so ?

I see a ton of Deceased population created on based on the console log. 
Will you please guide me how to tune this for the next run where it doesn't run this long ?

Thank you,

.............................................................................................................

.\run_synthea.bat -s 10000 -a 18-120 Texas Dallas -p 7000

**Running with options:**
Population: 7000
Seed: 10000
Provider Seed:1598479831959
Reference Time: 1598479831959
Location: Dallas, Texas
Min Age: 18
Max Age: 120

**Synthea.properties changes -**
ccda.export = true
text.export = true
clinical_note.export = true
database_type = file <====== How to load this .db file to run queries ?
append_numbers_to_person_names = false
veteran_population_override = true
death_by_natural_causes = true

**Comment by dehall** [comment]
We haven't done comprehensive benchmarks on different hardware, so I can't comment on whether or not that's an expected runtime for those settings on that CPU, but I can point out a few things that will help.

 - Specifying an age range with `-a` results in a uniform distribution of ages, so roughly the same number of people will be age 120 as age 18, which probably isn't what you really want. And when synthea tries to generate a 120-year old patient, it's very likely that many of its first attempts will die along the way before reaching age 120, so generating a single 120-year-old patient will actually produce 1 live patient and possibly up to 10 dead ones.
    - If you want something representative of the US veteran population, age 18 and up, (which I suspect you might based on the `veteran_population_override` setting) I'd recommend pointing the demographics file to `veteran_demographics.csv` instead of just `demographics.csv`, ie: `generate.demographics.default_file = geography/veteran_demographics.csv` in synthea.properties
 - Unless you want **a lot** of deceased patients in the resulting dataset, I would recommend disabling the `death_by_natural_causes` setting. Especially combined with the age range setting, this will cause synthea to try to create a lot of "extra" patients. Again consider how synthea tries to re-generate patients to meet the specified number of live patients, and may generate a lot of dead ones on the way.
 - Exporting to an HDD is likely going to be a bit slower than an SSD, though I haven't benchmarked this specifically in the context of synthea export formats.
 - As much as I like the idea of the database, in practice I actually recommend not using it for large populations. The file size of the H2 database just gets too large, and it really reduces performance as well. If you take a look at the `.db` file it already created in the synthea folder, it's probably already many GBs in size. That said, if you still want to take a look, it's in the H2 format. I use DBeaver which is free but you can also just use the H2 jar itself to launch an SQL editor tool and point it to that db file. More info on the schema is here: https://github.com/synthetichealth/synthea/wiki/Custom-Reports

**Comment by IoTFier** [comment]
Thank you @dehall . I will review your input closely.

In the meantime, here is another updated snapshot as the process is still running.
Should I kill it to apply changes from your input ? Or is there a way to run a parallel process pointing to another output path via parameter? Thanks.

Waiting for threads to finish... java.util.concurrent.ThreadPoolExecutor@44924587[Shutting down, pool size = 8, active threads = 8, queued tasks = 6265, completed tasks = 727]
734 -- Estefana Kuphal (56 y/o F) Dallas, Texas DECEASED
732 -- Isiah Walker (70 y/o M) Dallas, Texas DECEASED
728 -- Clay Berge (68 y/o M) Dallas, Texas DECEASED
720 -- Olin Bartell (72 y/o M) Dallas, Texas DECEASED
<==========---> 80% EXECUTING [7h 46m 53s]
> :run

**Comment by jawalonoski** [comment]
> Should I kill it to apply changes from your input ?

Yes. Do not use the database. 

> Or is there a way to run a parallel process pointing to another output path via parameter?

Technically, you can run it as many times as you want. If you run it simultaneously in the same folder the behavior is undefined though. But if decided to try running it a second time, my suggestion is to change the `exporter.baseDirectory` by using a command-line switch, e.g. `--exporter.baseDirectory=./output2/` so it isn't trying to write into the same output area.

**Comment by IoTFier** [comment]
Killed it after 790 patients alive patients created in 9 hours :(

Waiting for threads to finish... java.util.concurrent.ThreadPoolExecutor@44924587[Shutting down, pool size = 8, active threads = 8, queued tasks = 6202, completed tasks = 790]
797 -- Milton Keeling (56 y/o M) Dallas, Texas DECEASED
<==========---> 80% EXECUTING [9h 2m 31s]
> :run

**Comment by IoTFier** [comment]
@dehall , per your input on age criteria - a, I spelled our my current requirements in #771. I need a mix of population that has veterans but presenting themselves in non-va hospitals.

Requirement copied here too. 
 - in case not using -a, how do we make sure the generated population is above 18 years old ? I am interested in creating a volume of acute care patients across hospitals in a given city with the generated population is at randomized between 75 - 100 % of the bed capacity for each hospitals.

Similar need is to generate a population for -

(-a <18 ) Children hospitals and
for LTAC (long term acute care) hospitals and
some for Hospice facilities

Your help will be appreciated.
Thank you.

**Comment by jawalonoski** [comment]
For reference, when I run synthea on my MacBook I generate 1000 patients per minute. FHIR, CSV, notes, etc. Don't use the database and you'll be fine.

You can use the age parameter, but maybe don't go up to 140 years old (with or without using natural causes). Is 65 sufficient? 85?

Also, you can't force 75% or more of the bed capacity to be used. Synthea doesn't work like that. If you want to generate a significant volume of acute care patients taking up beds, you need a module to do that for you.

Also, synthea is not currently using the `src/main/resources/providers/hospice.csv` or `src/main/resources/providers/longterm.csv` provider files. So, that is going to be a major issue for you.

**Comment by IoTFier** [comment]
@jawalonoski - thank you for the input.
I could work with -a upto 85. Will not use natural cause for death and even database.
When do we use the database ?

Is there a step-by-step guide to create and apply the module in the local configuration ? I saw your FHIRly video from 2018 where you demoed the way to create a module but didn't quite get how to incorporate that in the list of all modules, and how to make sure the custom generated module takes the precedence before other modules are applied.

In future, will there be any support for hospice.csv and longterm.csv ?
Thanks

**Comment by jawalonoski** [comment]
> When do we use the database ?

Most people should not. Which is why it is disabled by default. It is a tool for the developers.

If you really want a database, generate the CSV data and pull it into a relational database.

> Is there a step-by-step guide to create and apply the module in the local configuration ?

Somewhat. Here is a module builder tutorial that is probably getting stale, https://github.com/synthetichealth/synthea/wiki/Module-Builder-Tutorial.

After you edit a module, you just have to download and copy it into the module folder. See this step: https://github.com/synthetichealth/synthea/wiki/Dev-Days#browse-the-diseases

> In future, will there be any support for hospice.csv and longterm.csv ?

Yes. No timeline.

**Comment by jawalonoski** [comment]
> Should SSD/SATA drive make that much of a difference ?

Not really. The time you see is due entirely to the database, or if you have an older machine, processing/memory.

> For what FHIR resources do you use csv for output ? Is there a way to upload that csv in FHIR server like Azure FHIR OSS / API ?

No. If you want FHIR, export FHIR.

**Comment by IoTFier** [comment]
Thank you @jawalonoski .

Made couple of updates (set database to none, natural death to false) as suggested by you and @dehall - and wow! what huge difference ...

**_.\run_synthea.bat -s 10000 -a 18-85 Texas Dallas -p 1000_**

Records: total=1510, alive=1000, dead=510

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5m 26s
4 actionable tasks: 3 executed, 1 up-to-date

---------------------------------------------------------------------------

_Unless it is possible now_, may I request you to consider following features that will allow us -
1. to control a  mix of alive and deceased population (see in the example above I have 50 % of deceased population within a range of 18-85)
2. ability to associate population capacity at a give n hospital by referring to the a set of id fields from the hospitals.csv 
3. ability to create population at a hospital with discharge and re-admitted back to the same hospital within 24 hours to 2 weeks period 
4. ability to create population for skilled nursing facility, hospice and long term acute care ?

I would really appreciate that consideration.
Thank you.

**Comment by jawalonoski** [comment]
#3 is possible using a new module if `generate.providers.selection_behavior` is not set to `random`. Just create a module with an inpatient encounter, and readmit them after a small delay. Follow the tutorials linked earlier to understand the process, and then create a new module with the flow you want to happen.

#4 is planned for, but the date is TBD.

#1 and #2 moved to #777.

**Comment by IoTFier** [comment]
Hello @jawalonoski , @dehall , thank you for your help.

@jawalonoski - I appreciate for accepting features for 1 & 2.
For 3, I will create a module per your guidance. 
Thank you.
