### ISSUE TITLE
Help needed for Synthea Canada

### ISSUE THREAD

**Issue by pooky1955** [synthetichealth/synthea#781]
Background
-------------------

Hi,
I am working with Manqing (@mnqng) on the Canadian dataset and we have successfully generated 4 files : demographics.csv, hospitals.csv, nursing.csv, primary_care_facilities.csv.

After generating the csv files, I first tried using the example folder of Synthea International by replacing demographics_uk.csv with our demographics.csv and changing the filename correctly in synthea.properties. We repeated the same process with hospitals.csv, nursing.csv, and primary_care_facilities.csv. After copying these files to the synthea git folder, I tried running ./run_synthea without any option and it gave me an error message with gradle. I also tried directly substituting the demographics.csv in the synthea folder with the Canada directly and it gave the same behaviour as following the synthea example directory.

Java Version
----------------
```
➜  ~ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

Error when running `./run_synthea`
----------------------------------------------
```

> Task :run FAILED
java.lang.RuntimeException: Unable to select a random city id.
        at org.mitre.synthea.world.geography.Location.randomCityId(Location.java:235)
        at org.mitre.synthea.world.geography.Location.randomCity(Location.java:187)
        at org.mitre.synthea.world.agents.Provider.generateClinician(Provider.java:445)
        at org.mitre.synthea.world.agents.Provider.generateClinicianList(Provider.java:425)
        at org.mitre.synthea.world.agents.Provider.loadProviders(Provider.java:383)
        at org.mitre.synthea.world.agents.Provider.loadProviders(Provider.java:315)
        at org.mitre.synthea.engine.Generator.init(Generator.java:234)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:171)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:156)
        at App.main(App.java:199)
Exception in thread "main" java.lang.RuntimeException: Unable to select a random city id.
        at org.mitre.synthea.world.geography.Location.randomCityId(Location.java:235)
        at org.mitre.synthea.world.geography.Location.randomCity(Location.java:187)
        at org.mitre.synthea.world.agents.Provider.generateClinician(Provider.java:445)
        at org.mitre.synthea.world.agents.Provider.generateClinicianList(Provider.java:425)
        at org.mitre.synthea.world.agents.Provider.loadProviders(Provider.java:383)
        at org.mitre.synthea.world.agents.Provider.loadProviders(Provider.java:315)
        at org.mitre.synthea.engine.Generator.init(Generator.java:234)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:171)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:156)
        at App.main(App.java:199)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
```

I think the error is in the way we structured our csv which is different than synthea-international, but I don't know what is the difference that is causing the error. It does look like a problem with the cities, so I guess it should be in the demographics.csv.

Error when running `./run_synthea Montréal`
-----------------------------------------------------------
```
➜  synthea git:(master) ✗ ./run_synthea Montréal

> Task :run FAILED
Exception in thread "main" java.lang.NullPointerException
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:196)
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:236)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:171)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:156)
        at App.main(App.java:199)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
4 actionable tasks: 2 executed, 2 up-to-date
```

Attachments
----------------
[synthea-international-canada.zip](https://github.com/synthetichealth/synthea/files/5177228/synthea-international-canada.zip)

End Note
--------------

Please let us know if this issue should be moved to synthea international or not.
Thank you for your help!
James and Manqing

**Comment by jawalonoski** [comment]
Apologies for the delay. I haven't downloaded and tested your attachment yet, but my guess it is a formatting issue. I'll try to get you some more feedback later today.

**Comment by jawalonoski** [comment]
The first error `Error when running ./run_synthea` is because the default location is `Massachusetts`, which no longer exists when we replaced the demographics file.

So, when you run with an international file set, you must always specify the location.

**Comment by jawalonoski** [comment]
The second error `Error when running ./run_synthea Montréal` has two parts.

First, the `NullPointerException`. Synthea requires some geography details. We need to provide those in the `src/main/resources/geography/zipcodes.csv` files. For example,

```csv
,USPS,ST,NAME,ZCTA5,LAT,LON
,Quebec,QC,Montréal,G9999,52.0,-72.0
```

Second, the correct command for Synthea is STATE (required) and then CITY (optional). So,

```
./run_synthea Quebec
```
or
```
./run_synthea Quebec Montréal
```
---------

After making a zip code addition for Montréal, Quebec, I can run the command:

```
./run_synthea Quebec Montréal
```

Which results in another error:

```
java.lang.RuntimeException: Unable to find provider: urgentcare
```

We need to also provide an `urgent_care_facilities.csv` file with at least one urgent care facility in Quebec.

**Comment by Jakatut** [comment]
Hey @pooky1955 Just wondering if you were ever able to get this going. I'm interested in using Synthea for a project and would greatly appreciate any guidance on how to get this working for Canada. Thanks :)

**Comment by pooky1955** [comment]
Hi @Jakatut! Sorry for the delay, I didn't continue working on Synthea Canada, so I did not manage to make it work. I'm not sure if it has already been implemented, but now that I have free time, I could continue working on it. Tell me if I could be of any help @jawalonoski!

**Comment by Jakatut** [comment]
Oh hey James! My team and I actually got it working. I can see if i can get themcon here.




________________________________

**Comment by pooky1955** [comment]
That's really nice! Congratulations!

**Comment by jawalonoski** [comment]
@Jakatut would you or your team be willing to put in a pull request for Canada to https://github.com/synthetichealth/synthea-international?

**Comment by Jakatut** [comment]
Yeah, im just double checking that we can share the data we used.




________________________________

**Comment by Jakatut** [comment]
Hey, so I found the site we got the data from: https://simplemaps.com/data/canada-cities#anchor_fsa_method
Looks like we can use it as long as there is some sort of credit like a link to the page.

**Comment by jawalonoski** [comment]
> Hey, so I found the site we got the data from: https://simplemaps.com/data/canada-cities#anchor_fsa_method
> Looks like we can use it as long as there is some sort of credit like a link to the page.

The README for the Canadian files in the synthea-international repository would be a good place to prominently cite that source, and any others you might have used.

**Comment by jawalonoski** [comment]
@Jakatut Any update on this? Anything we can do to help?

**Comment by Jakatut** [comment]
Hey, sorry. Been swamped with work and school.

Ill see if I can add them this week.




________________________________

**Comment by jawalonoski** [comment]
@Jakatut Gentle nudge and plea.

**Comment by Jakatut** [comment]
Hey, I've added some info to the readme. Sorry, i have 0 time to get snd add the data again.




________________________________

**Comment by jawalonoski** [comment]
I went back to the original data from the Statistics Canada websites and produced working configuration files (they work for every province). The files function, I didn't encounter any errors in my testing. However, there are issues with some of the coordinates and postal codes (they are inaccurate).

https://github.com/synthetichealth/synthea-international/pull/8

**Comment by pooky1955** [comment]
Oh ok that's great to hear @jawalonoski ! Do you have any idea why the postal codes wouldn't work? I didn't take a detailed look at the csvs that were generated. It seemed fine at brief glance.

**Comment by jawalonoski** [comment]
In short, postal codes in Canada are just as weird (or weirder) than they are in the US. See https://en.wikipedia.org/wiki/Postal_codes_in_Canada

It is estimated that there are over 830,000 postal codes in Canada.

I didn't have the motivation to tackle that. If someone does, I'm happy to take that as a future pull request.

**Comment by pooky1955** [comment]
Are the postal codes a big problem? Does the rest of the data generated look fine?

**Comment by jawalonoski** [comment]
> Are the postal codes a big problem? Does the rest of the data generated look fine?

The postal codes should not a big problem for most users, unless they have a use-case where they really need to be accurate. Some of the lat/lon coordinates are inaccurate (when they were null, I defaulted to plopping them into the middle of the province). Otherwise, the patient data looks fine.

**Comment by pooky1955** [comment]
Oh ok I see, that's great to hear!

**Comment by jawalonoski** [comment]
Fixed with https://github.com/synthetichealth/synthea-international/pull/8
