### ISSUE TITLE
CPCDSExporterTest does not properly validate generated CSVs

### ISSUE THREAD

**Issue by OtherwiseJLo** [synthetichealth/synthea#786]
I created a temporary variable debugView in CPCDSExporterTest to see its contents in the debugger. The screenshot below shows the contents of debugView without any modifications to the code.
![testsNoModification](https://user-images.githubusercontent.com/54177704/92924404-e4925d80-f406-11ea-99d4-7670739b6981.png)

I commented out line 312 in CPCDSExporter to see what an invalid CSV line produce. No error is thrown by SimpleCSV.parse() and the contents of debugView can be seen below:
![testRemoveField](https://user-images.githubusercontent.com/54177704/92924555-26bb9f00-f407-11ea-8c4b-1c06b0426e4b.png)

**Comment by jawalonoski** [comment]
Fixed with #787. Thank you for the issue and the pull request to fix it.
