### ISSUE TITLE
What SNOMED-CT edition is being used?

### ISSUE THREAD

**Issue by abdulzeedo** [synthetichealth/synthea#794]
Hi guys

I have looked in the wiki pages, and other issues, but I couldn't find any reference to the edition that is being used. I am asking because this diagnosis code: 15777000 Prediabetes (disorder) is now deprecated, the term Prediabetes still exists but it has been assigned a new code and is placed differently in the ontology. I am using the Snomed-CT US 2020-03-31 edition. 

The deprecated code:
https://browser.ihtsdotools.org/?perspective=full&conceptId1=15777000&edition=MAIN/SNOMEDCT-CA/2020-03-31&release=&languages=en,fr

The new code:
https://browser.ihtsdotools.org/?perspective=full&conceptId1=714628002&edition=MAIN/SNOMEDCT-CA/2020-03-31&release=&languages=en,fr

Any help?

**Comment by jawalonoski** [comment]
Currently we do not use a single version of SNOMED, and SNOMED codes are not updated in bulk. Occasionally individual codes are updated (usually when they become deprecated and someone complains).

The system has been developed over years and the codes are selected (from the International Edition primarily, occasionally from the US Edition if they do not exist in the International Edition) at the time that portion of the system was being developed.

The con is obvious. The pro is this mirrors the real world. Historical records exist out in the wild.

**Comment by abdulzeedo** [comment]
I agree with the pro, the notion spouses well with the objective of my research. I will try out a few different editions and see which ones have the least deprecated values. Thanks a lot.
