### ISSUE TITLE
Maven dependencies are 404'ing

### ISSUE THREAD

**Issue by jonobrien** [synthetichealth/synthea#807]
So I have tried both your snapshots and central maven embed options from the wiki.  It appears that your pom.xml files are 404'ing.

[https://repo.maven.apache.org/maven2/org/mitre/synthea/Synthea/2.5.0/Synthea-2.5.0.pom](https://repo.maven.apache.org/maven2/org/mitre/synthea/Synthea/2.5.0/Synthea-2.5.0.pom)
[https://repo.maven.apache.org/maven2/org/mitre/synthea/Synthea/2.6.1/Synthea-2.6.1.pom](https://repo.maven.apache.org/maven2/org/mitre/synthea/Synthea/2.6.1/Synthea-2.6.1.pom)

**Comment by hadleynet** [comment]
We haven't released a 2.6.1-SNAPSHOT but you should be able to pull the 2.6.1 release:

https://oss.sonatype.org/#nexus-search;quick~synthea

I see you are capitalizing Synthea in your links, try lower case:

https://repo.maven.apache.org/maven2/org/mitre/synthea/synthea/2.6.1/synthea-2.6.1.pom

**Comment by hadleynet** [comment]
I've fixed the wiki page to uncapitalize Synthea in the example pom entries.

**Comment by jonobrien** [comment]
Ahhh, that makes sense, thanks!
