### ISSUE TITLE
App has been compiled by a more recent version of the Java Runtime (Class file version 58.0)

### ISSUE THREAD

**Issue by gitpushdashf** [synthetichealth/synthea#813]
Hi,

I get this error using the v2.6.1 synthea-with-dependencies.jar, but not the master synthea-with-dependencies.jar.

Would there be any way you could build v2.6.1 for JDK 8?

Thank you!

**Comment by gitpushdashf** [comment]
Related: #658

**Comment by hadleynet** [comment]
I've added a build for JDK 8: [https://github.com/synthetichealth/synthea/releases/download/v2.6.1/synthea-with-dependencies-jdk8.jar](https://github.com/synthetichealth/synthea/releases/download/v2.6.1/synthea-with-dependencies-jdk8.jar).

Please let me know if this works for you.

**Comment by gitpushdashf** [comment]
Thank you! That should work!
