### ISSUE TITLE
What FHIR version does Synthea generate?

### ISSUE THREAD

**Issue by gitpushdashf** [synthetichealth/synthea#814]
https://github.com/synthetichealth/synthea/wiki/Getting-Started says R4 3.5, but 4.0.1 is the latest R4. How far from 4.0.1 is Synthea?

Thank you!

**Comment by dehall** [comment]
Thanks for bringing that to our attention - that note is very out of date and I've now updated it. Synthea does support FHIR 4.0.1, and it's considered the "default" version of FHIR in Synthea at this point.
For more detail on which specific resource types are supported, see: https://github.com/synthetichealth/synthea/wiki/HL7-FHIR

**Comment by gitpushdashf** [comment]
Thank you! That's great to hear.
