### ISSUE TITLE
New features/columns configuration

### ISSUE THREAD

**Issue by VenkateshShruti** [synthetichealth/synthea#816]
Hello

Is there a way to use Synthea to configure and generate additional columns for encounters/claims for the existing modules? 

Thank you

**Comment by jawalonoski** [comment]
It is not possible to do this by configuration.

If you mean to modify the CSV exporter, you need to edit the Java exporter code in https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/CSVExporter.java

Depending on what columns and data you need, you may have to edit the underlying HealthRecord.Encounter class https://github.com/synthetichealth/synthea/blob/a6b23894867f0bb46edf768a55cda51508a0d6dc/src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java#L493 or claims.
