### ISSUE TITLE
Evolving a Population - Help needed

### ISSUE THREAD

**Issue by ttavoula** [synthetichealth/synthea#832]
Hello,

I used the "Evolving a Population" feature to create and evolve a sample cohort of 10 patients (metabolic*) for 3 time steps (-t 100). My problem is that in the corresponding "conditions.csv" file of each step the conditions/symptoms as well as the encounter days are still the same. What am I missing?

Also, could you please provide some insight in terms of how this module "continues the simulation"? (e.g., there is an update in demographic data, new start dates, everything is done randomly?)

Thank you :)

**Comment by hadleynet** [comment]
Could you add the exact command lines you used to run Synthea for each step so I can see if I can reproduce this locally.

Wrt your question about continuing the simulation: Synthea loads the prior state of each person at the end of the prior run and then runs each person's record forward by the specified number of days. A given person's demographic data won't change but their health may change, e.g. acquiring a new condition, having a new encounter etc.

Thanks.

**Comment by ttavoula** [comment]
Sure. I used the same format as here: https://github.com/synthetichealth/synthea/wiki/Evolving-a-Population, I just added one more time step. Below are my commands:

$ mkdir -p output/1 output/2 output/3 output/4
$ ./run_synthea -p 10 -m metabolic* -u output/1/snap --exporter.baseDirectory output/1
$ ./run_synthea -i output/1/snap -u output/2/snap -t 100 --exporter.baseDirectory output/2
$ ./run_synthea -i output/2/snap -u output/3/snap -t 100 --exporter.baseDirectory output/3
$ ./run_synthea -i output/3/snap -u output/4/snap -t 100 --exporter.baseDirectory output/4

**Comment by hadleynet** [comment]
I think this issue is related to the relatively short time you are using between snapshots coupled with only using the metabolic syndrome modules. These modules build in long delays in some places (e.g. 0-30 years, 0-7 years). In my testing, if I extended the period of time between snapshots I did see new entries in the conditions.csv.

**Comment by ttavoula** [comment]
Got it. Thank you!
