### ISSUE TITLE
How to generate different patient conditions 

### ISSUE THREAD

**Issue by Gresliebear** [synthetichealth/synthea#851]
I am looking to generate patient data for a data science project, I want to change the conditions of the population with let's say higher rates of heart attacks or cardiovascular problems in general, to match closer to the reality of the state I currently live in. 

How do I easily change properties to do that?

**Comment by jawalonoski** [comment]
You have to modify the disease modules. You can do this with a text editor (see the documentation on the [format](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework) and edit the files in `src/main/resources/modules`) or graphically with a point-and-click interface by using the [Module Builder](https://synthetichealth.github.io/module-builder/). Using the module builder still requires that you save your modifications locally, and run the data locally.

**Comment by Gresliebear** [comment]
Thank you very much I will close it now
