### ISSUE TITLE
Lipid panel observations for healthy patient

### ISSUE THREAD

**Issue by arrowarchit** [synthetichealth/synthea#874]
Hey, I am new to Synthea, still figuring out a lot of things. I want to generate data for lipid profile observations like: HDL, LDL etc. for healthy patients(patients who have these lipid levels in the normal range and are not suffering from any other conditions). I tried using the Wellness_Encounter module for this, but it only generates observations described as DALY, QALY and QOLS in 'observations.csv' output. Kindly help me understand this better.

**Comment by jawalonoski** [comment]
@arrowarchit There is already a Lipid Panel in the [Wellness Encounter](https://synthetichealth.github.io/module-builder/#wellness_encounters) module. The state is called `Record_LipidPanel`. However, as you can see from this image, there is a conditional transition that limits who gets those panels, to people with Diabetes or those who are over the age of 30 and haven't had a panel within the last 3 years.

![image](https://user-images.githubusercontent.com/1054765/113150572-39aa8b00-9202-11eb-9423-6ea5758a53cf.png)

If you want everyone to get such a panel, you could change the transition conditional logic, or simply make it a [Direct Transition](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Transitions#direct).

So, for example:
![image](https://user-images.githubusercontent.com/1054765/113151002-acb40180-9202-11eb-963d-ff3902910b39.png)

Which results in this:
![image](https://user-images.githubusercontent.com/1054765/113151112-c5241c00-9202-11eb-89a2-9021645b6219.png)

Then you need to click the orange "Download" link on the top banner, and click the "Download" button in the dialog. Save the file to your module directory. [Run your local module](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Running-New-Modules).

One last thing, in case you are running into this: Synthea only outputs the last 10 years of data by default. If you want to change that, change the `exporter.years_of_history` property. Setting it to zero (`0`) skips filtering by date altogether.

**Comment by arrowarchit** [comment]
@jawalonoski Thanks for the reply, it worked out very well for me and I was able to generate the required data. Had another doubt regarding the module named 'Veteran_Hyperlipidemia'. The condition on veteran guard is exactly same for both if and else. Also, the module does not seem to include any other symptom other than weight gain for the condition onset, is that module completed yet or in progress?

**Comment by arrowarchit** [comment]
@jawalonoski  Thanks for the reply, it really helped.
