### ISSUE TITLE
how to find the smoking information?

### ISSUE THREAD

**Issue by RAiBoy** [synthetichealth/synthea#882]
I can find the smoking information from the Observation when I use  this command: ./run_synthea -p Num, but in this way I cannot find the metabolic patients, so I use ./run_synthea -p 10 -m metabolic*
and generate the metabolic patients records, but in this way I cannot find the smoking status information. can you please help me resolve it? THX!

**Comment by RAiBoy** [comment]
hi, I have already resolved this problem.

**Comment by jawalonoski** [comment]
Please see https://github.com/synthetichealth/synthea/wiki/The--M-Feature

Do not use the `-m` feature.

- Rerun Synthea without `-m`.
- `cd /output/fhir`
- `grep "smoking" *`

**Comment by RAiBoy** [comment]
it really helps me! thanks for your help!
