### ISSUE TITLE
Person Resource

### ISSUE THREAD

**Issue by rlapensee** [synthetichealth/synthea#884]
When looking at the Patient and Practitioner bundles generated, I am not seeing the subsequent Person resource defined? See example of Patient below I would expect... @jawalonoski any ideas how to get these Resources to include the Person resource?

`{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:470bbce1-f80a-4038-8d47-341293f59282",
            "resource": {
                "resourceType": "Patient",
                "id": "470bbce1-f80a-4038-8d47-341293f59282",
                "identifier": [
                    {
                        "system": "http://sunkist.com/codesystem/some-id",
                        "value": "duplicate"
                    }
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Savagery",
                        "given": [
                            "Shawn"
                        ]
                    }
                ]
            },
            "request": {
                "method": "POST",
                "url": "Patient"
            }
        },
        {
            "request": {
                "method": "POST",
                "url": "Person"
            },
            "resource": {
                "resourceType": "Person",
                "link": [
                    {
                        "target": {
                            "reference": "urn:uuid:470bbce1-f80a-4038-8d47-341293f59282"
                        },
                        "assurance": "level3"
                    }
                ]
            }
        }
    ]
}`

**Comment by jawalonoski** [comment]
We do not create or populate the `Person` resource. See https://github.com/synthetichealth/synthea/wiki/HL7-FHIR for a list of resources that Synthea currently supports.

If you want to add this functionality yourself, you can modify the FHIR exporters. For example, the FHIR R4 exporter is here: https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/FhirR4.java
