### ISSUE TITLE
Gaussian distribution for delay appears to generate incorrect mean values when distribution includes negative values for delays

### ISSUE THREAD

**Issue by casey7083** [synthetichealth/synthea#885]
#788 We are working on building an Acute Myeloid Leukemia module that generates a patient population with specific age distributions. We tried out the new Gaussian distribution with a mean age of 7.7 years and a Standard Deviation of 5.9 at the top of our module. It is generating patients that are diagnosed and entering an encounter prior to birth (sometimes several years before birth). This new Gaussian distribution for delay appears to generate incorrect mean values when the distribution includes negative values for delays.

•	Specified gaussian mean (sd) for delay **7.7** (5.9)
•	Synthea's observed/generated mean (sd)  **6.9** ( 5.7) 

After manually removing records with delays <0, expected mean value is observed, with lower sd.
•	**7.99 ( 4.94)**
![pic1](https://user-images.githubusercontent.com/46937161/118320317-aed7d400-b4c1-11eb-8f7c-ac70643a49b1.png)
![pic2](https://user-images.githubusercontent.com/46937161/118320650-26a5fe80-b4c2-11eb-97b3-3e77ee2ac42f.png)

**Comment by eedrummer** [comment]
There are a few potential issues going on here.

If you have a Gaussian distribution with a mean of 7.7 and SD of 5.9, a little less than 10% of the values will end up being less than 0. The way that delay state work, I could imagine it rewinding time to a time before an individual was born, although the value generated is way outside of the mean, so there may be more going on.

I can add some code to ensure a Delay is never less than 0. However, this will distort the distribution.

I can also take a look and see if an SD value substantially less than the mean generates the expected distribution.
