### ISSUE TITLE
CSV output doesn't have headers

### ISSUE THREAD

**Issue by dsfabian** [synthetichealth/synthea#887]
Hi! I'm having this weird problem where I changed the simulation output to be CSV's but the CSV's are outputting with no heading rows. I just cloned the project on Sunday. In synthea.properties, I only changed exporter.csv.export and exporter.csv.append_mode to true I think and I'm having this problem. Is there another setting I need to change in that file?

**Comment by jawalonoski** [comment]
Append Mode does not print headers. The idea is that you run Synthea once with append_mode false to get headers. Then you run it again and again with different settings with append_mode true, and the data is appended to the existing files without headers.
