### ISSUE TITLE
MedicationOrder is not used in DSTU3 anymore

### ISSUE THREAD

**Issue by rqg0717** [synthetichealth/synthea#89]
MedicationOrder is not used in DSTU3 anymore, but synthea:fhirupload still uploads that resource to STU3 FHIR server.

**Comment by jawalonoski** [comment]
According to the latest FHIR build `MedicationOrder` has been renamed to `MedicationRequest`. Our FHIR implementation is based on the [`fhir_models`](https://github.com/fhir-crucible/fhir_models) gem. We'll update our export after that dependency has been updated.

**Comment by cjduffett** [comment]
The latests FHIR STU3 documentation from HL7 suggests that MedicationOrder is still the expected name of that resource. See: http://hl7.org/fhir/2016Sep/medicationorder.html.

**Comment by jawalonoski** [comment]
@cjduffett you're looking in the wrong place. The link you provided was to the ballot version. @rqg0717 is referring to the [current build](http://build.fhir.org/medications-module.html) which will become the finalized STU3.
