### ISSUE TITLE
Execution failed for task ':app:validateSigningDebug'. > java.util.concurrent.ExecutionException: com.android.builder.utils.SynchronizedFile$ActionExecutionException: java.io.IOException: com.android.ide.common.signing.KeytoolException: Failed to create keystore.

### ISSUE THREAD

**Issue by z7b** [synthetichealth/synthea#891]

**Comment by Issaalhilali** [comment]
i have same problem

**Comment by jawalonoski** [comment]
A description would be helpful.

- How was this error encountered?
- Do you have steps to recreate it?
- What does your environment look like?

Based on `com.android.builder.utils` package, my guess is that you're trying to build or run Synthea on Android????

**Comment by jawalonoski** [comment]
I'm closing this issue. No explanation or details. Impossible to recreate.
