### ISSUE TITLE
GSON InaccessibleObjectException / Illegal Access exceptions while running Synthea with JDK 16

### ISSUE THREAD

**Issue by gbharathsri** [synthetichealth/synthea#897]
I installed JDK 8 and then later 16.0.1 on Mac OS and encountered Null pointer exceptions when attempting to run Synthea (both in development and basic setup modes).
`java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.concurrent.atomic.AtomicLong java.util.Random.seed accessible: module java.base does not "opens java.util" to unnamed module @40f9161a`

`caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.concurrent.atomic.AtomicLong java.util.Random.seed accessible: module java.base does not "opens java.util" to unnamed module @40f9161a`

I installed JDK 15.0.2 and it worked as expected. Just reporting in case if it's not a known issue.

**Comment by jawalonoski** [comment]
Thank you for the bug report.

What command or properties did you use that resulted in this exception?

Also, just to be clear, your title is `Null pointer exceptions...` but the details say `InaccessibleObjectException` -- I assume it is really the latter.

**Comment by gbharathsri** [comment]
Sorry, it's the latter. I ran below standard commands to generate some data. Reg. synthea.properties, I attempted to generate default fhir and also csv data with same end result of InaccessibleObjectExceptions.

run_synthea -p 100
run_synthea -p 1000
run_synthea Massachusetts Boston
java -jar synthea-with-dependencies.jar -p 1000
java -jar synthea-with-dependencies.jar -a 18-65

**Comment by jawalonoski** [comment]
Unable to replicate with JDK8 on Mac OS X.

Have not tested with JDK16.

**Comment by jawalonoski** [comment]
Recreated with JDK16.

`at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)`

Possibly need to upgrade GSON library?

**Comment by jawalonoski** [comment]
Interestingly enough, `./gradlew clean check` passes all unit tests with JDK16.

**Comment by jawalonoski** [comment]
You can temporarily fix this in JDK16 by modifying our `build.gradle` file to allow the GSON library to make illegal access.

Add `--illegal-access=permit` to the JVM args (see second line):

```gradle
run {
  jvmArgs '--illegal-access=permit'
  // args are called "arams" because they are called with -P,
  // ex. gradle run -Params="['arg1', 'args2']"
  // see https://stackoverflow.com/questions/27604283/gradle-task-pass-arguments-to-java-application
  if (project.hasProperty("arams")) {
    args Eval.me(arams)
  }
  def maxHeapSizeVar = System.getenv("MAX_HEAP_SIZE")
  if (maxHeapSizeVar != null) {
    maxHeapSize = maxHeapSizeVar
  }
}
```

Or with the jar file:

```
java --illegal-access=permit -jar synthea-with-dependencies.jar
```

**Comment by jawalonoski** [comment]
Reference https://github.com/google/gson/issues/1216

**Comment by jawalonoski** [comment]
Apparently using reflection on any `java.*` packages and classes is illegal, so we have to write our own serialization/deserialization for those classes (probably includes util structures, Random, etc).
