### ISSUE TITLE
Customize SSNs

### ISSUE THREAD

**Issue by fjukstad** [synthetichealth/synthea#903]
Hi,

First off, thanks for a great project! 

I want to use Synthea to generate synthetic Norwegian patients. [I've updated `synthea-international` to include Norwegian names](https://github.com/synthetichealth/synthea-international/pull/7), but I would like to get their social security numbers as realistic as possible. [Here](https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/children-born-in-norway/national-id-number/#structure-of-the-national-identity-number) are some more details on how our identity numbers are constructed. 

From my tiny bit of research, it looks like [this](https://github.com/synthetichealth/synthea/blob/c1baca8e5f6460cf41bffa577731afff164668c6/src/main/java/org/mitre/synthea/modules/LifecycleModule.java#L159) is where you generate SSNs for persons. I'd like to make it possible for me to replace this line with my own Norwegian SSN generator. How would you reccommend that I implement it? Is this something that you would like me to contribute to the code base? If not, I can create my own Norwegian fork of Synthea, but it would be amazing if we could join our efforts. 

Thanks,
Bjørn

**Comment by jawalonoski** [comment]
Well, yes, the quick and easy thing to do would just be to alter the lines of code you identified.

Alternatively, you could implement a `HealthRecordEditor` class that overwrites the SSN with the Norwegian format (see [HealthRecordEditor.java](https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/engine/HealthRecordEditor.java) for the Interface definition, and [GrowthDataErrorsEditor.java](https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/editors/GrowthDataErrorsEditor.java) for an example).

Right now, HealthRecordEditors are manually registered with the app and with a configuration parameter (e.g. `growtherrors`), but maybe we change that to do some dynamic class loading or something.

A second alternative, would be to create some configuration setting that takes in a format string and uses that as a template. The weakness there, and with your specific use case, is that approach would have no knowledge about the range limitations based on year of birth or any other meaning in the format string.

A third alternative would be to create some type of `PatientIdentifierGenerator` Interface where users can supply their own implementations (as few or as many as they want), that get loaded dynamically using a class loader, and that get used to set patient identifiers. A bit of work to get that going, but it is an approach we'd be willing to take a look at.

You can probably think of other alternatives.

**Comment by jawalonoski** [comment]
Another alternative is just post-process the data using whatever tools, scripts, or Extract-Transform-Load process you might have.

**Comment by fjukstad** [comment]
Thanks for the detailed response and suggestions @jawalonoski ! I'll give it some thought and see what I come up with. The initial fix will probably be some simple script that replaces the SSNs, but it would be neat to let others supply their own SSN generators with Synthea. Closing this issue until I have more questions! Thanks again!
