### ISSUE TITLE
Gradle Problems?

### ISSUE THREAD

**Issue by lpsample** [synthetichealth/synthea#907]
Hi,

I am getting an error when I try to run synthea since I pulled the other day.

I have tried changing the Gradle wrapper properties file url to be the most recent I can find on the Gradle site (https://services.gradle.org/distributions/gradle-7.1-bin.zip) but that gave me the same error. Any advice would be appreciated!

![Screen Shot 2021-06-24 at 5 44 13 PM](https://user-images.githubusercontent.com/40299515/123336402-d2a42600-d513-11eb-9310-cddedeb0b0b2.png)

**Comment by jawalonoski** [comment]
Is your JAVA_HOME or path set to a JDK (correct) versus a JRE (incorrect)?

Can you run `java -version` and `javac -version`?

**Comment by lpsample** [comment]
![image](https://user-images.githubusercontent.com/40299515/123337265-f4ea7380-d514-11eb-9d56-e82fe92b3260.png)
With --warning-mode all

**Comment by lpsample** [comment]
@jawalonoski 
![image](https://user-images.githubusercontent.com/40299515/123337351-12b7d880-d515-11eb-95fc-00d14453826a.png)

**Comment by jawalonoski** [comment]
What is your `JAVA_HOME` environment variable set to?

**Comment by lpsample** [comment]
It is set to nothing

**Comment by jawalonoski** [comment]
Can you try setting `JAVA_HOME` to the location of your JDK and see if that changes the result?

**Comment by lpsample** [comment]
@jawalonoski That solved it. Thank you so much!!
