### ISSUE TITLE
Generate patients of all USA

### ISSUE THREAD

**Issue by Mike2023** [synthetichealth/synthea#921]
Hi, I am trying to generate a population of patients in all states of USA. 
However, the command of "run_synthea" just generates patients in one state by either specify a state name or using default state.
For example, >run_synthea -s 123 -p 100000 Texas, or >run_synthea -s 123 -p 100000  (default for Massachusetts)
Is there a command / way to generate patients of all states in USA? 

Thanks a lot

Mike

**Comment by jawalonoski** [comment]
Sorry, but unfortunately Synthea does not support this out of the box. 

The best you can do is write a script to run 50 commands (all the states).

51 if you want to run and include Washington DC.

If you want distribution of patients across states weighted by state population counts, you'll have to use the `-p` switch appropriately. In other words, you might not want to run `-p 1000` in every state, you may want to change the count per state based on population density.

**Comment by Mike2023** [comment]
Got it. Thank you.
