### ISSUE TITLE
Export Income and Education in Patients.csv file

### ISSUE THREAD

**Issue by AmmarFaiq** [synthetichealth/synthea#924]
Hi,

Are there any ways to get the income and education of each patient in the CSV files that is generated by the model?

**Comment by jawalonoski** [comment]
There is no parameter that easily enables that.

You can modify the CSV exporter, and add the attributes of interest to this section (you'll probably want to adjust the column headers elsewhere in the code):

https://github.com/synthetichealth/synthea/blob/440c0a46c3c05c47f11d04e695ea81dcd4adfbd5/src/main/java/org/mitre/synthea/export/CSVExporter.java#L586-L605

Some attributes you might be interested in are named (from `Person.java`):

https://github.com/synthetichealth/synthea/blob/440c0a46c3c05c47f11d04e695ea81dcd4adfbd5/src/main/java/org/mitre/synthea/world/agents/Person.java#L71-L78

Alternatively, you could create Observation states in the Wellness module (or something else) that record income and education in the `observations.csv` file.

**Comment by AmmarFaiq** [comment]
Thanks for the suggestions! I tried to modify the CSV exporter and it works!
