### ISSUE TITLE
All encounters are 1 hour long

### ISSUE THREAD

**Issue by samanvp** [synthetichealth/synthea#930]
Is it possible to make encounters have variable length drawn randomly from a distribution?

**Comment by samanvp** [comment]
I took a quick look at the source and one possible solution is to add a random value to `encounter.stop` when we set it here:
https://github.com/synthetichealth/synthea/blob/b1a880afad1d2547ac355bb85eefe4c64b24a92b/src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java#L1064

I am wondering if that change might have any unwanted consequences?

**Comment by jawalonoski** [comment]
It should not be true that "all encounters are 1 hour long."

https://github.com/synthetichealth/synthea/blob/440c0a46c3c05c47f11d04e695ea81dcd4adfbd5/src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java#L523-L532

Those are the minimum base times by encounter type, and depending on the contents of the meeting (e.g. procedures, imaging studies) the length of the encounter can be extended, and even be multiple days in length (e.g. inpatient stays).

Adding a random time to the encounter stop time shouldn't be a big deal if you want to make that change locally and see what happens.

**Comment by samanvp** [comment]
Thanks for your reply, I can confirm my statement was wrong. Using [Synthea data in BigQuery](https://console.cloud.google.com/marketplace/product/mitre/synthea-fhir) I found the number of Encounters of each class:

- `AMB`: 36878889  
- `EMER`: 2058416
- `IMP`: 1390597

using this query:

```SQL
SELECT class.code, count(0)
FROM `bigquery-public-data.fhir_synthea.encounter`
GROUP BY 1
ORDER BY 2 DESC  
```

And using this query I found the distribution of Encounter lengths for `AMB`:
```SQL
SELECT DATETIME_DIFF(DATETIME(REGEXP_EXTRACT(period.end, r"^([0-9-]+T[0-9:]+)[+-][0-9:]+$")),
                     DATETIME(REGEXP_EXTRACT(period.start, r"^([0-9-]+T[0-9:]+)[+-][0-9:]+$")),
                     MINUTE),
       COUNT(0)
FROM `bigquery-public-data.fhir_synthea.encounter`
WHERE class.code = "AMB"
GROUP BY 1
ORDER BY 2 DESC
```
It seems 50% of Encounters of type `AMB` the length is 15 minute (i.e. the default value). For `EMER` 53% are default value and for `IMP` is 39%.
