### ISSUE TITLE
FHIR R4 + US Core Requires additional resource support 

### ISSUE THREAD

**Issue by daemel** [synthetichealth/synthea#942]
The Wiki documentation at https://github.com/synthetichealth/synthea/wiki/HL7-FHIR suggests that the following resources are only supported when using US Core + R4; is this accurate?  If so, then additional resources should be supported when using US Core + R4. 

Resources only supported with R4 and US Core:
CareTeam
Device
DiagnosticReport (for clinical notes)
DocumentReference (for clinical notes)
Location
Medication
MedicationStatement
PractitionerRole
Provenance

Additional documentation issue on the same reference https://github.com/synthetichealth/synthea/wiki/HL7-FHIR#configuring-fhir 

from wiki 
  exporter.fhir.use_us_core_ig = false

from source code (src\main\resources\synthea.properties 
 exporter.fhir.use_us_core_ig = true

**Comment by jawalonoski** [comment]
Yes, the wiki is accurate: those nine additional resources are only exported when using both FHIR R4 and US Core.

The examples in various locations show turning US Core on (`true`) and off (`false`). If you want those resources, turn US Core on (`true`).
