### ISSUE TITLE
Appropriate use of the -m flag to create patients with COVID

### ISSUE THREAD

**Issue by surangak** [synthetichealth/synthea#943]
Hello, 

I am using Synthea to generate patients with COVID. I also want to ensure that my patients represent appropriate disease burden across other illnesses/conditions. So for example, I want to ensure that older COVID patients have more chronic conditions, dementia etc. and require more resources to get better, while younger, healthier patients do not.

I am not clear on when/why I would use the -m flag to generate my population of COVID patients. Given that use of the -m covid18 flag would create patients with an appropriate prevalence of COVID, how is this different from not using the flag at all?

Why/why shouldn't I use the -m flag?

**Comment by jawalonoski** [comment]
Do not use the M flag. Just generate patients as normal, and either only use those that have COVID-19, or consider using a keep file.

Do Not Use the M Feature: https://github.com/synthetichealth/synthea/wiki/The--M-Feature

Keep Patient File: https://github.com/synthetichealth/synthea/wiki/Keep-Patients-Module

**Comment by surangak** [comment]
thank you @jawalonoski, this was very helpful!
