### ISSUE TITLE
Dataset doesn't include patients with Dementia

### ISSUE THREAD

**Issue by surangak** [synthetichealth/synthea#944]
Hi all,

I am doing some experimentation with Synthea.  Let's consider the following command: 
./run_synthea  -s 100 -p 100000 Indiana

In inspecting the 100000 patient records created by this command, I can't find any patients diagnosed with Dementia. Searching through the conditions.csv file for 'dementi*' as well as the SNOMED code '52448006' gives me zero hits.

However, looking at careplans.csv, I see that 'demential management' is included. I don't see any errors during data generation - it looks like dementia.json module is loaded successfully.

Is this expected behavior? any reason i'm not seeing dementias in the conditions file?

**Comment by jawalonoski** [comment]
@surangak Synthea does not include every SNOMED code in the terminology.

You can browse all the diseases and codes using the [Module Builder](https://synthetichealth.github.io/module-builder/), or you can generate an `./output/concepts.csv` file using the `./gradlew concepts` command.

If you review either of those resources, and specifically the [Dementia Module](https://synthetichealth.github.io/module-builder/#dementia), you will see that Synthea never uses the SNOMED code `52448006` -- so it is impossible for it appear in your output.

The closest Condition codes you will find are `230265002` or `26929004`.

In the unlikely event that those codes do not appear in your `conditions.csv` file, then please explore the `exporter.years_of_history` feature that is documented here: https://github.com/synthetichealth/synthea/wiki/Common-Configuration#other-export-settings

**Comment by surangak** [comment]
thank you @jawalonoski, it was similar a matter of not looking for the right SNOMED code.
