### ISSUE TITLE
allergic_rhinitis reason error

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#96]
The Wiki requires the reason of a Procedure to be: "the name of the ConditionOnset state which represents the reason for procedure. This ConditionOnset must come before the Procedure in the module".

In this module, there are two reason references to "reason": "has_allergic_rhinitis". While there is a state "Has_Allergic_Rhinitis" it is not a ConditionOnset.

**Comment by jawalonoski** [comment]
Good catch. Thanks for the bug report.
