### ISSUE TITLE
generate.default_population does not affect generated population size

### ISSUE THREAD

**Issue by spiceygas** [synthetichealth/synthea#964]
Trying to generate a population.  Following the [wiki documentation](https://github.com/synthetichealth/synthea/wiki/Common-Configuration), I specified a population size in the configuration file.
`generate.default_population=5`

Run with that configruation file.
`java -jar synthea-with-dependencies.jar -c .\configuration.txt`

Output is only for one patient.
```
Running with options:
Population: 1
Seed: 1639073647528
Provider Seed:1639073647528
Reference Time: 1639073647528
Location: Massachusetts
Min Age: 0
Max Age: 140
1 -- Lakisha305 Toy286 (50 y/o F) Shrewsbury, Massachusetts
Records: total=1, alive=1, dead=0
```

If run with population as a commandline parameter, then it works.
`java -jar synthea-with-dependencies.jar -p 5`
```
Running with options:
Population: 5
Seed: 1639073800180
Provider Seed:1639073800180
Reference Time: 1639073800180
Location: Massachusetts
Min Age: 0
Max Age: 140
1 -- Lacie818 Lynch190 (9 y/o F) Somerville, Massachusetts
4 -- Sid118 Brekke496 (11 y/o M) Boston, Massachusetts
2 -- Patrice780 Paucek755 (17 y/o F) Everett, Massachusetts
3 -- Neda956 Eichmann909 (56 y/o F) Upton, Massachusetts
5 -- Pauline896 Dibbert990 (57 y/o F) Dudley, Massachusetts
Records: total=5, alive=5, dead=0
```

The configuration setting is not working as defined on the wiki.  Either the documentation is wrong, or the feature is broken.

**Comment by hadleynet** [comment]
This is a known limitation, see comment at https://github.com/synthetichealth/synthea/blob/484c3f9d27343698ddde59077b5f5ca83cee156b/src/main/java/App.java#L113

**Comment by spiceygas** [comment]
Thanks for the response.  I updated the wiki page to indicated that it's not implemented so that others are not confused.
