### ISSUE TITLE
Patient resource, Display text for code 2186-5 needs to be changed

### ISSUE THREAD

**Issue by d0roppe** [synthetichealth/synthea#967]
Some of the Synthetic data for Patients has a code of 2186-5 with Display text of "Non Hispanic or Latino", this needs to be changed to "Not Hispanic or Latino" to validate against US Core.
This might have been correct before issue https://github.com/synthetichealth/synthea/issues/783
The display code in the ValueSet doesn’t match whats in the CodeSystem.  The CodeSystem is the one that should be in the instances.

**Comment by lmsurpre** [comment]
I opened https://jira.hl7.org/browse/FHIR-34488 to hopefully avoid this kind of confusion in the future.

In case there is any debate on which display value should be in instances, refer to https://www.hl7.org/fhir/valueset.html#designations
> Any display name for a concept provided in the value set is for display to a human user. The display in the Coding that results from a user selecting a concept from the expansion must be taken from the underlying code system definition, even if a value set is referenced explicitly in the Coding (e.g. by an extension). The correct display for a code can be determined by a $lookup operation. Any alternative display specified in the value set would go in CodeableConcept.text, perhaps appended to the UI label for the matching data element.

**Comment by jawalonoski** [comment]
The code as written is this:

https://github.com/synthetichealth/synthea/blob/9f5ff46eaa8e2b03651fb575ee38dc5016d24efc/src/main/java/org/mitre/synthea/export/FhirR4.java#L479-L485

There may be previously generated sample data sets that do not comply with the current code.

The "current version" of US Core (v4.0.0) says `"Non Hispanic or Latino"` (http://hl7.org/fhir/us/core/STU4/ValueSet-omb-ethnicity-category.json.html).

The latest ballot of US Core (v4.1.0) says `Not Hispanic or Latino` (http://hl7.org/fhir/us/core/2022Jan/ValueSet-omb-ethnicity-category.html and https://vsac.nlm.nih.gov/valueset/2.16.840.1.114222.4.11.837/expansion [UMLS account required])

**Comment by lmsurpre** [comment]
Great, then this should already be fixed.

My point above was that in 4.0.0, even though the valueset uses "Non", the CodeSystem still says "Not" and so that is always the right one to use in an instance.  Glad the latest draft of US Core has changed the valueset display name to avoid future confusion.

**Comment by d0roppe** [comment]
Will test again, but according to this, the issue is fixed.
