### ISSUE TITLE
Multithreaded Sequential Runs Without towns.json Fail

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#99]
If you start a multithreaded run without passing the `towns.json` config file the sequential generation fails, producing the following error:

```
NoMethodError: undefined method 'count' for nil:NilClass
/Users/cduffett/github/synthea/lib/world/sequential.rb:67:in 'run'
lib/tasks/tasks.rake:53:in 'block in (root)'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/rake-11.3.0/exe/rake:27:in '<top>'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/bin/jruby_executable_hooks:15:in '<top>'
Tasks: TOP => synthea:sequential
```

If a multithreaded run cannot be done without `towns.json` we should log an explicit warning and terminate. If it can, we should support it.

**Comment by dehall** [comment]
Fixed by https://github.com/synthetichealth/synthea/commit/461f0085f7f06242dfdfe03e080bb14385bb8093
