### ISSUE TITLE
To retain 'Organization' and 'PractitionerRole' resourceType in Synthea output

### ISSUE THREAD

**Issue by SUHASV117** [synthetichealth/synthea#994]
My Synthea output is not having "Organization" and "PractitionerRole" resourceTypes. How to get that in my Synthea outputs?

**Comment by jawalonoski** [comment]
If you are using default settings, Organization resources will be in `./output/fhir/hospitalInformation*.json`

If you are using default settings, PractitionerRole resources will be in `./output/fhir/practitionerInformation*.json`

PractitionerRole resources are only generated if you are using US Core. 

US Core is enabled and disabled in `synthea.properties` using:

```properties
# Use the US Core R4 Implementation Guide
exporter.fhir.use_us_core_ig = false
```
